# Evaluate Performance Using CatBoost

In [1]:
# Import statements (add as needed)

import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score, cross_validate, train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, FunctionTransformer, PowerTransformer
from sklearn.impute import SimpleImputer

from sklearn.compose import (
    TransformedTargetRegressor,
    make_column_transformer,
)

from sklearn.pipeline import make_pipeline
from skopt import BayesSearchCV
from missforest import MissForest

from sklearn.multioutput import MultiOutputRegressor
from sklearn.multioutput import RegressorChain
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from shap_select import shap_select
import xgboost as xgb
from xgboost import XGBRegressor
import optuna

/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# load both feature engineered dataset.

fe_df = pd.read_csv('../data/feature_engineered_training_set.csv')

In [3]:
fe_df = fe_df.drop(columns=['Unnamed: 0'])
fe_df.head()

,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,elevation,EVI,NDVI,Land Surface Temperature,nir,green,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
0,128.912,555.0,10.0,174.2,167.155040,241.0,636.0,15845.0,11190.0,11426.0,...,0.000001,0.008799,0.488024,1800.0,1725.0,10077420.0,8.676030e+07,9.502319e+07,-37.216627,1.142857
1,74.720,162.9,163.0,124.1,1521.251493,4643.0,7656.0,15190.0,17658.5,9550.0,...,0.007830,0.458929,97.342756,1755.0,1365.0,116294640.0,3.369889e+05,2.440265e+05,-0.523901,0.931034
2,89.254,573.0,80.0,127.5,1471.379902,3984.0,6276.0,14879.0,15210.0,10720.0,...,0.006964,0.393498,96.911494,1472.0,1344.0,93380604.0,2.800000e+01,2.100000e+01,-0.575803,0.821429
3,82.000,203.6,101.0,129.7,1342.659998,2217.0,3957.0,15228.5,14887.0,10943.0,...,0.007228,0.409018,102.307634,1495.0,1430.0,60259174.5,4.884100e+05,4.132700e+05,-0.538889,0.884615
4,56.100,145.1,151.0,129.2,1355.983661,4136.0,7396.0,15130.0,16828.5,9502.5,...,0.004980,0.437815,96.513882,1600.0,1280.0,111901480.0,1.337840e+05,9.556000e+04,-0.784851,0.892857

In [4]:
train_df, test_df = train_test_split(fe_df, test_size=0.3)      # create train set and test set to eval performance

In [5]:
train_df.head()

,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,elevation,EVI,NDVI,Land Surface Temperature,nir,green,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
2014,165.161,1310.0,11.0,204.30000,1012.728952,2907.0,5351.0,14948.5,12732.0,9699.0,...,0.000002,0.132912,5.350128,1825.0,1533.0,79989423.5,4.725000e+03,3.675000e+03,-316.669417,0.925926
1334,121.954,377.0,93.0,173.10000,1363.117917,2946.0,4692.0,15514.0,NaN,NaN,...,0.000251,0.186936,34.724747,1220.0,1159.0,72791688.0,1.819300e+04,1.502900e+04,-11.702699,0.869565
5898,81.145,179.6,20.0,133.30000,115.056783,2186.0,4889.0,14703.5,11544.5,12228.0,...,0.000093,0.254898,3.850726,1792.0,1728.0,71885411.5,1.683745e+06,1.515370e+06,-19.904327,0.933333
2314,245.918,758.0,183.0,168.40001,1296.518526,1623.0,3284.5,14641.0,13889.5,9824.0,...,0.000001,0.145714,0.000000,1782.0,1188.0,48088364.5,4.117773e+04,2.470664e+04,-35.600384,0.900000
5612,113.106,553.0,49.0,174.00000,952.729122,3244.0,5786.0,15102.0,13187.5,9932.0,...,0.000538,0.301439,10.106505,1495.0,1430.0,87380172.0,1.263721e+06,1.029699e+06,-5.551639,0.851852

In [6]:
train_df.shape

(6523, 33)

In [7]:
# Split train_df and test_df into X_train, X_test, y_train and y_test

X_train = train_df.drop(columns=['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus'])
y_train = train_df[['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']]

X_test = test_df.drop(columns=['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus'])
y_test = test_df[['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']]

### Preprocess Data - Catboost doesn't require Imputation or Scaling, can essentially skip this step.

## **Feature Selection**

In [8]:
# Will need to do different feature selection again for CatBoost since preprocessing steps are different than SVR.
# Conduct feature selection using shap_select again.

def perform_feature_selection(X_train, y_train):
    results_dict = {}

    X_tr, X_te, y_tr, y_te = train_test_split(X_train, y_train, test_size=0.2)
    X_te_df = pd.DataFrame(X_te, columns=X_train.columns, index=y_te.index)
    
    
    for target in y_train.columns:
        model = XGBRegressor(n_estimators=1000, verbosity = 0, eval_metric='rmse', objective='reg:squarederror')
        model.fit(X_tr, y_tr[target], eval_set=[(X_te, y_te[target])])

        selected_df = shap_select(model, X_te_df, y_te[target], task="regression", threshold=0.05)
        results_dict[target] = selected_df

    return results_dict

In [15]:
results = perform_feature_selection(X_train, y_train)

[0]	validation_0-rmse:58.85491
[1]	validation_0-rmse:49.90454
[2]	validation_0-rmse:43.98121
[3]	validation_0-rmse:39.98657
[4]	validation_0-rmse:37.09691
[5]	validation_0-rmse:35.05922
[6]	validation_0-rmse:34.03959
[7]	validation_0-rmse:33.39492
[8]	validation_0-rmse:32.66944
[9]	validation_0-rmse:31.96229
[10]	validation_0-rmse:31.51794
[11]	validation_0-rmse:31.27404
[12]	validation_0-rmse:31.06127
[13]	validation_0-rmse:30.93100
[14]	validation_0-rmse:30.66770
[15]	validation_0-rmse:30.61829
[16]	validation_0-rmse:30.24094
[17]	validation_0-rmse:30.12736
[18]	validation_0-rmse:29.86075
[19]	validation_0-rmse:29.73168
[20]	validation_0-rmse:29.58639
[21]	validation_0-rmse:29.61858
[22]	validation_0-rmse:29.61217
[23]	validation_0-rmse:29.52397
[24]	validation_0-rmse:29.41544
[25]	validation_0-rmse:29.36100
[26]	validation_0-rmse:29.31721
[27]	validation_0-rmse:29.21089
[28]	validation_0-rmse:29.19532
[29]	validation_0-rmse:29.12903
[30]	validation_0-rmse:28.97629
[31]	validation_0-rmse:28.95539
[32]	validation_0-rmse:28.94139
[33]	validation_0-rmse:28.86858
[34]	validation_0-rmse:28.85877
[35]	validation_0-rmse:28.86633
[36]	validation_0-rmse:28.80400
[37]	validation_0-rmse:28.88352
[38]	validation_0-rmse:28.84751
[39]	validation_0-rmse:28.84090
[40]	validation_0-rmse:28.77060
[41]	validation_0-rmse:28.74084
[42]	validation_0-rmse:28.76965
[43]	validation_0-rmse:28.77015
[44]	validation_0-rmse:28.78673
[45]	validation_0-rmse:28.79631
[46]	validation_0-rmse:28.79906
[47]	validation_0-rmse:28.79164
[48]	validation_0-rmse:28.78215
[49]	validation_0-rmse:28.75604
[50]	validation_0-rmse:28.76068
[51]	validation_0-rmse:28.76365
[52]	validation_0-rmse:28.72468
[53]	validation_0-rmse:28.71482
[54]	validation_0-rmse:28.68080
[55]	validation_0-rmse:28.62803
[56]	validation_0-rmse:28.62485
[57]	validation_0-rmse:28.59777
[58]	validation_0-rmse:28.62814
[59]	validation_0-rmse:28.62109
[60]	validation_0-rmse:28.64432
[61]	validation_0-rmse:28.58416
[62]	validation_0-rmse:28.55394
[63]	validation_0-rmse:28.53942
[64]	validation_0-rmse:28.55865
[65]	validation_0-rmse:28.61735
[66]	validation_0-rmse:28.61290
[67]	validation_0-rmse:28.61934
[68]	validation_0-rmse:28.61365
[69]	validation_0-rmse:28.61552
[70]	validation_0-rmse:28.61603
[71]	validation_0-rmse:28.59452
[72]	validation_0-rmse:28.59950
[73]	validation_0-rmse:28.57211
[74]	validation_0-rmse:28.57252
[75]	validation_0-rmse:28.60057
[76]	validation_0-rmse:28.60717
[77]	validation_0-rmse:28.62512
[78]	validation_0-rmse:28.62595
[79]	validation_0-rmse:28.63095
[80]	validation_0-rmse:28.63325
[81]	validation_0-rmse:28.63026
[82]	validation_0-rmse:28.65239
[83]	validation_0-rmse:28.63843
[84]	validation_0-rmse:28.64731
[85]	validation_0-rmse:28.66645
[86]	validation_0-rmse:28.66246
[87]	validation_0-rmse:28.63123
[88]	validation_0-rmse:28.57252
[89]	validation_0-rmse:28.59079
[90]	validation_0-rmse:28.60756
[91]	validation_0-rmse:28.60870
[92]	validation_0-rmse:28.56337
[93]	validation_0-rmse:28.54211
[94]	validation_0-rmse:28.55410
[95]	validation_0-rmse:28.53194
[96]	validation_0-rmse:28.52756
[97]	validation_0-rmse:28.52550
[98]	validation_0-rmse:28.54041
[99]	validation_0-rmse:28.52919
[100]	validation_0-rmse:28.52238
[101]	validation_0-rmse:28.54572
[102]	validation_0-rmse:28.52905
[103]	validation_0-rmse:28.54216
[104]	validation_0-rmse:28.53903
[105]	validation_0-rmse:28.51634
[106]	validation_0-rmse:28.50435
[107]	validation_0-rmse:28.53242
[108]	validation_0-rmse:28.51296
[109]	validation_0-rmse:28.50399
[110]	validation_0-rmse:28.51607
[111]	validation_0-rmse:28.52349
[112]	validation_0-rmse:28.51462
[113]	validation_0-rmse:28.51439
[114]	validation_0-rmse:28.49592
[115]	validation_0-rmse:28.50807
[116]	validation_0-rmse:28.49866
[117]	validation_0-rmse:28.48972
[118]	validation_0-rmse:28.50681
[119]	validation_0-rmse:28.49860
[120]	validation_0-rmse:28.48729
[121]	validation_0-rmse:28.49832
[122]	validation_0-rmse:28.49593
[123]	validation_0-rmse:28.49739
[124]	validation_0-rmse:28.48303
[125]	validation_0-rmse:28.49232
[126]	validation_0-rmse:28.47842
[127]	validation_0-rmse:28.48300
[128]	validation_0-rmse:28.49420
[129]	validation_0-rmse:28.50199
[130]	validation_0-rmse:28.51926
[131]	validation_0-rmse:28.52830
[132]	validation_0-rmse:28.53571
[133]	validation_0-rmse:28.54066
[134]	validation_0-rmse:28.54339
[135]	validation_0-rmse:28.51769
[136]	validation_0-rmse:28.53146
[137]	validation_0-rmse:28.53338
[138]	validation_0-rmse:28.50667
[139]	validation_0-rmse:28.49649
[140]	validation_0-rmse:28.51870
[141]	validation_0-rmse:28.52134
[142]	validation_0-rmse:28.52346
[143]	validation_0-rmse:28.53131
[144]	validation_0-rmse:28.53814
[145]	validation_0-rmse:28.52346
[146]	validation_0-rmse:28.52259
[147]	validation_0-rmse:28.52315
[148]	validation_0-rmse:28.52514
[149]	validation_0-rmse:28.52136
[150]	validation_0-rmse:28.53963
[151]	validation_0-rmse:28.54477
[152]	validation_0-rmse:28.53906
[153]	validation_0-rmse:28.54834
[154]	validation_0-rmse:28.53480
[155]	validation_0-rmse:28.53733
[156]	validation_0-rmse:28.54296
[157]	validation_0-rmse:28.53757
[158]	validation_0-rmse:28.52187
[159]	validation_0-rmse:28.52597
[160]	validation_0-rmse:28.52181
[161]	validation_0-rmse:28.52029
[162]	validation_0-rmse:28.52122
[163]	validation_0-rmse:28.51359
[164]	validation_0-rmse:28.50622
[165]	validation_0-rmse:28.49902
[166]	validation_0-rmse:28.50976
[167]	validation_0-rmse:28.51373
[168]	validation_0-rmse:28.50942
[169]	validation_0-rmse:28.51291
[170]	validation_0-rmse:28.50993
[171]	validation_0-rmse:28.53460
[172]	validation_0-rmse:28.52474
[173]	validation_0-rmse:28.51918
[174]	validation_0-rmse:28.50608
[175]	validation_0-rmse:28.49462
[176]	validation_0-rmse:28.48680
[177]	validation_0-rmse:28.48687
[178]	validation_0-rmse:28.48956
[179]	validation_0-rmse:28.49202
[180]	validation_0-rmse:28.49821
[181]	validation_0-rmse:28.50178
[182]	validation_0-rmse:28.50009
[183]	validation_0-rmse:28.51117
[184]	validation_0-rmse:28.51015
[185]	validation_0-rmse:28.51667
[186]	validation_0-rmse:28.51001
[187]	validation_0-rmse:28.50976
[188]	validation_0-rmse:28.52352
[189]	validation_0-rmse:28.52396
[190]	validation_0-rmse:28.52720
[191]	validation_0-rmse:28.51898
[192]	validation_0-rmse:28.51899
[193]	validation_0-rmse:28.52581
[194]	validation_0-rmse:28.51496
[195]	validation_0-rmse:28.51365
[196]	validation_0-rmse:28.51557
[197]	validation_0-rmse:28.51150
[198]	validation_0-rmse:28.51436
[199]	validation_0-rmse:28.51105
[200]	validation_0-rmse:28.51316
[201]	validation_0-rmse:28.52092
[202]	validation_0-rmse:28.52011
[203]	validation_0-rmse:28.51867
[204]	validation_0-rmse:28.52176
[205]	validation_0-rmse:28.52866
[206]	validation_0-rmse:28.53282
[207]	validation_0-rmse:28.54415
[208]	validation_0-rmse:28.54463
[209]	validation_0-rmse:28.54258
[210]	validation_0-rmse:28.54063
[211]	validation_0-rmse:28.53666
[212]	validation_0-rmse:28.53747
[213]	validation_0-rmse:28.52988
[214]	validation_0-rmse:28.52953
[215]	validation_0-rmse:28.53008
[216]	validation_0-rmse:28.53767
[217]	validation_0-rmse:28.53919
[218]	validation_0-rmse:28.54006
[219]	validation_0-rmse:28.53612
[220]	validation_0-rmse:28.53536
[221]	validation_0-rmse:28.54002
[222]	validation_0-rmse:28.54418
[223]	validation_0-rmse:28.54530
[224]	validation_0-rmse:28.54264
[225]	validation_0-rmse:28.54234
[226]	validation_0-rmse:28.53725
[227]	validation_0-rmse:28.53527
[228]	validation_0-rmse:28.53476
[229]	validation_0-rmse:28.53508
[230]	validation_0-rmse:28.53669
[231]	validation_0-rmse:28.54060
[232]	validation_0-rmse:28.53869
[233]	validation_0-rmse:28.53567
[234]	validation_0-rmse:28.52958
[235]	validation_0-rmse:28.52852
[236]	validation_0-rmse:28.52972
[237]	validation_0-rmse:28.53488
[238]	validation_0-rmse:28.53690
[239]	validation_0-rmse:28.53639
[240]	validation_0-rmse:28.53315
[241]	validation_0-rmse:28.53479
[242]	validation_0-rmse:28.53625
[243]	validation_0-rmse:28.53599
[244]	validation_0-rmse:28.53729
[245]	validation_0-rmse:28.53785
[246]	validation_0-rmse:28.53453
[247]	validation_0-rmse:28.53411
[248]	validation_0-rmse:28.53420
[249]	validation_0-rmse:28.53700
[250]	validation_0-rmse:28.53914
[251]	validation_0-rmse:28.53985
[252]	validation_0-rmse:28.54103
[253]	validation_0-rmse:28.53740
[254]	validation_0-rmse:28.53875
[255]	validation_0-rmse:28.54259
[256]	validation_0-rmse:28.54411
[257]	validation_0-rmse:28.54031
[258]	validation_0-rmse:28.54266
[259]	validation_0-rmse:28.54959
[260]	validation_0-rmse:28.55056
[261]	validation_0-rmse:28.55431
[262]	validation_0-rmse:28.54827
[263]	validation_0-rmse:28.54595
[264]	validation_0-rmse:28.54631
[265]	validation_0-rmse:28.54451
[266]	validation_0-rmse:28.54781
[267]	validation_0-rmse:28.54880
[268]	validation_0-rmse:28.54635
[269]	validation_0-rmse:28.54565
[270]	validation_0-rmse:28.54931
[271]	validation_0-rmse:28.55419
[272]	validation_0-rmse:28.55307
[273]	validation_0-rmse:28.55616
[274]	validation_0-rmse:28.55658
[275]	validation_0-rmse:28.55932
[276]	validation_0-rmse:28.56097
[277]	validation_0-rmse:28.56150
[278]	validation_0-rmse:28.56765
[279]	validation_0-rmse:28.57002
[280]	validation_0-rmse:28.57262
[281]	validation_0-rmse:28.57437
[282]	validation_0-rmse:28.57397
[283]	validation_0-rmse:28.57355
[284]	validation_0-rmse:28.57115
[285]	validation_0-rmse:28.57157
[286]	validation_0-rmse:28.57517
[287]	validation_0-rmse:28.57124
[288]	validation_0-rmse:28.56967
[289]	validation_0-rmse:28.57093
[290]	validation_0-rmse:28.56740
[291]	validation_0-rmse:28.56907
[292]	validation_0-rmse:28.56889
[293]	validation_0-rmse:28.56781
[294]	validation_0-rmse:28.56734
[295]	validation_0-rmse:28.56673
[296]	validation_0-rmse:28.56958
[297]	validation_0-rmse:28.56718
[298]	validation_0-rmse:28.56464
[299]	validation_0-rmse:28.57157
[300]	validation_0-rmse:28.56920
[301]	validation_0-rmse:28.56801
[302]	validation_0-rmse:28.57123
[303]	validation_0-rmse:28.56938
[304]	validation_0-rmse:28.57022
[305]	validation_0-rmse:28.57103
[306]	validation_0-rmse:28.57189
[307]	validation_0-rmse:28.57236
[308]	validation_0-rmse:28.56854
[309]	validation_0-rmse:28.56808
[310]	validation_0-rmse:28.57053
[311]	validation_0-rmse:28.56588
[312]	validation_0-rmse:28.56494
[313]	validation_0-rmse:28.56416
[314]	validation_0-rmse:28.57014
[315]	validation_0-rmse:28.57167
[316]	validation_0-rmse:28.57254
[317]	validation_0-rmse:28.57285
[318]	validation_0-rmse:28.56874
[319]	validation_0-rmse:28.57158
[320]	validation_0-rmse:28.57071
[321]	validation_0-rmse:28.57064
[322]	validation_0-rmse:28.56554
[323]	validation_0-rmse:28.56424
[324]	validation_0-rmse:28.56193
[325]	validation_0-rmse:28.56137
[326]	validation_0-rmse:28.55945
[327]	validation_0-rmse:28.56055
[328]	validation_0-rmse:28.56209
[329]	validation_0-rmse:28.56195
[330]	validation_0-rmse:28.56323
[331]	validation_0-rmse:28.56353
[332]	validation_0-rmse:28.56323
[333]	validation_0-rmse:28.56274
[334]	validation_0-rmse:28.56694
[335]	validation_0-rmse:28.56556
[336]	validation_0-rmse:28.56572
[337]	validation_0-rmse:28.56428
[338]	validation_0-rmse:28.56484
[339]	validation_0-rmse:28.56529
[340]	validation_0-rmse:28.56135
[341]	validation_0-rmse:28.56419
[342]	validation_0-rmse:28.56299
[343]	validation_0-rmse:28.56187
[344]	validation_0-rmse:28.56251
[345]	validation_0-rmse:28.56489
[346]	validation_0-rmse:28.56672
[347]	validation_0-rmse:28.56907
[348]	validation_0-rmse:28.56901
[349]	validation_0-rmse:28.56919
[350]	validation_0-rmse:28.56700
[351]	validation_0-rmse:28.56465
[352]	validation_0-rmse:28.56534
[353]	validation_0-rmse:28.56620
[354]	validation_0-rmse:28.56650
[355]	validation_0-rmse:28.56805
[356]	validation_0-rmse:28.56867
[357]	validation_0-rmse:28.56839
[358]	validation_0-rmse:28.57110
[359]	validation_0-rmse:28.57230
[360]	validation_0-rmse:28.57286
[361]	validation_0-rmse:28.57276
[362]	validation_0-rmse:28.56923
[363]	validation_0-rmse:28.56752
[364]	validation_0-rmse:28.56471
[365]	validation_0-rmse:28.56540
[366]	validation_0-rmse:28.56718
[367]	validation_0-rmse:28.56609
[368]	validation_0-rmse:28.56584
[369]	validation_0-rmse:28.56660
[370]	validation_0-rmse:28.56678
[371]	validation_0-rmse:28.56814
[372]	validation_0-rmse:28.56730
[373]	validation_0-rmse:28.56375
[374]	validation_0-rmse:28.56396
[375]	validation_0-rmse:28.56138
[376]	validation_0-rmse:28.56163
[377]	validation_0-rmse:28.56466
[378]	validation_0-rmse:28.56676
[379]	validation_0-rmse:28.56481
[380]	validation_0-rmse:28.56566
[381]	validation_0-rmse:28.56467
[382]	validation_0-rmse:28.56433
[383]	validation_0-rmse:28.56647
[384]	validation_0-rmse:28.56951
[385]	validation_0-rmse:28.57061
[386]	validation_0-rmse:28.57100
[387]	validation_0-rmse:28.57011
[388]	validation_0-rmse:28.57003
[389]	validation_0-rmse:28.57015
[390]	validation_0-rmse:28.56976
[391]	validation_0-rmse:28.56952
[392]	validation_0-rmse:28.57288
[393]	validation_0-rmse:28.57210
[394]	validation_0-rmse:28.57442
[395]	validation_0-rmse:28.57569
[396]	validation_0-rmse:28.57479
[397]	validation_0-rmse:28.57587
[398]	validation_0-rmse:28.57632
[399]	validation_0-rmse:28.57540
[400]	validation_0-rmse:28.57551
[401]	validation_0-rmse:28.57583
[402]	validation_0-rmse:28.57558
[403]	validation_0-rmse:28.57392
[404]	validation_0-rmse:28.57458
[405]	validation_0-rmse:28.57327
[406]	validation_0-rmse:28.57348
[407]	validation_0-rmse:28.57441
[408]	validation_0-rmse:28.57450
[409]	validation_0-rmse:28.57171
[410]	validation_0-rmse:28.57325
[411]	validation_0-rmse:28.57121
[412]	validation_0-rmse:28.57177
[413]	validation_0-rmse:28.57147
[414]	validation_0-rmse:28.56716
[415]	validation_0-rmse:28.56457
[416]	validation_0-rmse:28.56436
[417]	validation_0-rmse:28.56476
[418]	validation_0-rmse:28.56322
[419]	validation_0-rmse:28.56416
[420]	validation_0-rmse:28.56458
[421]	validation_0-rmse:28.56360
[422]	validation_0-rmse:28.56391
[423]	validation_0-rmse:28.56459
[424]	validation_0-rmse:28.56500
[425]	validation_0-rmse:28.56499
[426]	validation_0-rmse:28.56616
[427]	validation_0-rmse:28.56752
[428]	validation_0-rmse:28.56886
[429]	validation_0-rmse:28.57003
[430]	validation_0-rmse:28.57063
[431]	validation_0-rmse:28.57042
[432]	validation_0-rmse:28.57032
[433]	validation_0-rmse:28.57011
[434]	validation_0-rmse:28.57022
[435]	validation_0-rmse:28.56990
[436]	validation_0-rmse:28.56990
[437]	validation_0-rmse:28.56901
[438]	validation_0-rmse:28.56917
[439]	validation_0-rmse:28.56868
[440]	validation_0-rmse:28.56857
[441]	validation_0-rmse:28.56846
[442]	validation_0-rmse:28.56892
[443]	validation_0-rmse:28.56862
[444]	validation_0-rmse:28.56882
[445]	validation_0-rmse:28.56930
[446]	validation_0-rmse:28.56911
[447]	validation_0-rmse:28.56896
[448]	validation_0-rmse:28.56913
[449]	validation_0-rmse:28.56830
[450]	validation_0-rmse:28.56780
[451]	validation_0-rmse:28.56756
[452]	validation_0-rmse:28.56729
[453]	validation_0-rmse:28.56695
[454]	validation_0-rmse:28.56652
[455]	validation_0-rmse:28.56604
[456]	validation_0-rmse:28.56612
[457]	validation_0-rmse:28.56670
[458]	validation_0-rmse:28.56642
[459]	validation_0-rmse:28.56574
[460]	validation_0-rmse:28.56616
[461]	validation_0-rmse:28.56657
[462]	validation_0-rmse:28.56651
[463]	validation_0-rmse:28.56635
[464]	validation_0-rmse:28.56582
[465]	validation_0-rmse:28.56754
[466]	validation_0-rmse:28.56776
[467]	validation_0-rmse:28.56743
[468]	validation_0-rmse:28.56804
[469]	validation_0-rmse:28.56716
[470]	validation_0-rmse:28.56652
[471]	validation_0-rmse:28.56705
[472]	validation_0-rmse:28.56670
[473]	validation_0-rmse:28.56728
[474]	validation_0-rmse:28.56715
[475]	validation_0-rmse:28.56617
[476]	validation_0-rmse:28.56620
[477]	validation_0-rmse:28.56702
[478]	validation_0-rmse:28.56649
[479]	validation_0-rmse:28.56609
[480]	validation_0-rmse:28.56549
[481]	validation_0-rmse:28.56603
[482]	validation_0-rmse:28.56662
[483]	validation_0-rmse:28.56850
[484]	validation_0-rmse:28.56865
[485]	validation_0-rmse:28.56881
[486]	validation_0-rmse:28.56895
[487]	validation_0-rmse:28.56876
[488]	validation_0-rmse:28.56844
[489]	validation_0-rmse:28.56934
[490]	validation_0-rmse:28.56958
[491]	validation_0-rmse:28.56908
[492]	validation_0-rmse:28.56864
[493]	validation_0-rmse:28.56924
[494]	validation_0-rmse:28.57040
[495]	validation_0-rmse:28.57055
[496]	validation_0-rmse:28.57082
[497]	validation_0-rmse:28.57065
[498]	validation_0-rmse:28.57028
[499]	validation_0-rmse:28.56998
[500]	validation_0-rmse:28.56970
[501]	validation_0-rmse:28.56895
[502]	validation_0-rmse:28.56868
[503]	validation_0-rmse:28.56932
[504]	validation_0-rmse:28.56992
[505]	validation_0-rmse:28.57044
[506]	validation_0-rmse:28.57068
[507]	validation_0-rmse:28.57083
[508]	validation_0-rmse:28.57166
[509]	validation_0-rmse:28.57150
[510]	validation_0-rmse:28.57161
[511]	validation_0-rmse:28.57227
[512]	validation_0-rmse:28.57222
[513]	validation_0-rmse:28.57228
[514]	validation_0-rmse:28.57256
[515]	validation_0-rmse:28.57264
[516]	validation_0-rmse:28.57285
[517]	validation_0-rmse:28.57225
[518]	validation_0-rmse:28.57235
[519]	validation_0-rmse:28.57252
[520]	validation_0-rmse:28.57201
[521]	validation_0-rmse:28.57194
[522]	validation_0-rmse:28.57202
[523]	validation_0-rmse:28.57265
[524]	validation_0-rmse:28.57307
[525]	validation_0-rmse:28.57268
[526]	validation_0-rmse:28.57277
[527]	validation_0-rmse:28.57229
[528]	validation_0-rmse:28.57233
[529]	validation_0-rmse:28.57255
[530]	validation_0-rmse:28.57255
[531]	validation_0-rmse:28.57268
[532]	validation_0-rmse:28.57231
[533]	validation_0-rmse:28.57206
[534]	validation_0-rmse:28.57209
[535]	validation_0-rmse:28.57163
[536]	validation_0-rmse:28.57177
[537]	validation_0-rmse:28.57195
[538]	validation_0-rmse:28.57175
[539]	validation_0-rmse:28.57202
[540]	validation_0-rmse:28.57271
[541]	validation_0-rmse:28.57270
[542]	validation_0-rmse:28.57290
[543]	validation_0-rmse:28.57280
[544]	validation_0-rmse:28.57278
[545]	validation_0-rmse:28.57259
[546]	validation_0-rmse:28.57246
[547]	validation_0-rmse:28.57246
[548]	validation_0-rmse:28.57253
[549]	validation_0-rmse:28.57262
[550]	validation_0-rmse:28.57238
[551]	validation_0-rmse:28.57248
[552]	validation_0-rmse:28.57245
[553]	validation_0-rmse:28.57217
[554]	validation_0-rmse:28.57180
[555]	validation_0-rmse:28.57203
[556]	validation_0-rmse:28.57192
[557]	validation_0-rmse:28.57208
[558]	validation_0-rmse:28.57157
[559]	validation_0-rmse:28.57177
[560]	validation_0-rmse:28.57163
[561]	validation_0-rmse:28.57144
[562]	validation_0-rmse:28.57130
[563]	validation_0-rmse:28.57120
[564]	validation_0-rmse:28.57176
[565]	validation_0-rmse:28.57180
[566]	validation_0-rmse:28.57157
[567]	validation_0-rmse:28.57166
[568]	validation_0-rmse:28.57144
[569]	validation_0-rmse:28.57185
[570]	validation_0-rmse:28.57188
[571]	validation_0-rmse:28.57129
[572]	validation_0-rmse:28.57096
[573]	validation_0-rmse:28.57079
[574]	validation_0-rmse:28.57103
[575]	validation_0-rmse:28.57133
[576]	validation_0-rmse:28.57130
[577]	validation_0-rmse:28.57131
[578]	validation_0-rmse:28.57143
[579]	validation_0-rmse:28.57154
[580]	validation_0-rmse:28.57144
[581]	validation_0-rmse:28.57119
[582]	validation_0-rmse:28.57120
[583]	validation_0-rmse:28.57100
[584]	validation_0-rmse:28.57106
[585]	validation_0-rmse:28.57159
[586]	validation_0-rmse:28.57097
[587]	validation_0-rmse:28.57153
[588]	validation_0-rmse:28.57165
[589]	validation_0-rmse:28.57162
[590]	validation_0-rmse:28.57155
[591]	validation_0-rmse:28.57162
[592]	validation_0-rmse:28.57168
[593]	validation_0-rmse:28.57185
[594]	validation_0-rmse:28.57172
[595]	validation_0-rmse:28.57173
[596]	validation_0-rmse:28.57176
[597]	validation_0-rmse:28.57205
[598]	validation_0-rmse:28.57166
[599]	validation_0-rmse:28.57200
[600]	validation_0-rmse:28.57163
[601]	validation_0-rmse:28.57187
[602]	validation_0-rmse:28.57168
[603]	validation_0-rmse:28.57162
[604]	validation_0-rmse:28.57150
[605]	validation_0-rmse:28.57117
[606]	validation_0-rmse:28.57095
[607]	validation_0-rmse:28.57124
[608]	validation_0-rmse:28.57108

In [17]:
results

{'Total Alkalinity':                         feature name    t-value  stat.significance  \
 0                 cec_pH_interaction  15.673946       7.361350e-51
 1                   skin_temperature  15.164197       5.871305e-48
 2                  flow_accumulation  12.205200       1.616905e-32
 3                          elevation   7.912707       5.352284e-15
 4                                nir   7.869746       7.430035e-15
 5                             swir16   6.080586       1.571873e-09
 6            total_precipitation_sum   5.280180       1.511775e-07
 7               NDVI_LST_interaction   4.425181       1.044363e-05
 8                              MNDWI   3.663210       2.591170e-04
 9              total_evaporation_sum   3.185135       1.481363e-03
 10          Land Surface Temperature   2.843609       4.530778e-03
 11                    temperature_2m   2.369782       1.794457e-02
 12             volumetric_soil_water   1.667729       9.561196e-02
 13                               cec  -0.069954       9.442409e-01
 14  flow_acc_phosphorous_interaction  -0.221468       8.247630e-01
 15                              clay  -0.255543       7.983448e-01
 16                               pet  -0.520161       6.030410e-01
 17                             green  -0.524998       5.996752e-01
 18                    cec_clay_ratio  -0.661238       5.085778e-01
 19                               EVI  -1.259359       2.081293e-01
 20        phosphorous_pH_interaction  -1.285840       1.987306e-01
 21                                pH  -1.719172       8.582434e-02
 22                              NDMI  -2.306109       2.126346e-02
 23                  soil_temperature  -2.948311       3.253116e-03
 24         flow_acc_clay_interaction  -2.952959       3.204908e-03
 25                       phosphorous  -3.023520       2.548206e-03
 26                     precipitation  -3.027873       2.512160e-03
 27                            swir22  -3.951081       8.205922e-05
 28                              NDVI  -4.003895       6.589717e-05
 29   evaporation_precipitation_ratio  -5.163014       2.816590e-07

     coefficient  selected
 0      2.105113         1
 1     12.410097         1
 2      3.287594         1
 3      1.337230         1
 4      8.705266         1
 5      7.558047         1
 6      6.222600         1
 7      4.707620         1
 8      3.958302         1
 9      0.967774         1
 10     1.751778         1
 11     3.327922         1
 12     1.249292         0
 13    -0.044293        -1
 14    -0.275254        -1
 15    -0.196338        -1
 16    -0.378052        -1
 17    -0.637052        -1
 18    -0.451176        -1
 19    -1.594252        -1
 20    -0.739441        -1
 21    -2.085732        -1
 22    -3.060451        -1
 23    -3.013066        -1
 24    -2.135984        -1
 25    -1.329574        -1
 26    -4.141558        -1
 27    -4.033764        -1
 28    -4.874800        -1
 29    -7.709064        -1  ,
 'Electrical Conductance':                         feature name    t-value  stat.significance  \
 0                   skin_temperature  22.324280       9.390466e-94
 1                               NDVI  16.207649       5.884577e-54
 2                          elevation  15.098915       1.365217e-47
 3                        phosphorous  14.101849       3.956347e-42
 4              total_evaporation_sum  11.391881       1.004218e-28
 5          flow_acc_clay_interaction   8.683161       1.135191e-17
 6                               clay   8.428970       9.149598e-17
 7                                 pH   6.224477       6.510734e-10
 8                      precipitation   4.194256       2.923808e-05
 9         phosphorous_pH_interaction   4.167529       3.283521e-05
 10                               pet   3.341967       8.556192e-04
 11                    cec_clay_ratio   3.222590       1.302056e-03
 12                cec_pH_interaction   2.561813       1.052539e-02
 13                 flow_accumulation   1.174997       2.402127e-01
 14                               EVI   1.119651       2.630709e-01
 15          Land Surface Temperature   0.973158       3.306573e-01
 16                            swir22   0.343792       7.310585e-01
 17   evaporation_precipitation_ratio   0.011246       9.910291e-01
 18                             MNDWI  -0.205990       8.368312e-01
 19                             green  -0.521705       6.019658e-01
 20                    temperature_2m  -0.528295       5.973860e-01
 21                               cec  -0.796158       4.260878e-01
 22             volumetric_soil_water  -0.874903       3.817908e-01
 23                            swir16  -1.096683       2.729861e-01
 24           total_precipitation_sum  -1.329641       1.838736e-01
 25                               nir  -1.925563       5.438044e-02
 26                              NDMI  -3.077413       2.132477e-03
 27  flow_acc_phosphorous_interaction  -3.364487       7.896135e-04
 28              NDVI_LST_interaction  -8.682481       1.163252e-17
 29                  soil_temperature -15.872846       6.509957e-52

     coefficient  selected
 0     23.739129         1
 1     12.965913         1
 2      2.182123         1
 3      3.090701         1
 4      2.608384         1
 5      5.578783         1
 6      2.165840         1
 7      1.773715         1
 8      4.514108         1
 9      1.534060         1
 10     0.591548         1
 11     0.942956         1
 12     0.935697         1
 13     0.668690         0
 14     0.713138         0
 15     0.528672         0
 16     0.324865         0
 17     0.016827         0
 18    -0.159340        -1
 19    -0.324356        -1
 20    -0.561767        -1
 21    -0.448386        -1
 22    -0.417463        -1
 23    -1.149400        -1
 24    -1.585771        -1
 25    -1.955195        -1
 26    -2.751912        -1
 27    -4.336293        -1
 28    -7.521979        -1
 29   -10.927576        -1  ,
 'Dissolved Reactive Phosphorus':                         feature name    t-value  stat.significance  \
 0         phosphorous_pH_interaction  18.425754       1.455809e-67
 1                 cec_pH_interaction  13.114938       5.327280e-37
 2                                pet   9.655123       2.380420e-21
 3                  flow_accumulation   8.689544       1.074786e-17
 4            total_precipitation_sum   7.329305       4.050940e-13
 5                          elevation   5.852280       6.132620e-09
 6                                EVI   5.726980       1.268731e-08
 7                                nir   4.350751       1.463135e-05
 8   flow_acc_phosphorous_interaction   3.644861       2.781196e-04
 9           Land Surface Temperature   3.122189       1.834864e-03
 10                    cec_clay_ratio   2.298321       2.170233e-02
 11                             MNDWI   1.920879       5.496662e-02
 12         flow_acc_clay_interaction   1.676789       9.382560e-02
 13                               cec   1.582156       1.138589e-01
 14                              NDMI   1.389801       1.648291e-01
 15                       phosphorous   0.972257       3.311049e-01
 16              NDVI_LST_interaction   0.890273       3.734855e-01
 17                     precipitation   0.276220       7.824235e-01
 18                            swir22  -0.242629       8.083317e-01
 19             volumetric_soil_water  -0.320111       7.489359e-01
 20                              clay  -0.430496       6.669072e-01
 21                  skin_temperature  -0.652517       5.141845e-01
 22                  soil_temperature  -0.709761       4.779816e-01
 23             total_evaporation_sum  -1.035832       3.004759e-01
 24                            swir16  -1.322952       1.860876e-01
 25                              NDVI  -1.480070       1.391008e-01
 26                                pH  -2.067152       3.892084e-02
 27   evaporation_precipitation_ratio  -2.490669       1.287656e-02
 28                    temperature_2m  -3.665231       2.572676e-04
 29                             green  -3.666297       2.562007e-04

     coefficient  selected
 0      2.077236         1
 1      4.645637         1
 2      1.867317         1
 3      1.737758         1
 4      3.916985         1
 5      1.194878         1
 6      3.677701         1
 7      2.756765         1
 8      2.340263         1
 9      1.725258         1
 10     0.748671         1
 11     1.082411         0
 12     1.342519         0
 13     1.481153         0
 14     0.755605         0
 15     0.357518         0
 16     0.662912         0
 17     0.185962         0
 18    -0.135042        -1
 19    -0.148157        -1
 20    -0.175997        -1
 21    -0.395447        -1
 22    -0.469486        -1
 23    -0.639003        -1
 24    -0.949444        -1
 25    -1.088617        -1
 26    -0.510686        -1
 27    -1.861645        -1
 28    -1.702803        -1
 29    -2.222721        -1  }

In [9]:
total_alk_feats = ["cec_pH_interaction", "skin_temperature", "flow_accumulation", "elevation", "nir",
                   "swir16", "total_precipitation_sum", "NDVI_LST_interaction", "MNDWI", "total_evaporation_sum",
                   "Land Surface Temperature", "temperature_2m"]

len(total_alk_feats)

12

In [10]:
elec_cond_feats = [
    "skin_temperature",
    "NDVI",
    "elevation",
    "phosphorous",
    "total_evaporation_sum",
    "flow_acc_clay_interaction",
    "clay",
    "pH",
    "precipitation",
    "phosphorous_pH_interaction",
    "pet",
    "cec_clay_ratio",
    "cec_pH_interaction"
]

len(elec_cond_feats)

13

In [11]:
drp_feats = [
    "phosphorous_pH_interaction",
    "cec_pH_interaction",
    "pet",
    "flow_accumulation",
    "total_precipitation_sum",
    "elevation",
    "EVI",
    "nir",
    "flow_acc_phosphorous_interaction",
    "Land Surface Temperature",
    "cec_clay_ratio"
]

len(drp_feats)

11

In [12]:
selected_feats = set(list(total_alk_feats + elec_cond_feats + drp_feats))

len(selected_feats)

23