# Evaluate Performance Using CatBoost

In [16]:
# Import statements (add as needed)

import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score, cross_validate, train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, FunctionTransformer, PowerTransformer
from sklearn.impute import SimpleImputer

from sklearn.compose import (
    TransformedTargetRegressor,
    make_column_transformer,
)

from sklearn.pipeline import make_pipeline
from skopt import BayesSearchCV
from missforest import MissForest

from sklearn.multioutput import MultiOutputRegressor
from sklearn.multioutput import RegressorChain
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from shap_select import shap_select
import xgboost as xgb
from xgboost import XGBRegressor
import optuna
from catboost import CatBoostRegressor

In [2]:
# load both feature engineered dataset.

fe_df = pd.read_csv('../data/feature_engineered_training_set.csv')

In [3]:
fe_df = fe_df.drop(columns=['Unnamed: 0'])
fe_df.head()

,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,elevation,EVI,NDVI,Land Surface Temperature,nir,green,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
0,128.912,555.0,10.0,174.2,167.155040,241.0,636.0,15845.0,11190.0,11426.0,...,0.000001,0.008799,0.488024,1800.0,1725.0,10077420.0,8.676030e+07,9.502319e+07,-37.216627,1.142857
1,74.720,162.9,163.0,124.1,1521.251493,4643.0,7656.0,15190.0,17658.5,9550.0,...,0.007830,0.458929,97.342756,1755.0,1365.0,116294640.0,3.369889e+05,2.440265e+05,-0.523901,0.931034
2,89.254,573.0,80.0,127.5,1471.379902,3984.0,6276.0,14879.0,15210.0,10720.0,...,0.006964,0.393498,96.911494,1472.0,1344.0,93380604.0,2.800000e+01,2.100000e+01,-0.575803,0.821429
3,82.000,203.6,101.0,129.7,1342.659998,2217.0,3957.0,15228.5,14887.0,10943.0,...,0.007228,0.409018,102.307634,1495.0,1430.0,60259174.5,4.884100e+05,4.132700e+05,-0.538889,0.884615
4,56.100,145.1,151.0,129.2,1355.983661,4136.0,7396.0,15130.0,16828.5,9502.5,...,0.004980,0.437815,96.513882,1600.0,1280.0,111901480.0,1.337840e+05,9.556000e+04,-0.784851,0.892857

In [4]:
train_df, test_df = train_test_split(fe_df, test_size=0.3)      # create train set and test set to eval performance

In [5]:
train_df.head()

,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,elevation,EVI,NDVI,Land Surface Temperature,nir,green,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
2014,165.161,1310.0,11.0,204.30000,1012.728952,2907.0,5351.0,14948.5,12732.0,9699.0,...,0.000002,0.132912,5.350128,1825.0,1533.0,79989423.5,4.725000e+03,3.675000e+03,-316.669417,0.925926
1334,121.954,377.0,93.0,173.10000,1363.117917,2946.0,4692.0,15514.0,NaN,NaN,...,0.000251,0.186936,34.724747,1220.0,1159.0,72791688.0,1.819300e+04,1.502900e+04,-11.702699,0.869565
5898,81.145,179.6,20.0,133.30000,115.056783,2186.0,4889.0,14703.5,11544.5,12228.0,...,0.000093,0.254898,3.850726,1792.0,1728.0,71885411.5,1.683745e+06,1.515370e+06,-19.904327,0.933333
2314,245.918,758.0,183.0,168.40001,1296.518526,1623.0,3284.5,14641.0,13889.5,9824.0,...,0.000001,0.145714,0.000000,1782.0,1188.0,48088364.5,4.117773e+04,2.470664e+04,-35.600384,0.900000
5612,113.106,553.0,49.0,174.00000,952.729122,3244.0,5786.0,15102.0,13187.5,9932.0,...,0.000538,0.301439,10.106505,1495.0,1430.0,87380172.0,1.263721e+06,1.029699e+06,-5.551639,0.851852

In [6]:
train_df.shape

(6523, 33)

In [7]:
# Split train_df and test_df into X_train, X_test, y_train and y_test

X_train = train_df.drop(columns=['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus'])
y_train = train_df[['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']]

X_test = test_df.drop(columns=['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus'])
y_test = test_df[['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']]

### Preprocess Data - Catboost doesn't require Imputation or Scaling, can essentially skip this step.

## **Feature Selection**

In [8]:
# Will need to do different feature selection again for CatBoost since preprocessing steps are different than SVR.
# Conduct feature selection using shap_select again.

def perform_feature_selection(X_train, y_train):
    results_dict = {}

    X_tr, X_te, y_tr, y_te = train_test_split(X_train, y_train, test_size=0.2)
    X_te_df = pd.DataFrame(X_te, columns=X_train.columns, index=y_te.index)
    
    
    for target in y_train.columns:
        model = XGBRegressor(n_estimators=1000, verbosity = 0, eval_metric='rmse', objective='reg:squarederror')
        model.fit(X_tr, y_tr[target], eval_set=[(X_te, y_te[target])])

        selected_df = shap_select(model, X_te_df, y_te[target], task="regression", threshold=0.05)
        results_dict[target] = selected_df

    return results_dict

In [15]:
results = perform_feature_selection(X_train, y_train)

[0]	validation_0-rmse:58.85491
[1]	validation_0-rmse:49.90454
[2]	validation_0-rmse:43.98121
[3]	validation_0-rmse:39.98657
[4]	validation_0-rmse:37.09691
[5]	validation_0-rmse:35.05922
[6]	validation_0-rmse:34.03959
[7]	validation_0-rmse:33.39492
[8]	validation_0-rmse:32.66944
[9]	validation_0-rmse:31.96229
[10]	validation_0-rmse:31.51794
[11]	validation_0-rmse:31.27404
[12]	validation_0-rmse:31.06127
[13]	validation_0-rmse:30.93100
[14]	validation_0-rmse:30.66770
[15]	validation_0-rmse:30.61829
[16]	validation_0-rmse:30.24094
[17]	validation_0-rmse:30.12736
[18]	validation_0-rmse:29.86075
[19]	validation_0-rmse:29.73168
[20]	validation_0-rmse:29.58639
[21]	validation_0-rmse:29.61858
[22]	validation_0-rmse:29.61217
[23]	validation_0-rmse:29.52397
[24]	validation_0-rmse:29.41544
[25]	validation_0-rmse:29.36100
[26]	validation_0-rmse:29.31721
[27]	validation_0-rmse:29.21089
[28]	validation_0-rmse:29.19532
[29]	validation_0-rmse:29.12903
[30]	validation_0-rmse:28.97629
[31]	validation_0-rmse:28.95539
[32]	validation_0-rmse:28.94139
[33]	validation_0-rmse:28.86858
[34]	validation_0-rmse:28.85877
[35]	validation_0-rmse:28.86633
[36]	validation_0-rmse:28.80400
[37]	validation_0-rmse:28.88352
[38]	validation_0-rmse:28.84751
[39]	validation_0-rmse:28.84090
[40]	validation_0-rmse:28.77060
[41]	validation_0-rmse:28.74084
[42]	validation_0-rmse:28.76965
[43]	validation_0-rmse:28.77015
[44]	validation_0-rmse:28.78673
[45]	validation_0-rmse:28.79631
[46]	validation_0-rmse:28.79906
[47]	validation_0-rmse:28.79164
[48]	validation_0-rmse:28.78215
[49]	validation_0-rmse:28.75604
[50]	validation_0-rmse:28.76068
[51]	validation_0-rmse:28.76365
[52]	validation_0-rmse:28.72468
[53]	validation_0-rmse:28.71482
[54]	validation_0-rmse:28.68080
[55]	validation_0-rmse:28.62803
[56]	validation_0-rmse:28.62485
[57]	validation_0-rmse:28.59777
[58]	validation_0-rmse:28.62814
[59]	validation_0-rmse:28.62109
[60]	validation_0-rmse:28.64432
[61]	validation_0-rmse:28.58416
[62]	validation_0-rmse:28.55394
[63]	validation_0-rmse:28.53942
[64]	validation_0-rmse:28.55865
[65]	validation_0-rmse:28.61735
[66]	validation_0-rmse:28.61290
[67]	validation_0-rmse:28.61934
[68]	validation_0-rmse:28.61365
[69]	validation_0-rmse:28.61552
[70]	validation_0-rmse:28.61603
[71]	validation_0-rmse:28.59452
[72]	validation_0-rmse:28.59950
[73]	validation_0-rmse:28.57211
[74]	validation_0-rmse:28.57252
[75]	validation_0-rmse:28.60057
[76]	validation_0-rmse:28.60717
[77]	validation_0-rmse:28.62512
[78]	validation_0-rmse:28.62595
[79]	validation_0-rmse:28.63095
[80]	validation_0-rmse:28.63325
[81]	validation_0-rmse:28.63026
[82]	validation_0-rmse:28.65239
[83]	validation_0-rmse:28.63843
[84]	validation_0-rmse:28.64731
[85]	validation_0-rmse:28.66645
[86]	validation_0-rmse:28.66246
[87]	validation_0-rmse:28.63123
[88]	validation_0-rmse:28.57252
[89]	validation_0-rmse:28.59079
[90]	validation_0-rmse:28.60756
[91]	validation_0-rmse:28.60870
[92]	validation_0-rmse:28.56337
[93]	validation_0-rmse:28.54211
[94]	validation_0-rmse:28.55410
[95]	validation_0-rmse:28.53194
[96]	validation_0-rmse:28.52756
[97]	validation_0-rmse:28.52550
[98]	validation_0-rmse:28.54041
[99]	validation_0-rmse:28.52919
[100]	validation_0-rmse:28.52238
[101]	validation_0-rmse:28.54572
[102]	validation_0-rmse:28.52905
[103]	validation_0-rmse:28.54216
[104]	validation_0-rmse:28.53903
[105]	validation_0-rmse:28.51634
[106]	validation_0-rmse:28.50435
[107]	validation_0-rmse:28.53242
[108]	validation_0-rmse:28.51296
[109]	validation_0-rmse:28.50399
[110]	validation_0-rmse:28.51607
[111]	validation_0-rmse:28.52349
[112]	validation_0-rmse:28.51462
[113]	validation_0-rmse:28.51439
[114]	validation_0-rmse:28.49592
[115]	validation_0-rmse:28.50807
[116]	validation_0-rmse:28.49866
[117]	validation_0-rmse:28.48972
[118]	validation_0-rmse:28.50681
[119]	validation_0-rmse:28.49860
[120]	validation_0-rmse:28.48729
[121]	validation_0-rmse:28.49832
[122]	validation_0-rmse:28.49593
[123]	validation_0-rmse:28.49739
[124]	validation_0-rmse:28.48303
[125]	validation_0-rmse:28.49232
[126]	validation_0-rmse:28.47842
[127]	validation_0-rmse:28.48300
[128]	validation_0-rmse:28.49420
[129]	validation_0-rmse:28.50199
[130]	validation_0-rmse:28.51926
[131]	validation_0-rmse:28.52830
[132]	validation_0-rmse:28.53571
[133]	validation_0-rmse:28.54066
[134]	validation_0-rmse:28.54339
[135]	validation_0-rmse:28.51769
[136]	validation_0-rmse:28.53146
[137]	validation_0-rmse:28.53338
[138]	validation_0-rmse:28.50667
[139]	validation_0-rmse:28.49649
[140]	validation_0-rmse:28.51870
[141]	validation_0-rmse:28.52134
[142]	validation_0-rmse:28.52346
[143]	validation_0-rmse:28.53131
[144]	validation_0-rmse:28.53814
[145]	validation_0-rmse:28.52346
[146]	validation_0-rmse:28.52259
[147]	validation_0-rmse:28.52315
[148]	validation_0-rmse:28.52514
[149]	validation_0-rmse:28.52136
[150]	validation_0-rmse:28.53963
[151]	validation_0-rmse:28.54477
[152]	validation_0-rmse:28.53906
[153]	validation_0-rmse:28.54834
[154]	validation_0-rmse:28.53480
[155]	validation_0-rmse:28.53733
[156]	validation_0-rmse:28.54296
[157]	validation_0-rmse:28.53757
[158]	validation_0-rmse:28.52187
[159]	validation_0-rmse:28.52597
[160]	validation_0-rmse:28.52181
[161]	validation_0-rmse:28.52029
[162]	validation_0-rmse:28.52122
[163]	validation_0-rmse:28.51359
[164]	validation_0-rmse:28.50622
[165]	validation_0-rmse:28.49902
[166]	validation_0-rmse:28.50976
[167]	validation_0-rmse:28.51373
[168]	validation_0-rmse:28.50942
[169]	validation_0-rmse:28.51291
[170]	validation_0-rmse:28.50993
[171]	validation_0-rmse:28.53460
[172]	validation_0-rmse:28.52474
[173]	validation_0-rmse:28.51918
[174]	validation_0-rmse:28.50608
[175]	validation_0-rmse:28.49462
[176]	validation_0-rmse:28.48680
[177]	validation_0-rmse:28.48687
[178]	validation_0-rmse:28.48956
[179]	validation_0-rmse:28.49202
[180]	validation_0-rmse:28.49821
[181]	validation_0-rmse:28.50178
[182]	validation_0-rmse:28.50009
[183]	validation_0-rmse:28.51117
[184]	validation_0-rmse:28.51015
[185]	validation_0-rmse:28.51667
[186]	validation_0-rmse:28.51001
[187]	validation_0-rmse:28.50976
[188]	validation_0-rmse:28.52352
[189]	validation_0-rmse:28.52396
[190]	validation_0-rmse:28.52720
[191]	validation_0-rmse:28.51898
[192]	validation_0-rmse:28.51899
[193]	validation_0-rmse:28.52581
[194]	validation_0-rmse:28.51496
[195]	validation_0-rmse:28.51365
[196]	validation_0-rmse:28.51557
[197]	validation_0-rmse:28.51150
[198]	validation_0-rmse:28.51436
[199]	validation_0-rmse:28.51105
[200]	validation_0-rmse:28.51316
[201]	validation_0-rmse:28.52092
[202]	validation_0-rmse:28.52011
[203]	validation_0-rmse:28.51867
[204]	validation_0-rmse:28.52176
[205]	validation_0-rmse:28.52866
[206]	validation_0-rmse:28.53282
[207]	validation_0-rmse:28.54415
[208]	validation_0-rmse:28.54463
[209]	validation_0-rmse:28.54258
[210]	validation_0-rmse:28.54063
[211]	validation_0-rmse:28.53666
[212]	validation_0-rmse:28.53747
[213]	validation_0-rmse:28.52988
[214]	validation_0-rmse:28.52953
[215]	validation_0-rmse:28.53008
[216]	validation_0-rmse:28.53767
[217]	validation_0-rmse:28.53919
[218]	validation_0-rmse:28.54006
[219]	validation_0-rmse:28.53612
[220]	validation_0-rmse:28.53536
[221]	validation_0-rmse:28.54002
[222]	validation_0-rmse:28.54418
[223]	validation_0-rmse:28.54530
[224]	validation_0-rmse:28.54264
[225]	validation_0-rmse:28.54234
[226]	validation_0-rmse:28.53725
[227]	validation_0-rmse:28.53527
[228]	validation_0-rmse:28.53476
[229]	validation_0-rmse:28.53508
[230]	validation_0-rmse:28.53669
[231]	validation_0-rmse:28.54060
[232]	validation_0-rmse:28.53869
[233]	validation_0-rmse:28.53567
[234]	validation_0-rmse:28.52958
[235]	validation_0-rmse:28.52852
[236]	validation_0-rmse:28.52972
[237]	validation_0-rmse:28.53488
[238]	validation_0-rmse:28.53690
[239]	validation_0-rmse:28.53639
[240]	validation_0-rmse:28.53315
[241]	validation_0-rmse:28.53479
[242]	validation_0-rmse:28.53625
[243]	validation_0-rmse:28.53599
[244]	validation_0-rmse:28.53729
[245]	validation_0-rmse:28.53785
[246]	validation_0-rmse:28.53453
[247]	validation_0-rmse:28.53411
[248]	validation_0-rmse:28.53420
[249]	validation_0-rmse:28.53700
[250]	validation_0-rmse:28.53914
[251]	validation_0-rmse:28.53985
[252]	validation_0-rmse:28.54103
[253]	validation_0-rmse:28.53740
[254]	validation_0-rmse:28.53875
[255]	validation_0-rmse:28.54259
[256]	validation_0-rmse:28.54411
[257]	validation_0-rmse:28.54031
[258]	validation_0-rmse:28.54266
[259]	validation_0-rmse:28.54959
[260]	validation_0-rmse:28.55056
[261]	validation_0-rmse:28.55431
[262]	validation_0-rmse:28.54827
[263]	validation_0-rmse:28.54595
[264]	validation_0-rmse:28.54631
[265]	validation_0-rmse:28.54451
[266]	validation_0-rmse:28.54781
[267]	validation_0-rmse:28.54880
[268]	validation_0-rmse:28.54635
[269]	validation_0-rmse:28.54565
[270]	validation_0-rmse:28.54931
[271]	validation_0-rmse:28.55419
[272]	validation_0-rmse:28.55307
[273]	validation_0-rmse:28.55616
[274]	validation_0-rmse:28.55658
[275]	validation_0-rmse:28.55932
[276]	validation_0-rmse:28.56097
[277]	validation_0-rmse:28.56150
[278]	validation_0-rmse:28.56765
[279]	validation_0-rmse:28.57002
[280]	validation_0-rmse:28.57262
[281]	validation_0-rmse:28.57437
[282]	validation_0-rmse:28.57397
[283]	validation_0-rmse:28.57355
[284]	validation_0-rmse:28.57115
[285]	validation_0-rmse:28.57157
[286]	validation_0-rmse:28.57517
[287]	validation_0-rmse:28.57124
[288]	validation_0-rmse:28.56967
[289]	validation_0-rmse:28.57093
[290]	validation_0-rmse:28.56740
[291]	validation_0-rmse:28.56907
[292]	validation_0-rmse:28.56889
[293]	validation_0-rmse:28.56781
[294]	validation_0-rmse:28.56734
[295]	validation_0-rmse:28.56673
[296]	validation_0-rmse:28.56958
[297]	validation_0-rmse:28.56718
[298]	validation_0-rmse:28.56464
[299]	validation_0-rmse:28.57157
[300]	validation_0-rmse:28.56920
[301]	validation_0-rmse:28.56801
[302]	validation_0-rmse:28.57123
[303]	validation_0-rmse:28.56938
[304]	validation_0-rmse:28.57022
[305]	validation_0-rmse:28.57103
[306]	validation_0-rmse:28.57189
[307]	validation_0-rmse:28.57236
[308]	validation_0-rmse:28.56854
[309]	validation_0-rmse:28.56808
[310]	validation_0-rmse:28.57053
[311]	validation_0-rmse:28.56588
[312]	validation_0-rmse:28.56494
[313]	validation_0-rmse:28.56416
[314]	validation_0-rmse:28.57014
[315]	validation_0-rmse:28.57167
[316]	validation_0-rmse:28.57254
[317]	validation_0-rmse:28.57285
[318]	validation_0-rmse:28.56874
[319]	validation_0-rmse:28.57158
[320]	validation_0-rmse:28.57071
[321]	validation_0-rmse:28.57064
[322]	validation_0-rmse:28.56554
[323]	validation_0-rmse:28.56424
[324]	validation_0-rmse:28.56193
[325]	validation_0-rmse:28.56137
[326]	validation_0-rmse:28.55945
[327]	validation_0-rmse:28.56055
[328]	validation_0-rmse:28.56209
[329]	validation_0-rmse:28.56195
[330]	validation_0-rmse:28.56323
[331]	validation_0-rmse:28.56353
[332]	validation_0-rmse:28.56323
[333]	validation_0-rmse:28.56274
[334]	validation_0-rmse:28.56694
[335]	validation_0-rmse:28.56556
[336]	validation_0-rmse:28.56572
[337]	validation_0-rmse:28.56428
[338]	validation_0-rmse:28.56484
[339]	validation_0-rmse:28.56529
[340]	validation_0-rmse:28.56135
[341]	validation_0-rmse:28.56419
[342]	validation_0-rmse:28.56299
[343]	validation_0-rmse:28.56187
[344]	validation_0-rmse:28.56251
[345]	validation_0-rmse:28.56489
[346]	validation_0-rmse:28.56672
[347]	validation_0-rmse:28.56907
[348]	validation_0-rmse:28.56901
[349]	validation_0-rmse:28.56919
[350]	validation_0-rmse:28.56700
[351]	validation_0-rmse:28.56465
[352]	validation_0-rmse:28.56534
[353]	validation_0-rmse:28.56620
[354]	validation_0-rmse:28.56650
[355]	validation_0-rmse:28.56805
[356]	validation_0-rmse:28.56867
[357]	validation_0-rmse:28.56839
[358]	validation_0-rmse:28.57110
[359]	validation_0-rmse:28.57230
[360]	validation_0-rmse:28.57286
[361]	validation_0-rmse:28.57276
[362]	validation_0-rmse:28.56923
[363]	validation_0-rmse:28.56752
[364]	validation_0-rmse:28.56471
[365]	validation_0-rmse:28.56540
[366]	validation_0-rmse:28.56718
[367]	validation_0-rmse:28.56609
[368]	validation_0-rmse:28.56584
[369]	validation_0-rmse:28.56660
[370]	validation_0-rmse:28.56678
[371]	validation_0-rmse:28.56814
[372]	validation_0-rmse:28.56730
[373]	validation_0-rmse:28.56375
[374]	validation_0-rmse:28.56396
[375]	validation_0-rmse:28.56138
[376]	validation_0-rmse:28.56163
[377]	validation_0-rmse:28.56466
[378]	validation_0-rmse:28.56676
[379]	validation_0-rmse:28.56481
[380]	validation_0-rmse:28.56566
[381]	validation_0-rmse:28.56467
[382]	validation_0-rmse:28.56433
[383]	validation_0-rmse:28.56647
[384]	validation_0-rmse:28.56951
[385]	validation_0-rmse:28.57061
[386]	validation_0-rmse:28.57100
[387]	validation_0-rmse:28.57011
[388]	validation_0-rmse:28.57003
[389]	validation_0-rmse:28.57015
[390]	validation_0-rmse:28.56976
[391]	validation_0-rmse:28.56952
[392]	validation_0-rmse:28.57288
[393]	validation_0-rmse:28.57210
[394]	validation_0-rmse:28.57442
[395]	validation_0-rmse:28.57569
[396]	validation_0-rmse:28.57479
[397]	validation_0-rmse:28.57587
[398]	validation_0-rmse:28.57632
[399]	validation_0-rmse:28.57540
[400]	validation_0-rmse:28.57551
[401]	validation_0-rmse:28.57583
[402]	validation_0-rmse:28.57558
[403]	validation_0-rmse:28.57392
[404]	validation_0-rmse:28.57458
[405]	validation_0-rmse:28.57327
[406]	validation_0-rmse:28.57348
[407]	validation_0-rmse:28.57441
[408]	validation_0-rmse:28.57450
[409]	validation_0-rmse:28.57171
[410]	validation_0-rmse:28.57325
[411]	validation_0-rmse:28.57121
[412]	validation_0-rmse:28.57177
[413]	validation_0-rmse:28.57147
[414]	validation_0-rmse:28.56716
[415]	validation_0-rmse:28.56457
[416]	validation_0-rmse:28.56436
[417]	validation_0-rmse:28.56476
[418]	validation_0-rmse:28.56322
[419]	validation_0-rmse:28.56416
[420]	validation_0-rmse:28.56458
[421]	validation_0-rmse:28.56360
[422]	validation_0-rmse:28.56391
[423]	validation_0-rmse:28.56459
[424]	validation_0-rmse:28.56500
[425]	validation_0-rmse:28.56499
[426]	validation_0-rmse:28.56616
[427]	validation_0-rmse:28.56752
[428]	validation_0-rmse:28.56886
[429]	validation_0-rmse:28.57003
[430]	validation_0-rmse:28.57063
[431]	validation_0-rmse:28.57042
[432]	validation_0-rmse:28.57032
[433]	validation_0-rmse:28.57011
[434]	validation_0-rmse:28.57022
[435]	validation_0-rmse:28.56990
[436]	validation_0-rmse:28.56990
[437]	validation_0-rmse:28.56901
[438]	validation_0-rmse:28.56917
[439]	validation_0-rmse:28.56868
[440]	validation_0-rmse:28.56857
[441]	validation_0-rmse:28.56846
[442]	validation_0-rmse:28.56892
[443]	validation_0-rmse:28.56862
[444]	validation_0-rmse:28.56882
[445]	validation_0-rmse:28.56930
[446]	validation_0-rmse:28.56911
[447]	validation_0-rmse:28.56896
[448]	validation_0-rmse:28.56913
[449]	validation_0-rmse:28.56830
[450]	validation_0-rmse:28.56780
[451]	validation_0-rmse:28.56756
[452]	validation_0-rmse:28.56729
[453]	validation_0-rmse:28.56695
[454]	validation_0-rmse:28.56652
[455]	validation_0-rmse:28.56604
[456]	validation_0-rmse:28.56612
[457]	validation_0-rmse:28.56670
[458]	validation_0-rmse:28.56642
[459]	validation_0-rmse:28.56574
[460]	validation_0-rmse:28.56616
[461]	validation_0-rmse:28.56657
[462]	validation_0-rmse:28.56651
[463]	validation_0-rmse:28.56635
[464]	validation_0-rmse:28.56582
[465]	validation_0-rmse:28.56754
[466]	validation_0-rmse:28.56776
[467]	validation_0-rmse:28.56743
[468]	validation_0-rmse:28.56804
[469]	validation_0-rmse:28.56716
[470]	validation_0-rmse:28.56652
[471]	validation_0-rmse:28.56705
[472]	validation_0-rmse:28.56670
[473]	validation_0-rmse:28.56728
[474]	validation_0-rmse:28.56715
[475]	validation_0-rmse:28.56617
[476]	validation_0-rmse:28.56620
[477]	validation_0-rmse:28.56702
[478]	validation_0-rmse:28.56649
[479]	validation_0-rmse:28.56609
[480]	validation_0-rmse:28.56549
[481]	validation_0-rmse:28.56603
[482]	validation_0-rmse:28.56662
[483]	validation_0-rmse:28.56850
[484]	validation_0-rmse:28.56865
[485]	validation_0-rmse:28.56881
[486]	validation_0-rmse:28.56895
[487]	validation_0-rmse:28.56876
[488]	validation_0-rmse:28.56844
[489]	validation_0-rmse:28.56934
[490]	validation_0-rmse:28.56958
[491]	validation_0-rmse:28.56908
[492]	validation_0-rmse:28.56864
[493]	validation_0-rmse:28.56924
[494]	validation_0-rmse:28.57040
[495]	validation_0-rmse:28.57055
[496]	validation_0-rmse:28.57082
[497]	validation_0-rmse:28.57065
[498]	validation_0-rmse:28.57028
[499]	validation_0-rmse:28.56998
[500]	validation_0-rmse:28.56970
[501]	validation_0-rmse:28.56895
[502]	validation_0-rmse:28.56868
[503]	validation_0-rmse:28.56932
[504]	validation_0-rmse:28.56992
[505]	validation_0-rmse:28.57044
[506]	validation_0-rmse:28.57068
[507]	validation_0-rmse:28.57083
[508]	validation_0-rmse:28.57166
[509]	validation_0-rmse:28.57150
[510]	validation_0-rmse:28.57161
[511]	validation_0-rmse:28.57227
[512]	validation_0-rmse:28.57222
[513]	validation_0-rmse:28.57228
[514]	validation_0-rmse:28.57256
[515]	validation_0-rmse:28.57264
[516]	validation_0-rmse:28.57285
[517]	validation_0-rmse:28.57225
[518]	validation_0-rmse:28.57235
[519]	validation_0-rmse:28.57252
[520]	validation_0-rmse:28.57201
[521]	validation_0-rmse:28.57194
[522]	validation_0-rmse:28.57202
[523]	validation_0-rmse:28.57265
[524]	validation_0-rmse:28.57307
[525]	validation_0-rmse:28.57268
[526]	validation_0-rmse:28.57277
[527]	validation_0-rmse:28.57229
[528]	validation_0-rmse:28.57233
[529]	validation_0-rmse:28.57255
[530]	validation_0-rmse:28.57255
[531]	validation_0-rmse:28.57268
[532]	validation_0-rmse:28.57231
[533]	validation_0-rmse:28.57206
[534]	validation_0-rmse:28.57209
[535]	validation_0-rmse:28.57163
[536]	validation_0-rmse:28.57177
[537]	validation_0-rmse:28.57195
[538]	validation_0-rmse:28.57175
[539]	validation_0-rmse:28.57202
[540]	validation_0-rmse:28.57271
[541]	validation_0-rmse:28.57270
[542]	validation_0-rmse:28.57290
[543]	validation_0-rmse:28.57280
[544]	validation_0-rmse:28.57278
[545]	validation_0-rmse:28.57259
[546]	validation_0-rmse:28.57246
[547]	validation_0-rmse:28.57246
[548]	validation_0-rmse:28.57253
[549]	validation_0-rmse:28.57262
[550]	validation_0-rmse:28.57238
[551]	validation_0-rmse:28.57248
[552]	validation_0-rmse:28.57245
[553]	validation_0-rmse:28.57217
[554]	validation_0-rmse:28.57180
[555]	validation_0-rmse:28.57203
[556]	validation_0-rmse:28.57192
[557]	validation_0-rmse:28.57208
[558]	validation_0-rmse:28.57157
[559]	validation_0-rmse:28.57177
[560]	validation_0-rmse:28.57163
[561]	validation_0-rmse:28.57144
[562]	validation_0-rmse:28.57130
[563]	validation_0-rmse:28.57120
[564]	validation_0-rmse:28.57176
[565]	validation_0-rmse:28.57180
[566]	validation_0-rmse:28.57157
[567]	validation_0-rmse:28.57166
[568]	validation_0-rmse:28.57144
[569]	validation_0-rmse:28.57185
[570]	validation_0-rmse:28.57188
[571]	validation_0-rmse:28.57129
[572]	validation_0-rmse:28.57096
[573]	validation_0-rmse:28.57079
[574]	validation_0-rmse:28.57103
[575]	validation_0-rmse:28.57133
[576]	validation_0-rmse:28.57130
[577]	validation_0-rmse:28.57131
[578]	validation_0-rmse:28.57143
[579]	validation_0-rmse:28.57154
[580]	validation_0-rmse:28.57144
[581]	validation_0-rmse:28.57119
[582]	validation_0-rmse:28.57120
[583]	validation_0-rmse:28.57100
[584]	validation_0-rmse:28.57106
[585]	validation_0-rmse:28.57159
[586]	validation_0-rmse:28.57097
[587]	validation_0-rmse:28.57153
[588]	validation_0-rmse:28.57165
[589]	validation_0-rmse:28.57162
[590]	validation_0-rmse:28.57155
[591]	validation_0-rmse:28.57162
[592]	validation_0-rmse:28.57168
[593]	validation_0-rmse:28.57185
[594]	validation_0-rmse:28.57172
[595]	validation_0-rmse:28.57173
[596]	validation_0-rmse:28.57176
[597]	validation_0-rmse:28.57205
[598]	validation_0-rmse:28.57166
[599]	validation_0-rmse:28.57200
[600]	validation_0-rmse:28.57163
[601]	validation_0-rmse:28.57187
[602]	validation_0-rmse:28.57168
[603]	validation_0-rmse:28.57162
[604]	validation_0-rmse:28.57150
[605]	validation_0-rmse:28.57117
[606]	validation_0-rmse:28.57095
[607]	validation_0-rmse:28.57124
[608]	validation_0-rmse:28.57108

In [17]:
results

{'Total Alkalinity':                         feature name    t-value  stat.significance  \
 0                 cec_pH_interaction  15.673946       7.361350e-51
 1                   skin_temperature  15.164197       5.871305e-48
 2                  flow_accumulation  12.205200       1.616905e-32
 3                          elevation   7.912707       5.352284e-15
 4                                nir   7.869746       7.430035e-15
 5                             swir16   6.080586       1.571873e-09
 6            total_precipitation_sum   5.280180       1.511775e-07
 7               NDVI_LST_interaction   4.425181       1.044363e-05
 8                              MNDWI   3.663210       2.591170e-04
 9              total_evaporation_sum   3.185135       1.481363e-03
 10          Land Surface Temperature   2.843609       4.530778e-03
 11                    temperature_2m   2.369782       1.794457e-02
 12             volumetric_soil_water   1.667729       9.561196e-02
 13                               cec  -0.069954       9.442409e-01
 14  flow_acc_phosphorous_interaction  -0.221468       8.247630e-01
 15                              clay  -0.255543       7.983448e-01
 16                               pet  -0.520161       6.030410e-01
 17                             green  -0.524998       5.996752e-01
 18                    cec_clay_ratio  -0.661238       5.085778e-01
 19                               EVI  -1.259359       2.081293e-01
 20        phosphorous_pH_interaction  -1.285840       1.987306e-01
 21                                pH  -1.719172       8.582434e-02
 22                              NDMI  -2.306109       2.126346e-02
 23                  soil_temperature  -2.948311       3.253116e-03
 24         flow_acc_clay_interaction  -2.952959       3.204908e-03
 25                       phosphorous  -3.023520       2.548206e-03
 26                     precipitation  -3.027873       2.512160e-03
 27                            swir22  -3.951081       8.205922e-05
 28                              NDVI  -4.003895       6.589717e-05
 29   evaporation_precipitation_ratio  -5.163014       2.816590e-07

     coefficient  selected
 0      2.105113         1
 1     12.410097         1
 2      3.287594         1
 3      1.337230         1
 4      8.705266         1
 5      7.558047         1
 6      6.222600         1
 7      4.707620         1
 8      3.958302         1
 9      0.967774         1
 10     1.751778         1
 11     3.327922         1
 12     1.249292         0
 13    -0.044293        -1
 14    -0.275254        -1
 15    -0.196338        -1
 16    -0.378052        -1
 17    -0.637052        -1
 18    -0.451176        -1
 19    -1.594252        -1
 20    -0.739441        -1
 21    -2.085732        -1
 22    -3.060451        -1
 23    -3.013066        -1
 24    -2.135984        -1
 25    -1.329574        -1
 26    -4.141558        -1
 27    -4.033764        -1
 28    -4.874800        -1
 29    -7.709064        -1  ,
 'Electrical Conductance':                         feature name    t-value  stat.significance  \
 0                   skin_temperature  22.324280       9.390466e-94
 1                               NDVI  16.207649       5.884577e-54
 2                          elevation  15.098915       1.365217e-47
 3                        phosphorous  14.101849       3.956347e-42
 4              total_evaporation_sum  11.391881       1.004218e-28
 5          flow_acc_clay_interaction   8.683161       1.135191e-17
 6                               clay   8.428970       9.149598e-17
 7                                 pH   6.224477       6.510734e-10
 8                      precipitation   4.194256       2.923808e-05
 9         phosphorous_pH_interaction   4.167529       3.283521e-05
 10                               pet   3.341967       8.556192e-04
 11                    cec_clay_ratio   3.222590       1.302056e-03
 12                cec_pH_interaction   2.561813       1.052539e-02
 13                 flow_accumulation   1.174997       2.402127e-01
 14                               EVI   1.119651       2.630709e-01
 15          Land Surface Temperature   0.973158       3.306573e-01
 16                            swir22   0.343792       7.310585e-01
 17   evaporation_precipitation_ratio   0.011246       9.910291e-01
 18                             MNDWI  -0.205990       8.368312e-01
 19                             green  -0.521705       6.019658e-01
 20                    temperature_2m  -0.528295       5.973860e-01
 21                               cec  -0.796158       4.260878e-01
 22             volumetric_soil_water  -0.874903       3.817908e-01
 23                            swir16  -1.096683       2.729861e-01
 24           total_precipitation_sum  -1.329641       1.838736e-01
 25                               nir  -1.925563       5.438044e-02
 26                              NDMI  -3.077413       2.132477e-03
 27  flow_acc_phosphorous_interaction  -3.364487       7.896135e-04
 28              NDVI_LST_interaction  -8.682481       1.163252e-17
 29                  soil_temperature -15.872846       6.509957e-52

     coefficient  selected
 0     23.739129         1
 1     12.965913         1
 2      2.182123         1
 3      3.090701         1
 4      2.608384         1
 5      5.578783         1
 6      2.165840         1
 7      1.773715         1
 8      4.514108         1
 9      1.534060         1
 10     0.591548         1
 11     0.942956         1
 12     0.935697         1
 13     0.668690         0
 14     0.713138         0
 15     0.528672         0
 16     0.324865         0
 17     0.016827         0
 18    -0.159340        -1
 19    -0.324356        -1
 20    -0.561767        -1
 21    -0.448386        -1
 22    -0.417463        -1
 23    -1.149400        -1
 24    -1.585771        -1
 25    -1.955195        -1
 26    -2.751912        -1
 27    -4.336293        -1
 28    -7.521979        -1
 29   -10.927576        -1  ,
 'Dissolved Reactive Phosphorus':                         feature name    t-value  stat.significance  \
 0         phosphorous_pH_interaction  18.425754       1.455809e-67
 1                 cec_pH_interaction  13.114938       5.327280e-37
 2                                pet   9.655123       2.380420e-21
 3                  flow_accumulation   8.689544       1.074786e-17
 4            total_precipitation_sum   7.329305       4.050940e-13
 5                          elevation   5.852280       6.132620e-09
 6                                EVI   5.726980       1.268731e-08
 7                                nir   4.350751       1.463135e-05
 8   flow_acc_phosphorous_interaction   3.644861       2.781196e-04
 9           Land Surface Temperature   3.122189       1.834864e-03
 10                    cec_clay_ratio   2.298321       2.170233e-02
 11                             MNDWI   1.920879       5.496662e-02
 12         flow_acc_clay_interaction   1.676789       9.382560e-02
 13                               cec   1.582156       1.138589e-01
 14                              NDMI   1.389801       1.648291e-01
 15                       phosphorous   0.972257       3.311049e-01
 16              NDVI_LST_interaction   0.890273       3.734855e-01
 17                     precipitation   0.276220       7.824235e-01
 18                            swir22  -0.242629       8.083317e-01
 19             volumetric_soil_water  -0.320111       7.489359e-01
 20                              clay  -0.430496       6.669072e-01
 21                  skin_temperature  -0.652517       5.141845e-01
 22                  soil_temperature  -0.709761       4.779816e-01
 23             total_evaporation_sum  -1.035832       3.004759e-01
 24                            swir16  -1.322952       1.860876e-01
 25                              NDVI  -1.480070       1.391008e-01
 26                                pH  -2.067152       3.892084e-02
 27   evaporation_precipitation_ratio  -2.490669       1.287656e-02
 28                    temperature_2m  -3.665231       2.572676e-04
 29                             green  -3.666297       2.562007e-04

     coefficient  selected
 0      2.077236         1
 1      4.645637         1
 2      1.867317         1
 3      1.737758         1
 4      3.916985         1
 5      1.194878         1
 6      3.677701         1
 7      2.756765         1
 8      2.340263         1
 9      1.725258         1
 10     0.748671         1
 11     1.082411         0
 12     1.342519         0
 13     1.481153         0
 14     0.755605         0
 15     0.357518         0
 16     0.662912         0
 17     0.185962         0
 18    -0.135042        -1
 19    -0.148157        -1
 20    -0.175997        -1
 21    -0.395447        -1
 22    -0.469486        -1
 23    -0.639003        -1
 24    -0.949444        -1
 25    -1.088617        -1
 26    -0.510686        -1
 27    -1.861645        -1
 28    -1.702803        -1
 29    -2.222721        -1  }

In [9]:
total_alk_feats = ["cec_pH_interaction", "skin_temperature", "flow_accumulation", "elevation", "nir",
                   "swir16", "total_precipitation_sum", "NDVI_LST_interaction", "MNDWI", "total_evaporation_sum",
                   "Land Surface Temperature", "temperature_2m"]

len(total_alk_feats)

12

In [10]:
elec_cond_feats = [
    "skin_temperature",
    "NDVI",
    "elevation",
    "phosphorous",
    "total_evaporation_sum",
    "flow_acc_clay_interaction",
    "clay",
    "pH",
    "precipitation",
    "phosphorous_pH_interaction",
    "pet",
    "cec_clay_ratio",
    "cec_pH_interaction"
]

len(elec_cond_feats)

13

In [11]:
drp_feats = [
    "phosphorous_pH_interaction",
    "cec_pH_interaction",
    "pet",
    "flow_accumulation",
    "total_precipitation_sum",
    "elevation",
    "EVI",
    "nir",
    "flow_acc_phosphorous_interaction",
    "Land Surface Temperature",
    "cec_clay_ratio"
]

len(drp_feats)

11

In [14]:
selected_feats = list(set(total_alk_feats + elec_cond_feats + drp_feats))

len(selected_feats)

23

## **Hyperparamter Optimization**

In [15]:
# Define new X_train and X_test based on feature selection results

X_train_fe = X_train[selected_feats]
X_test_fe = X_test[selected_feats]

X_train_fe.head()

,phosphorous_pH_interaction,cec_clay_ratio,cec_pH_interaction,NDVI_LST_interaction,nir,flow_accumulation,phosphorous,total_precipitation_sum,pet,pH,...,skin_temperature,MNDWI,elevation,total_evaporation_sum,EVI,flow_acc_clay_interaction,temperature_2m,Land Surface Temperature,flow_acc_phosphorous_interaction,swir16
2014,1533.0,0.925926,1825.0,79989423.5,12732.0,175.000000,21.0,0.000002,204.30000,73.0,...,292.891655,-0.092470,1012.728952,-0.000998,2907.0,4.725000e+03,291.355673,14948.5,3.675000e+03,11675.5
1334,1159.0,0.869565,1220.0,72791688.0,NaN,791.000000,19.0,0.000251,173.10000,61.0,...,294.242273,NaN,1363.117917,-0.002943,2946.0,1.819300e+04,292.974353,15514.0,1.502900e+04,NaN
5898,1728.0,0.933333,1792.0,71885411.5,11544.5,56124.822222,27.0,0.000093,133.30000,64.0,...,288.487464,0.143712,115.056783,-0.001870,2186.0,1.683745e+06,288.729935,14703.5,1.515370e+06,9155.0
2314,1188.0,0.900000,1782.0,48088364.5,13889.5,1372.590909,18.0,0.000001,168.40001,66.0,...,283.771401,-0.263596,1296.518526,-0.000075,1623.0,4.117773e+04,282.983824,14641.0,2.470664e+04,16857.0
5612,1430.0,0.851852,1495.0,87380172.0,13187.5,46804.487179,22.0,0.000538,174.00000,65.0,...,294.255641,-0.051068,952.729122,-0.002991,3244.0,1.263721e+06,293.876384,15102.0,1.029699e+06,11001.0

In [ ]:
# Next steps: perform hyperparameter optimization using Optuna. Then, using optimal
# hyperparameters retrain model for final testing.

def objective(trial):
    iterations = trial.suggest_int("iterations", 300, 1500)
    depth = trial.suggest_int("depth", 4, 10)
    learning_rate = trial.suggest_float("learning_rate", 0.01, 0.3)
    l2_leaf_reg =  trial.suggest_float("l2_leaf_reg", 1, 10)
    bagging_temperature =  trial.suggest_float("bagging_temperature", 0, 5)
    random_strength =  trial.suggest_float("random_strength", 0, 5)


    catboost = MultiOutputRegressor(CatBoostRegressor(iterations=iterations, learning_rate=learning_rate,
                                    depth=depth, l2_leaf_reg=l2_leaf_reg, 
                                    bagging_temperature=bagging_temperature,
                                    random_strength=random_strength, allow_writing_files=False, early_stopping_rounds=50))
    
    score = cross_val_score(catboost, X_train_fe, y_train, cv=5, scoring="r2", n_jobs=-1).mean()

    return score

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50)

In [27]:
study.best_trial

FrozenTrial(number=26, state=<TrialState.COMPLETE: 1>, values=[0.7839309668625903], datetime_start=datetime.datetime(2026, 3, 12, 16, 26, 1, 42046), datetime_complete=datetime.datetime(2026, 3, 12, 16, 26, 27, 576874), params={'iterations': 1322, 'depth': 7, 'learning_rate': 0.03653435268116288, 'l2_leaf_reg': 1.0357053375540382, 'bagging_temperature': 3.9705584233937956, 'random_strength': 0.24148881154228752}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'iterations': IntDistribution(high=1500, log=False, low=300, step=1), 'depth': IntDistribution(high=10, log=False, low=4, step=1), 'learning_rate': FloatDistribution(high=0.3, log=False, low=0.01, step=None), 'l2_leaf_reg': FloatDistribution(high=10.0, log=False, low=1.0, step=None), 'bagging_temperature': FloatDistribution(high=5.0, log=False, low=0.0, step=None), 'random_strength': FloatDistribution(high=5.0, log=False, low=0.0, step=None)}, trial_id=26, value=None)

In [33]:
study.best_params

{'iterations': 1322,
 'depth': 7,
 'learning_rate': 0.03653435268116288,
 'l2_leaf_reg': 1.0357053375540382,
 'bagging_temperature': 3.9705584233937956,
 'random_strength': 0.24148881154228752}

In [29]:
study.best_value

0.7839309668625903

Results for CatBoost are Above, Regression chaining doesnt work with Nan values so using multi_output_regression throughout here.

In [ ]:
## FINAL MODEL EVALUATION ON TEST SET TO SEE PERFORMANCE

cb = MultiOutputRegressor(CatBoostRegressor(iterations=1322, depth=7, learning_rate=0.037,
                        l2_leaf_reg=1.036, bagging_temperature=3.97, random_strength=0.241))

cb.fit(X_train_fe, y_train)
score = cb.score(X_test_fe, y_test)

score

0:	learn: 73.1112162	total: 55.4ms	remaining: 1m 13s
1:	learn: 71.5990099	total: 57.3ms	remaining: 37.8s
2:	learn: 70.1739701	total: 59ms	remaining: 25.9s
3:	learn: 68.7864992	total: 60.5ms	remaining: 19.9s
4:	learn: 67.4332789	total: 62.2ms	remaining: 16.4s
5:	learn: 66.1556674	total: 63.6ms	remaining: 14s
6:	learn: 64.9742106	total: 65.4ms	remaining: 12.3s
7:	learn: 63.8153822	total: 66.9ms	remaining: 11s
8:	learn: 62.7333356	total: 68.3ms	remaining: 9.97s
9:	learn: 61.6952620	total: 69.9ms	remaining: 9.17s
10:	learn: 60.6694272	total: 72.3ms	remaining: 8.61s
11:	learn: 59.6809725	total: 73.8ms	remaining: 8.05s
12:	learn: 58.7246726	total: 75.1ms	remaining: 7.57s
13:	learn: 57.8411109	total: 76.4ms	remaining: 7.14s
14:	learn: 57.0011256	total: 77.8ms	remaining: 6.78s
15:	learn: 56.1925357	total: 79.2ms	remaining: 6.46s
16:	learn: 55.3996431	total: 80.5ms	remaining: 6.18s
17:	learn: 54.6916757	total: 82.1ms	remaining: 5.94s
18:	learn: 53.9676527	total: 83.5ms	remaining: 5.72s
19:	learn: 53.2725963	total: 85ms	remaining: 5.53s
20:	learn: 52.6335759	total: 86.3ms	remaining: 5.35s
21:	learn: 52.0465981	total: 87.8ms	remaining: 5.18s
22:	learn: 51.4120812	total: 89.2ms	remaining: 5.04s
23:	learn: 50.8469158	total: 90.9ms	remaining: 4.91s
24:	learn: 50.3039504	total: 92.3ms	remaining: 4.79s
25:	learn: 49.7205686	total: 93.6ms	remaining: 4.66s
26:	learn: 49.2150908	total: 94.8ms	remaining: 4.55s
27:	learn: 48.7365556	total: 96.1ms	remaining: 4.44s
28:	learn: 48.2782776	total: 97.4ms	remaining: 4.34s
29:	learn: 47.8169394	total: 98.7ms	remaining: 4.25s
30:	learn: 47.4283865	total: 99.9ms	remaining: 4.16s
31:	learn: 47.0241661	total: 101ms	remaining: 4.08s
32:	learn: 46.5786513	total: 102ms	remaining: 4s
33:	learn: 46.1816150	total: 104ms	remaining: 3.93s
34:	learn: 45.7954681	total: 105ms	remaining: 3.87s
35:	learn: 45.4486104	total: 107ms	remaining: 3.83s
36:	learn: 45.0857521	total: 108ms	remaining: 3.77s
37:	learn: 44.7562835	total: 110ms	remaining: 3.71s
38:	learn: 44.3500322	total: 111ms	remaining: 3.65s
39:	learn: 44.0302084	total: 112ms	remaining: 3.6s
40:	learn: 43.7378401	total: 114ms	remaining: 3.56s
41:	learn: 43.4449782	total: 115ms	remaining: 3.52s
42:	learn: 43.1754185	total: 117ms	remaining: 3.47s
43:	learn: 42.8501345	total: 118ms	remaining: 3.42s
44:	learn: 42.5440645	total: 119ms	remaining: 3.38s
45:	learn: 42.3136071	total: 121ms	remaining: 3.34s
46:	learn: 42.0328384	total: 122ms	remaining: 3.31s
47:	learn: 41.7272434	total: 123ms	remaining: 3.28s
48:	learn: 41.4833459	total: 125ms	remaining: 3.24s
49:	learn: 41.2661503	total: 126ms	remaining: 3.2s
50:	learn: 41.0302848	total: 127ms	remaining: 3.17s
51:	learn: 40.8400204	total: 129ms	remaining: 3.14s
52:	learn: 40.6191539	total: 130ms	remaining: 3.11s
53:	learn: 40.3915498	total: 131ms	remaining: 3.08s
54:	learn: 40.1420673	total: 133ms	remaining: 3.05s
55:	learn: 39.9368653	total: 134ms	remaining: 3.03s
56:	learn: 39.7717251	total: 135ms	remaining: 3s
57:	learn: 39.5897291	total: 137ms	remaining: 2.98s
58:	learn: 39.4377691	total: 138ms	remaining: 2.95s
59:	learn: 39.2640165	total: 139ms	remaining: 2.92s
60:	learn: 39.1196673	total: 140ms	remaining: 2.9s
61:	learn: 38.9374810	total: 142ms	remaining: 2.88s
62:	learn: 38.8137767	total: 143ms	remaining: 2.86s
63:	learn: 38.6986298	total: 144ms	remaining: 2.84s
64:	learn: 38.5487725	total: 146ms	remaining: 2.82s
65:	learn: 38.3964067	total: 147ms	remaining: 2.8s
66:	learn: 38.2710591	total: 148ms	remaining: 2.78s
67:	learn: 38.1356968	total: 150ms	remaining: 2.76s
68:	learn: 37.9714356	total: 151ms	remaining: 2.74s
69:	learn: 37.8339072	total: 152ms	remaining: 2.72s
70:	learn: 37.6806904	total: 154ms	remaining: 2.71s
71:	learn: 37.5764092	total: 155ms	remaining: 2.69s
72:	learn: 37.4752541	total: 156ms	remaining: 2.67s
73:	learn: 37.3705147	total: 157ms	remaining: 2.65s
74:	learn: 37.2846072	total: 159ms	remaining: 2.64s
75:	learn: 37.1834504	total: 160ms	remaining: 2.62s
76:	learn: 37.0359810	total: 161ms	remaining: 2.6s
77:	learn: 36.9356809	total: 162ms	remaining: 2.59s
78:	learn: 36.8437031	total: 164ms	remaining: 2.57s
79:	learn: 36.7197112	total: 165ms	remaining: 2.56s
80:	learn: 36.6400560	total: 166ms	remaining: 2.55s
81:	learn: 36.5217855	total: 167ms	remaining: 2.53s
82:	learn: 36.4424249	total: 169ms	remaining: 2.52s
83:	learn: 36.3379659	total: 170ms	remaining: 2.51s
84:	learn: 36.2112702	total: 171ms	remaining: 2.49s
85:	learn: 36.1488629	total: 173ms	remaining: 2.48s
86:	learn: 36.0849644	total: 174ms	remaining: 2.47s
87:	learn: 36.0117711	total: 175ms	remaining: 2.46s
88:	learn: 35.9067431	total: 177ms	remaining: 2.44s
89:	learn: 35.8203170	total: 178ms	remaining: 2.43s
90:	learn: 35.6967581	total: 179ms	remaining: 2.42s
91:	learn: 35.6047804	total: 181ms	remaining: 2.41s
92:	learn: 35.5192982	total: 182ms	remaining: 2.4s
93:	learn: 35.4355451	total: 183ms	remaining: 2.39s
94:	learn: 35.3561076	total: 184ms	remaining: 2.38s
95:	learn: 35.2598050	total: 186ms	remaining: 2.37s
96:	learn: 35.1991772	total: 187ms	remaining: 2.36s
97:	learn: 35.1222266	total: 188ms	remaining: 2.35s
98:	learn: 35.0479944	total: 189ms	remaining: 2.34s
99:	learn: 34.9925861	total: 191ms	remaining: 2.33s
100:	learn: 34.9225610	total: 192ms	remaining: 2.32s
101:	learn: 34.8630470	total: 193ms	remaining: 2.31s
102:	learn: 34.7597567	total: 195ms	remaining: 2.3s
103:	learn: 34.6613994	total: 196ms	remaining: 2.29s
104:	learn: 34.5864590	total: 197ms	remaining: 2.28s
105:	learn: 34.5221185	total: 198ms	remaining: 2.27s
106:	learn: 34.4504529	total: 199ms	remaining: 2.26s
107:	learn: 34.3752077	total: 201ms	remaining: 2.26s
108:	learn: 34.2993331	total: 202ms	remaining: 2.25s
109:	learn: 34.2414371	total: 204ms	remaining: 2.24s
110:	learn: 34.1938278	total: 206ms	remaining: 2.25s
111:	learn: 34.1200084	total: 207ms	remaining: 2.24s
112:	learn: 34.0792413	total: 208ms	remaining: 2.23s
113:	learn: 34.0159725	total: 210ms	remaining: 2.22s
114:	learn: 33.9218737	total: 211ms	remaining: 2.22s
115:	learn: 33.8717679	total: 212ms	remaining: 2.21s
116:	learn: 33.8139045	total: 214ms	remaining: 2.2s
117:	learn: 33.7559883	total: 215ms	remaining: 2.19s
118:	learn: 33.6899416	total: 216ms	remaining: 2.19s
119:	learn: 33.6441819	total: 217ms	remaining: 2.18s
120:	learn: 33.5696820	total: 219ms	remaining: 2.17s
121:	learn: 33.5053384	total: 220ms	remaining: 2.17s
122:	learn: 33.4494396	total: 222ms	remaining: 2.16s
123:	learn: 33.4209655	total: 223ms	remaining: 2.15s
124:	learn: 33.3765813	total: 224ms	remaining: 2.15s
125:	learn: 33.3360672	total: 226ms	remaining: 2.14s
126:	learn: 33.2885845	total: 227ms	remaining: 2.14s
127:	learn: 33.2422808	total: 229ms	remaining: 2.13s
128:	learn: 33.2039198	total: 230ms	remaining: 2.13s
129:	learn: 33.1654761	total: 231ms	remaining: 2.12s
130:	learn: 33.1211170	total: 232ms	remaining: 2.11s
131:	learn: 33.0791466	total: 234ms	remaining: 2.11s
132:	learn: 33.0356818	total: 235ms	remaining: 2.1s
133:	learn: 32.9785891	total: 236ms	remaining: 2.1s
134:	learn: 32.9115570	total: 238ms	remaining: 2.09s
135:	learn: 32.8605814	total: 239ms	remaining: 2.08s
136:	learn: 32.8041847	total: 240ms	remaining: 2.08s
137:	learn: 32.7590300	total: 242ms	remaining: 2.08s
138:	learn: 32.6786514	total: 243ms	remaining: 2.07s
139:	learn: 32.6310942	total: 245ms	remaining: 2.07s
140:	learn: 32.5738420	total: 246ms	remaining: 2.06s
141:	learn: 32.5196900	total: 247ms	remaining: 2.05s
142:	learn: 32.4405331	total: 249ms	remaining: 2.05s
143:	learn: 32.3809797	total: 250ms	remaining: 2.04s
144:	learn: 32.3321108	total: 251ms	remaining: 2.04s
145:	learn: 32.2555148	total: 253ms	remaining: 2.04s
146:	learn: 32.2015371	total: 254ms	remaining: 2.03s
147:	learn: 32.1592314	total: 256ms	remaining: 2.03s
148:	learn: 32.1328722	total: 257ms	remaining: 2.02s
149:	learn: 32.0602198	total: 259ms	remaining: 2.02s
150:	learn: 32.0343411	total: 260ms	remaining: 2.02s
151:	learn: 31.9946806	total: 262ms	remaining: 2.01s
152:	learn: 31.9447190	total: 263ms	remaining: 2.01s
153:	learn: 31.9040282	total: 264ms	remaining: 2s
154:	learn: 31.8545349	total: 266ms	remaining: 2s
155:	learn: 31.8232260	total: 268ms	remaining: 2s
156:	learn: 31.7744662	total: 269ms	remaining: 2s
157:	learn: 31.7415198	total: 271ms	remaining: 1.99s
158:	learn: 31.7086920	total: 272ms	remaining: 1.99s
159:	learn: 31.6562032	total: 273ms	remaining: 1.99s
160:	learn: 31.6100433	total: 275ms	remaining: 1.98s
161:	learn: 31.5606025	total: 276ms	remaining: 1.98s
162:	learn: 31.5271590	total: 278ms	remaining: 1.98s
163:	learn: 31.4527715	total: 279ms	remaining: 1.97s
164:	learn: 31.4181973	total: 281ms	remaining: 1.97s
165:	learn: 31.3786313	total: 282ms	remaining: 1.96s
166:	learn: 31.3345806	total: 283ms	remaining: 1.96s
167:	learn: 31.3057118	total: 285ms	remaining: 1.96s
168:	learn: 31.2475426	total: 286ms	remaining: 1.95s
169:	learn: 31.2032027	total: 287ms	remaining: 1.95s
170:	learn: 31.1660094	total: 289ms	remaining: 1.94s
171:	learn: 31.1274461	total: 290ms	remaining: 1.94s
172:	learn: 31.0795454	total: 291ms	remaining: 1.94s
173:	learn: 31.0448203	total: 293ms	remaining: 1.93s
174:	learn: 31.0044106	total: 294ms	remaining: 1.93s
175:	learn: 30.9571141	total: 295ms	remaining: 1.92s
176:	learn: 30.9468756	total: 296ms	remaining: 1.92s
177:	learn: 30.9228777	total: 297ms	remaining: 1.91s
178:	learn: 30.8851797	total: 299ms	remaining: 1.91s
179:	learn: 30.8283591	total: 301ms	remaining: 1.91s
180:	learn: 30.8016088	total: 302ms	remaining: 1.91s
181:	learn: 30.7289666	total: 304ms	remaining: 1.9s
182:	learn: 30.7058095	total: 305ms	remaining: 1.9s
183:	learn: 30.6510937	total: 306ms	remaining: 1.89s
184:	learn: 30.6253611	total: 308ms	remaining: 1.89s
185:	learn: 30.5990023	total: 309ms	remaining: 1.89s
186:	learn: 30.5678408	total: 310ms	remaining: 1.88s
187:	learn: 30.5469511	total: 312ms	remaining: 1.88s
188:	learn: 30.5055978	total: 313ms	remaining: 1.88s
189:	learn: 30.4663473	total: 314ms	remaining: 1.87s
190:	learn: 30.4270070	total: 316ms	remaining: 1.87s
191:	learn: 30.3987376	total: 317ms	remaining: 1.87s
192:	learn: 30.3725285	total: 319ms	remaining: 1.86s
193:	learn: 30.3165391	total: 320ms	remaining: 1.86s
194:	learn: 30.2976371	total: 321ms	remaining: 1.85s
195:	learn: 30.2793642	total: 322ms	remaining: 1.85s
196:	learn: 30.2643785	total: 324ms	remaining: 1.85s
197:	learn: 30.2455772	total: 325ms	remaining: 1.85s
198:	learn: 30.1949122	total: 327ms	remaining: 1.84s
199:	learn: 30.1717828	total: 328ms	remaining: 1.84s
200:	learn: 30.1443988	total: 329ms	remaining: 1.83s
201:	learn: 30.1202198	total: 330ms	remaining: 1.83s
202:	learn: 30.0865314	total: 332ms	remaining: 1.83s
203:	learn: 30.0651566	total: 333ms	remaining: 1.82s
204:	learn: 30.0477820	total: 334ms	remaining: 1.82s
205:	learn: 30.0250976	total: 336ms	remaining: 1.82s
206:	learn: 29.9941117	total: 337ms	remaining: 1.81s
207:	learn: 29.9588912	total: 338ms	remaining: 1.81s
208:	learn: 29.9340192	total: 340ms	remaining: 1.81s
209:	learn: 29.9063847	total: 341ms	remaining: 1.81s
210:	learn: 29.8768084	total: 346ms	remaining: 1.82s
211:	learn: 29.8505386	total: 347ms	remaining: 1.82s
212:	learn: 29.8187282	total: 348ms	remaining: 1.81s
213:	learn: 29.7777163	total: 350ms	remaining: 1.81s
214:	learn: 29.7457353	total: 351ms	remaining: 1.81s
215:	learn: 29.7197060	total: 352ms	remaining: 1.8s
216:	learn: 29.6721710	total: 354ms	remaining: 1.8s
217:	learn: 29.6556180	total: 355ms	remaining: 1.8s
218:	learn: 29.6269131	total: 356ms	remaining: 1.79s
219:	learn: 29.5912748	total: 358ms	remaining: 1.79s
220:	learn: 29.5688402	total: 359ms	remaining: 1.79s
221:	learn: 29.5419955	total: 360ms	remaining: 1.78s
222:	learn: 29.5004055	total: 362ms	remaining: 1.78s
223:	learn: 29.4586363	total: 363ms	remaining: 1.78s
224:	learn: 29.4363059	total: 364ms	remaining: 1.77s
225:	learn: 29.3869793	total: 366ms	remaining: 1.77s
226:	learn: 29.3659758	total: 367ms	remaining: 1.77s
227:	learn: 29.3248232	total: 368ms	remaining: 1.77s
228:	learn: 29.2791518	total: 369ms	remaining: 1.76s
229:	learn: 29.2287834	total: 371ms	remaining: 1.76s
230:	learn: 29.2098796	total: 373ms	remaining: 1.76s
231:	learn: 29.1929574	total: 374ms	remaining: 1.76s
232:	learn: 29.1517065	total: 375ms	remaining: 1.75s
233:	learn: 29.1390314	total: 377ms	remaining: 1.75s
234:	learn: 29.1065378	total: 378ms	remaining: 1.75s
235:	learn: 29.0698671	total: 380ms	remaining: 1.75s
236:	learn: 29.0444092	total: 381ms	remaining: 1.75s
237:	learn: 29.0258067	total: 383ms	remaining: 1.74s
238:	learn: 28.9915547	total: 384ms	remaining: 1.74s
239:	learn: 28.9729126	total: 385ms	remaining: 1.74s
240:	learn: 28.9478728	total: 387ms	remaining: 1.74s
241:	learn: 28.9311129	total: 388ms	remaining: 1.73s
242:	learn: 28.9141984	total: 390ms	remaining: 1.73s
243:	learn: 28.8788710	total: 391ms	remaining: 1.73s
244:	learn: 28.8529814	total: 393ms	remaining: 1.73s
245:	learn: 28.8286349	total: 394ms	remaining: 1.72s
246:	learn: 28.8082244	total: 396ms	remaining: 1.72s
247:	learn: 28.7906039	total: 397ms	remaining: 1.72s
248:	learn: 28.7477029	total: 399ms	remaining: 1.72s
249:	learn: 28.7238516	total: 400ms	remaining: 1.72s
250:	learn: 28.7016546	total: 401ms	remaining: 1.71s
251:	learn: 28.6791933	total: 403ms	remaining: 1.71s
252:	learn: 28.6460715	total: 404ms	remaining: 1.71s
253:	learn: 28.6187616	total: 405ms	remaining: 1.7s
254:	learn: 28.6044848	total: 407ms	remaining: 1.7s
255:	learn: 28.5653420	total: 408ms	remaining: 1.7s
256:	learn: 28.5463657	total: 409ms	remaining: 1.7s
257:	learn: 28.5299246	total: 411ms	remaining: 1.69s
258:	learn: 28.5116423	total: 412ms	remaining: 1.69s
259:	learn: 28.4803085	total: 414ms	remaining: 1.69s
260:	learn: 28.4358825	total: 415ms	remaining: 1.69s
261:	learn: 28.4184729	total: 416ms	remaining: 1.68s
262:	learn: 28.4029995	total: 417ms	remaining: 1.68s
263:	learn: 28.3829692	total: 419ms	remaining: 1.68s
264:	learn: 28.3686814	total: 420ms	remaining: 1.68s
265:	learn: 28.3351139	total: 422ms	remaining: 1.67s
266:	learn: 28.3176989	total: 423ms	remaining: 1.67s
267:	learn: 28.2886244	total: 424ms	remaining: 1.67s
268:	learn: 28.2619161	total: 426ms	remaining: 1.67s
269:	learn: 28.2343372	total: 427ms	remaining: 1.66s
270:	learn: 28.2073949	total: 428ms	remaining: 1.66s
271:	learn: 28.1695381	total: 430ms	remaining: 1.66s
272:	learn: 28.1315665	total: 431ms	remaining: 1.66s
273:	learn: 28.0958946	total: 433ms	remaining: 1.65s
274:	learn: 28.0681850	total: 434ms	remaining: 1.65s
275:	learn: 28.0479429	total: 435ms	remaining: 1.65s
276:	learn: 28.0144618	total: 437ms	remaining: 1.65s
277:	learn: 27.9900606	total: 438ms	remaining: 1.65s
278:	learn: 27.9719190	total: 439ms	remaining: 1.64s
279:	learn: 27.9306664	total: 441ms	remaining: 1.64s
280:	learn: 27.9055301	total: 442ms	remaining: 1.64s
281:	learn: 27.8774825	total: 443ms	remaining: 1.64s
282:	learn: 27.8511242	total: 445ms	remaining: 1.63s
283:	learn: 27.8337483	total: 446ms	remaining: 1.63s
284:	learn: 27.8014024	total: 448ms	remaining: 1.63s
285:	learn: 27.7701563	total: 449ms	remaining: 1.63s
286:	learn: 27.7261496	total: 451ms	remaining: 1.63s
287:	learn: 27.7020040	total: 452ms	remaining: 1.62s
288:	learn: 27.6906446	total: 453ms	remaining: 1.62s
289:	learn: 27.6649666	total: 455ms	remaining: 1.62s
290:	learn: 27.6444132	total: 456ms	remaining: 1.61s
291:	learn: 27.6098745	total: 457ms	remaining: 1.61s
292:	learn: 27.5732596	total: 459ms	remaining: 1.61s
293:	learn: 27.5489143	total: 460ms	remaining: 1.61s
294:	learn: 27.5310988	total: 462ms	remaining: 1.61s
295:	learn: 27.4947152	total: 463ms	remaining: 1.61s
296:	learn: 27.4818173	total: 465ms	remaining: 1.6s
297:	learn: 27.4654035	total: 466ms	remaining: 1.6s
298:	learn: 27.4438098	total: 468ms	remaining: 1.6s
299:	learn: 27.4270307	total: 469ms	remaining: 1.6s
300:	learn: 27.4026926	total: 470ms	remaining: 1.59s
301:	learn: 27.3859199	total: 472ms	remaining: 1.59s
302:	learn: 27.3603048	total: 473ms	remaining: 1.59s
303:	learn: 27.3463191	total: 474ms	remaining: 1.59s
304:	learn: 27.3195629	total: 475ms	remaining: 1.58s
305:	learn: 27.2984205	total: 477ms	remaining: 1.58s
306:	learn: 27.2753848	total: 478ms	remaining: 1.58s
307:	learn: 27.2463388	total: 480ms	remaining: 1.58s
308:	learn: 27.2162085	total: 481ms	remaining: 1.58s
309:	learn: 27.2039897	total: 482ms	remaining: 1.57s
310:	learn: 27.1845893	total: 483ms	remaining: 1.57s
311:	learn: 27.1695480	total: 485ms	remaining: 1.57s
312:	learn: 27.1441063	total: 486ms	remaining: 1.57s
313:	learn: 27.1308960	total: 487ms	remaining: 1.56s
314:	learn: 27.1054637	total: 489ms	remaining: 1.56s
315:	learn: 27.0607854	total: 490ms	remaining: 1.56s
316:	learn: 27.0215806	total: 491ms	remaining: 1.56s
317:	learn: 26.9847240	total: 493ms	remaining: 1.56s
318:	learn: 26.9631516	total: 495ms	remaining: 1.55s
319:	learn: 26.9437595	total: 496ms	remaining: 1.55s
320:	learn: 26.9201571	total: 497ms	remaining: 1.55s
321:	learn: 26.9019318	total: 499ms	remaining: 1.55s
322:	learn: 26.8848277	total: 500ms	remaining: 1.55s
323:	learn: 26.8705016	total: 501ms	remaining: 1.54s
324:	learn: 26.8439729	total: 503ms	remaining: 1.54s
325:	learn: 26.8123126	total: 504ms	remaining: 1.54s
326:	learn: 26.7977022	total: 506ms	remaining: 1.54s
327:	learn: 26.7841785	total: 507ms	remaining: 1.53s
328:	learn: 26.7557410	total: 508ms	remaining: 1.53s
329:	learn: 26.7296111	total: 510ms	remaining: 1.53s
330:	learn: 26.7124348	total: 511ms	remaining: 1.53s
331:	learn: 26.6980097	total: 512ms	remaining: 1.53s
332:	learn: 26.6740673	total: 513ms	remaining: 1.52s
333:	learn: 26.6601234	total: 515ms	remaining: 1.52s
334:	learn: 26.6316099	total: 516ms	remaining: 1.52s
335:	learn: 26.6201536	total: 517ms	remaining: 1.52s
336:	learn: 26.5884922	total: 519ms	remaining: 1.51s
337:	learn: 26.5664619	total: 520ms	remaining: 1.51s
338:	learn: 26.5374423	total: 521ms	remaining: 1.51s
339:	learn: 26.5110441	total: 522ms	remaining: 1.51s
340:	learn: 26.4932411	total: 524ms	remaining: 1.51s
341:	learn: 26.4601617	total: 525ms	remaining: 1.5s
342:	learn: 26.4366605	total: 526ms	remaining: 1.5s
343:	learn: 26.4172612	total: 528ms	remaining: 1.5s
344:	learn: 26.3999464	total: 529ms	remaining: 1.5s
345:	learn: 26.3738334	total: 530ms	remaining: 1.5s
346:	learn: 26.3637190	total: 531ms	remaining: 1.49s
347:	learn: 26.3395672	total: 533ms	remaining: 1.49s
348:	learn: 26.3217563	total: 534ms	remaining: 1.49s
349:	learn: 26.3091601	total: 535ms	remaining: 1.49s
350:	learn: 26.2898805	total: 537ms	remaining: 1.48s
351:	learn: 26.2674118	total: 538ms	remaining: 1.48s
352:	learn: 26.2535925	total: 539ms	remaining: 1.48s
353:	learn: 26.2371818	total: 540ms	remaining: 1.48s
354:	learn: 26.2149381	total: 542ms	remaining: 1.48s
355:	learn: 26.1936351	total: 543ms	remaining: 1.47s
356:	learn: 26.1704991	total: 544ms	remaining: 1.47s
357:	learn: 26.1557758	total: 546ms	remaining: 1.47s
358:	learn: 26.1447961	total: 547ms	remaining: 1.47s
359:	learn: 26.1252362	total: 548ms	remaining: 1.47s
360:	learn: 26.0934702	total: 550ms	remaining: 1.46s
361:	learn: 26.0714246	total: 551ms	remaining: 1.46s
362:	learn: 26.0515804	total: 553ms	remaining: 1.46s
363:	learn: 26.0344536	total: 554ms	remaining: 1.46s
364:	learn: 26.0216574	total: 555ms	remaining: 1.46s
365:	learn: 25.9995742	total: 556ms	remaining: 1.45s
366:	learn: 25.9793752	total: 558ms	remaining: 1.45s
367:	learn: 25.9576206	total: 559ms	remaining: 1.45s
368:	learn: 25.9359217	total: 560ms	remaining: 1.45s
369:	learn: 25.9177326	total: 562ms	remaining: 1.44s
370:	learn: 25.8979122	total: 563ms	remaining: 1.44s
371:	learn: 25.8881741	total: 564ms	remaining: 1.44s
372:	learn: 25.8697673	total: 565ms	remaining: 1.44s
373:	learn: 25.8345868	total: 567ms	remaining: 1.44s
374:	learn: 25.8194380	total: 568ms	remaining: 1.43s
375:	learn: 25.7981006	total: 569ms	remaining: 1.43s
376:	learn: 25.7688953	total: 570ms	remaining: 1.43s
377:	learn: 25.7582677	total: 572ms	remaining: 1.43s
378:	learn: 25.7411732	total: 573ms	remaining: 1.43s

0.7820469130417637

In [37]:
## Predict Output for Submission Set

submission_df = pd.read_csv('../data/validation_set.csv')
submission_df.head()

,Unnamed: 0,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,elevation,EVI,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
0,0,-32.043333,27.822778,01-09-2014,NaN,NaN,NaN,161.90001,780.299056,1628.0,...,0.000007,0.136892,0.000000,1742.0,1742.0,4.542096e+07,351115.714286,338111.428571,-95.760822,0.962963
1,1,-33.329167,26.077500,16-09-2015,NaN,NaN,NaN,177.60000,279.351413,2933.0,...,0.000550,0.259777,27.521283,1495.0,1690.0,1.069767e+08,202225.000000,210314.000000,-3.653135,0.920000
2,2,-32.991639,27.640028,07-05-2015,NaN,NaN,NaN,158.40001,163.622679,4032.0,...,0.000174,0.232120,14.464016,1403.0,1525.0,1.034820e+08,121744.000000,126816.666667,-10.921542,0.958333
3,3,-34.096389,24.439167,07-02-2012,NaN,NaN,NaN,130.00000,44.046365,4701.0,...,NaN,NaN,42.085633,1121.0,1416.0,1.123978e+08,18889.531915,18889.531915,NaN,0.791667
4,4,-32.000556,28.581667,01-10-2014,NaN,NaN,NaN,152.50000,333.249422,1498.0,...,0.000618,0.336999,30.467072,1674.0,1674.0,6.468512e+07,410099.609756,381816.878049,-4.473473,0.931034

In [38]:
check_df = submission_df.drop(columns=['Unnamed: 0', 'Latitude', 
'Longitude', 'Sample Date', 
"Total Alkalinity", "Electrical Conductance",
'Dissolved Reactive Phosphorus'])

check_df.head()

,pet,elevation,EVI,NDVI,Land Surface Temperature,nir,green,swir16,swir22,NDMI,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
0,161.90001,780.299056,1628.0,3016.0,15060.0,15229.0,12868.0,14797.0,12421.0,0.014388,...,0.000007,0.136892,0.000000,1742.0,1742.0,4.542096e+07,351115.714286,338111.428571,-95.760822,0.962963
1,177.60000,279.351413,2933.0,7263.0,14729.0,NaN,NaN,NaN,NaN,NaN,...,0.000550,0.259777,27.521283,1495.0,1690.0,1.069767e+08,202225.000000,210314.000000,-3.653135,0.920000
2,158.40001,163.622679,4032.0,7036.0,14707.5,16221.0,9304.5,12536.5,9958.0,0.128123,...,0.000174,0.232120,14.464016,1403.0,1525.0,1.034820e+08,121744.000000,126816.666667,-10.921542,0.958333
3,130.00000,44.046365,4701.0,7474.5,15037.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,42.085633,1121.0,1416.0,1.123978e+08,18889.531915,18889.531915,NaN,0.791667
4,152.50000,333.249422,1498.0,4257.0,15195.0,9125.0,11100.5,9455.0,8711.0,-0.017761,...,0.000618,0.336999,30.467072,1674.0,1674.0,6.468512e+07,410099.609756,381816.878049,-4.473473,0.931034

In [40]:
test_df = check_df[selected_feats]

test_df.head()

,phosphorous_pH_interaction,cec_clay_ratio,cec_pH_interaction,NDVI_LST_interaction,nir,flow_accumulation,phosphorous,total_precipitation_sum,pet,pH,...,skin_temperature,MNDWI,elevation,total_evaporation_sum,EVI,flow_acc_clay_interaction,temperature_2m,Land Surface Temperature,flow_acc_phosphorous_interaction,swir16
0,1742.0,0.962963,1742.0,4.542096e+07,15229.0,13004.285714,26.0,0.000007,161.90001,67.0,...,288.386807,-0.069727,780.299056,-0.000788,1628.0,351115.714286,287.626439,15060.0,338111.428571,14797.0
1,1690.0,0.920000,1495.0,1.069767e+08,NaN,8089.000000,26.0,0.000550,177.60000,65.0,...,288.667907,NaN,279.351413,-0.002014,2933.0,202225.000000,287.174347,14729.0,210314.000000,NaN
2,1525.0,0.958333,1403.0,1.034820e+08,16221.0,5072.666667,25.0,0.000174,158.40001,61.0,...,291.107708,-0.147979,163.622679,-0.001915,4032.0,121744.000000,291.330903,14707.5,126816.666667,12536.5
3,1416.0,0.791667,1121.0,1.123978e+08,NaN,787.063830,24.0,NaN,130.00000,59.0,...,NaN,NaN,44.046365,NaN,4701.0,18889.531915,NaN,15037.5,18889.531915,NaN
4,1674.0,0.931034,1674.0,6.468512e+07,9125.0,14141.365854,27.0,0.000618,152.50000,62.0,...,288.706654,0.080052,333.249422,-0.002771,1498.0,410099.609756,288.034482,15195.0,381816.878049,9455.0

In [41]:
vals = cb.predict(test_df)
val_df = pd.DataFrame(vals)
val_df.columns = ['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']

val_df

     Total Alkalinity  Electrical Conductance  Dissolved Reactive Phosphorus
0          124.621303              337.688026                      21.330442
1           86.445012              425.564354                      45.632628
2           61.420649              202.549960                      21.500480
3           71.374396              322.545137                       9.694899
4           88.838084              258.189106                      18.876887
..                ...                     ...                            ...
195         59.829777              433.446571                      27.188335
196         85.026952              367.828543                      19.510188
197         93.389578              353.277355                      31.694825
198         59.293472              367.635304                      32.677361
199        142.450626              665.789272                      22.903129

[200 rows x 3 columns]

In [42]:
submission = pd.DataFrame({
    'Longitude': submission_df['Longitude'],
    'Latitude': submission_df['Latitude'],
    'Sample Date': submission_df['Sample Date'],
    'Total Alkalinity': val_df['Total Alkalinity'],
    'Electrical Conductance': val_df['Electrical Conductance'],
    'Dissolved Reactive Phosphorus': val_df['Dissolved Reactive Phosphorus']
})

submission

,Longitude,Latitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus
0,27.822778,-32.043333,01-09-2014,124.621303,337.688026,21.330442
1,26.077500,-33.329167,16-09-2015,86.445012,425.564354,45.632628
2,27.640028,-32.991639,07-05-2015,61.420649,202.549960,21.500480
3,24.439167,-34.096389,07-02-2012,71.374396,322.545137,9.694899
4,28.581667,-32.000556,01-10-2014,88.838084,258.189106,18.876887
...,...,...,...,...,...,...
195,25.386667,-33.771111,06-12-2012,59.829777,433.446571,27.188335
196,27.390750,-33.185361,04-09-2014,85.026952,367.828543,19.510188
197,27.822778,-32.043333,28-09-2015,93.389578,353.277355,31.694825
198,25.161389,-33.001667,08-01-2015,59.293472,367.635304,32.677361
199,26.994720,-33.237780,27-03-2013,142.450626,665.789272,22.903129

In [44]:
submission.to_csv('../submission.csv', index=False)