# Evaluate Performance Using Ridge

In [14]:
# Import statements (add as needed)

import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score, cross_validate, train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, FunctionTransformer, PowerTransformer
from sklearn.impute import SimpleImputer

from sklearn.compose import (
    TransformedTargetRegressor,
    make_column_transformer,
)

from sklearn.pipeline import make_pipeline
from skopt import BayesSearchCV
from missforest import MissForest

from sklearn.multioutput import MultiOutputRegressor
from sklearn.multioutput import RegressorChain
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from shap_select import shap_select
import xgboost as xgb
from xgboost import XGBRegressor
import optuna
from catboost import CatBoostRegressor
from sklearn.linear_model import Ridge

In [2]:
# load both feature engineered dataset.

fe_df = pd.read_csv('../data/feature_engineered_training_set.csv')

In [3]:
fe_df = fe_df.drop(columns=['Unnamed: 0'])
fe_df.head()

,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,elevation,EVI,NDVI,Land Surface Temperature,nir,green,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
0,128.912,555.0,10.0,174.2,167.155040,241.0,636.0,15845.0,11190.0,11426.0,...,0.000001,0.008799,0.488024,1800.0,1725.0,10077420.0,8.676030e+07,9.502319e+07,-37.216627,1.142857
1,74.720,162.9,163.0,124.1,1521.251493,4643.0,7656.0,15190.0,17658.5,9550.0,...,0.007830,0.458929,97.342756,1755.0,1365.0,116294640.0,3.369889e+05,2.440265e+05,-0.523901,0.931034
2,89.254,573.0,80.0,127.5,1471.379902,3984.0,6276.0,14879.0,15210.0,10720.0,...,0.006964,0.393498,96.911494,1472.0,1344.0,93380604.0,2.800000e+01,2.100000e+01,-0.575803,0.821429
3,82.000,203.6,101.0,129.7,1342.659998,2217.0,3957.0,15228.5,14887.0,10943.0,...,0.007228,0.409018,102.307634,1495.0,1430.0,60259174.5,4.884100e+05,4.132700e+05,-0.538889,0.884615
4,56.100,145.1,151.0,129.2,1355.983661,4136.0,7396.0,15130.0,16828.5,9502.5,...,0.004980,0.437815,96.513882,1600.0,1280.0,111901480.0,1.337840e+05,9.556000e+04,-0.784851,0.892857

In [4]:
train_df, test_df = train_test_split(fe_df, test_size=0.3)      # create train set and test set to eval performance

In [5]:
# Split train_df and test_df into X_train, X_test, y_train and y_test

X_train = train_df.drop(columns=['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus'])
y_train = train_df[['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']]

X_test = test_df.drop(columns=['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus'])
y_test = test_df[['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']]

## **Data Preprocessing**

In [6]:
preprocessor = make_pipeline(SimpleImputer(strategy='median'), StandardScaler())

## **Feature Selection**

In [10]:
# Conduct feature selection using shap_select.

def perform_feature_selection(X_train, y_train):
    results_dict = {}

    X_tr, X_te, y_tr, y_te = train_test_split(X_train, y_train, test_size=0.2)
    X_tr_fe = preprocessor.fit_transform(X_tr)
    X_te_fe = preprocessor.transform(X_te)
    X_te_df = pd.DataFrame(X_te_fe, columns=X_train.columns, index=y_te.index)
    
    
    for target in y_train.columns:
        model = XGBRegressor(n_estimators=1000, verbosity = 0, eval_metric='rmse', objective='reg:squarederror')
        model.fit(X_tr_fe, y_tr[target], eval_set=[(X_te_fe, y_te[target])])

        selected_df = shap_select(model, X_te_df, y_te[target], task="regression", threshold=0.05)
        results_dict[target] = selected_df

    return results_dict

In [11]:
results = perform_feature_selection(X_train, y_train)

[0]	validation_0-rmse:61.14167
[1]	validation_0-rmse:52.73011
[2]	validation_0-rmse:47.30802
[3]	validation_0-rmse:42.90090
[4]	validation_0-rmse:40.19608
[5]	validation_0-rmse:38.74684
[6]	validation_0-rmse:37.21890
[7]	validation_0-rmse:36.75916
[8]	validation_0-rmse:36.00083
[9]	validation_0-rmse:35.53983
[10]	validation_0-rmse:35.12292
[11]	validation_0-rmse:34.86331
[12]	validation_0-rmse:34.67659
[13]	validation_0-rmse:34.62496
[14]	validation_0-rmse:33.96615
[15]	validation_0-rmse:33.91632
[16]	validation_0-rmse:33.72175
[17]	validation_0-rmse:33.64442
[18]	validation_0-rmse:33.52384
[19]	validation_0-rmse:33.33246
[20]	validation_0-rmse:33.26280
[21]	validation_0-rmse:33.32197
[22]	validation_0-rmse:33.23083
[23]	validation_0-rmse:33.19608
[24]	validation_0-rmse:33.26166
[25]	validation_0-rmse:33.17399
[26]	validation_0-rmse:33.11543
[27]	validation_0-rmse:33.11131
[28]	validation_0-rmse:32.98413
[29]	validation_0-rmse:32.93300
[30]	validation_0-rmse:32.97844
[31]	validation_0-rmse:32.99957
[32]	validation_0-rmse:33.04082
[33]	validation_0-rmse:33.06420
[34]	validation_0-rmse:33.06474
[35]	validation_0-rmse:33.03863
[36]	validation_0-rmse:33.03999
[37]	validation_0-rmse:33.00258
[38]	validation_0-rmse:33.02854
[39]	validation_0-rmse:33.00463
[40]	validation_0-rmse:32.99744
[41]	validation_0-rmse:32.91620
[42]	validation_0-rmse:32.91992
[43]	validation_0-rmse:32.91362
[44]	validation_0-rmse:32.89616
[45]	validation_0-rmse:32.94058
[46]	validation_0-rmse:32.97793
[47]	validation_0-rmse:32.97830
[48]	validation_0-rmse:33.05145
[49]	validation_0-rmse:33.02459
[50]	validation_0-rmse:32.99707
[51]	validation_0-rmse:33.02842
[52]	validation_0-rmse:32.93963
[53]	validation_0-rmse:32.94614
[54]	validation_0-rmse:33.01493
[55]	validation_0-rmse:33.04250
[56]	validation_0-rmse:33.01348
[57]	validation_0-rmse:32.94362
[58]	validation_0-rmse:32.89419
[59]	validation_0-rmse:32.87659
[60]	validation_0-rmse:32.87827
[61]	validation_0-rmse:32.87800
[62]	validation_0-rmse:32.89473
[63]	validation_0-rmse:32.89077
[64]	validation_0-rmse:32.90375
[65]	validation_0-rmse:32.93277
[66]	validation_0-rmse:32.92873
[67]	validation_0-rmse:32.96995
[68]	validation_0-rmse:32.93143
[69]	validation_0-rmse:32.94939
[70]	validation_0-rmse:32.98373
[71]	validation_0-rmse:32.93446
[72]	validation_0-rmse:32.95624
[73]	validation_0-rmse:33.04922
[74]	validation_0-rmse:33.05445
[75]	validation_0-rmse:33.03559
[76]	validation_0-rmse:33.01618
[77]	validation_0-rmse:33.01309
[78]	validation_0-rmse:33.00396
[79]	validation_0-rmse:33.00907
[80]	validation_0-rmse:33.00122
[81]	validation_0-rmse:32.98416
[82]	validation_0-rmse:32.97723
[83]	validation_0-rmse:32.97513
[84]	validation_0-rmse:32.97007
[85]	validation_0-rmse:32.96129
[86]	validation_0-rmse:32.99607
[87]	validation_0-rmse:33.01056
[88]	validation_0-rmse:33.00859
[89]	validation_0-rmse:33.02069
[90]	validation_0-rmse:33.09320
[91]	validation_0-rmse:33.09044
[92]	validation_0-rmse:33.13502
[93]	validation_0-rmse:33.09993
[94]	validation_0-rmse:33.09310
[95]	validation_0-rmse:33.06664
[96]	validation_0-rmse:33.05791
[97]	validation_0-rmse:33.05728
[98]	validation_0-rmse:33.05251
[99]	validation_0-rmse:33.04757
[100]	validation_0-rmse:33.06916
[101]	validation_0-rmse:33.07739
[102]	validation_0-rmse:33.08185
[103]	validation_0-rmse:33.05790
[104]	validation_0-rmse:33.04829
[105]	validation_0-rmse:33.04444
[106]	validation_0-rmse:33.03510
[107]	validation_0-rmse:33.03548
[108]	validation_0-rmse:33.05429
[109]	validation_0-rmse:33.05240
[110]	validation_0-rmse:33.05455
[111]	validation_0-rmse:33.04968
[112]	validation_0-rmse:33.03765
[113]	validation_0-rmse:33.01801
[114]	validation_0-rmse:33.01349
[115]	validation_0-rmse:33.04429
[116]	validation_0-rmse:33.05200
[117]	validation_0-rmse:33.05196
[118]	validation_0-rmse:33.05717
[119]	validation_0-rmse:33.06055
[120]	validation_0-rmse:33.06633
[121]	validation_0-rmse:33.07073
[122]	validation_0-rmse:33.08413
[123]	validation_0-rmse:33.10472
[124]	validation_0-rmse:33.11613
[125]	validation_0-rmse:33.12070
[126]	validation_0-rmse:33.11297
[127]	validation_0-rmse:33.12960
[128]	validation_0-rmse:33.09542
[129]	validation_0-rmse:33.10528
[130]	validation_0-rmse:33.09633
[131]	validation_0-rmse:33.09054
[132]	validation_0-rmse:33.09910
[133]	validation_0-rmse:33.09686
[134]	validation_0-rmse:33.08803
[135]	validation_0-rmse:33.10073
[136]	validation_0-rmse:33.09899
[137]	validation_0-rmse:33.12060
[138]	validation_0-rmse:33.11200
[139]	validation_0-rmse:33.12589
[140]	validation_0-rmse:33.11999
[141]	validation_0-rmse:33.12251
[142]	validation_0-rmse:33.12613
[143]	validation_0-rmse:33.11765
[144]	validation_0-rmse:33.11660
[145]	validation_0-rmse:33.11190
[146]	validation_0-rmse:33.12086
[147]	validation_0-rmse:33.13130
[148]	validation_0-rmse:33.13691
[149]	validation_0-rmse:33.12951
[150]	validation_0-rmse:33.12395
[151]	validation_0-rmse:33.12724
[152]	validation_0-rmse:33.13037
[153]	validation_0-rmse:33.13308
[154]	validation_0-rmse:33.12731
[155]	validation_0-rmse:33.13884
[156]	validation_0-rmse:33.12987
[157]	validation_0-rmse:33.13154
[158]	validation_0-rmse:33.13078
[159]	validation_0-rmse:33.13145
[160]	validation_0-rmse:33.12658
[161]	validation_0-rmse:33.12548
[162]	validation_0-rmse:33.12122
[163]	validation_0-rmse:33.11364
[164]	validation_0-rmse:33.11985
[165]	validation_0-rmse:33.11977
[166]	validation_0-rmse:33.11591
[167]	validation_0-rmse:33.11873
[168]	validation_0-rmse:33.11787
[169]	validation_0-rmse:33.11900
[170]	validation_0-rmse:33.11576
[171]	validation_0-rmse:33.12049
[172]	validation_0-rmse:33.12560
[173]	validation_0-rmse:33.13839
[174]	validation_0-rmse:33.13236
[175]	validation_0-rmse:33.12697
[176]	validation_0-rmse:33.12284
[177]	validation_0-rmse:33.12848
[178]	validation_0-rmse:33.13895
[179]	validation_0-rmse:33.14173
[180]	validation_0-rmse:33.13367
[181]	validation_0-rmse:33.14103
[182]	validation_0-rmse:33.14758
[183]	validation_0-rmse:33.16382
[184]	validation_0-rmse:33.17448
[185]	validation_0-rmse:33.17676
[186]	validation_0-rmse:33.16905
[187]	validation_0-rmse:33.17801
[188]	validation_0-rmse:33.18211
[189]	validation_0-rmse:33.18355
[190]	validation_0-rmse:33.18704
[191]	validation_0-rmse:33.19153
[192]	validation_0-rmse:33.19377
[193]	validation_0-rmse:33.19564
[194]	validation_0-rmse:33.20925
[195]	validation_0-rmse:33.21185
[196]	validation_0-rmse:33.22012
[197]	validation_0-rmse:33.22856
[198]	validation_0-rmse:33.23624
[199]	validation_0-rmse:33.22525
[200]	validation_0-rmse:33.22617
[201]	validation_0-rmse:33.21825
[202]	validation_0-rmse:33.22129
[203]	validation_0-rmse:33.21640
[204]	validation_0-rmse:33.21324
[205]	validation_0-rmse:33.21547
[206]	validation_0-rmse:33.21102
[207]	validation_0-rmse:33.21146
[208]	validation_0-rmse:33.20868
[209]	validation_0-rmse:33.20185
[210]	validation_0-rmse:33.20311
[211]	validation_0-rmse:33.20451
[212]	validation_0-rmse:33.20457
[213]	validation_0-rmse:33.20162
[214]	validation_0-rmse:33.20220
[215]	validation_0-rmse:33.20135
[216]	validation_0-rmse:33.20402
[217]	validation_0-rmse:33.20905
[218]	validation_0-rmse:33.19937
[219]	validation_0-rmse:33.20338
[220]	validation_0-rmse:33.19906
[221]	validation_0-rmse:33.20460
[222]	validation_0-rmse:33.20245
[223]	validation_0-rmse:33.20298
[224]	validation_0-rmse:33.20110
[225]	validation_0-rmse:33.20261
[226]	validation_0-rmse:33.20413
[227]	validation_0-rmse:33.20616
[228]	validation_0-rmse:33.21046
[229]	validation_0-rmse:33.20677
[230]	validation_0-rmse:33.21150
[231]	validation_0-rmse:33.21335
[232]	validation_0-rmse:33.22015
[233]	validation_0-rmse:33.21920
[234]	validation_0-rmse:33.22157
[235]	validation_0-rmse:33.21879
[236]	validation_0-rmse:33.22133
[237]	validation_0-rmse:33.22207
[238]	validation_0-rmse:33.21704
[239]	validation_0-rmse:33.21841
[240]	validation_0-rmse:33.21414
[241]	validation_0-rmse:33.21485
[242]	validation_0-rmse:33.21576
[243]	validation_0-rmse:33.21461
[244]	validation_0-rmse:33.20385
[245]	validation_0-rmse:33.20610
[246]	validation_0-rmse:33.19702
[247]	validation_0-rmse:33.19477
[248]	validation_0-rmse:33.19683
[249]	validation_0-rmse:33.19618
[250]	validation_0-rmse:33.19883
[251]	validation_0-rmse:33.19763
[252]	validation_0-rmse:33.20333
[253]	validation_0-rmse:33.20804
[254]	validation_0-rmse:33.20570
[255]	validation_0-rmse:33.19982
[256]	validation_0-rmse:33.18714
[257]	validation_0-rmse:33.18121
[258]	validation_0-rmse:33.18720
[259]	validation_0-rmse:33.19265
[260]	validation_0-rmse:33.19366
[261]	validation_0-rmse:33.19451
[262]	validation_0-rmse:33.19795
[263]	validation_0-rmse:33.19537
[264]	validation_0-rmse:33.19213
[265]	validation_0-rmse:33.18983
[266]	validation_0-rmse:33.18927
[267]	validation_0-rmse:33.18880
[268]	validation_0-rmse:33.18505
[269]	validation_0-rmse:33.18841
[270]	validation_0-rmse:33.19676
[271]	validation_0-rmse:33.19575
[272]	validation_0-rmse:33.19027
[273]	validation_0-rmse:33.18949
[274]	validation_0-rmse:33.19389
[275]	validation_0-rmse:33.19236
[276]	validation_0-rmse:33.19078
[277]	validation_0-rmse:33.18861
[278]	validation_0-rmse:33.19040
[279]	validation_0-rmse:33.19400
[280]	validation_0-rmse:33.19977
[281]	validation_0-rmse:33.20108
[282]	validation_0-rmse:33.19532
[283]	validation_0-rmse:33.19562
[284]	validation_0-rmse:33.19427
[285]	validation_0-rmse:33.19895
[286]	validation_0-rmse:33.20108
[287]	validation_0-rmse:33.20118
[288]	validation_0-rmse:33.20227
[289]	validation_0-rmse:33.20016
[290]	validation_0-rmse:33.20580
[291]	validation_0-rmse:33.21174
[292]	validation_0-rmse:33.21323
[293]	validation_0-rmse:33.21365
[294]	validation_0-rmse:33.21222
[295]	validation_0-rmse:33.21026
[296]	validation_0-rmse:33.21100
[297]	validation_0-rmse:33.21685
[298]	validation_0-rmse:33.21497
[299]	validation_0-rmse:33.21628
[300]	validation_0-rmse:33.21700
[301]	validation_0-rmse:33.21904
[302]	validation_0-rmse:33.21846
[303]	validation_0-rmse:33.21762
[304]	validation_0-rmse:33.21765
[305]	validation_0-rmse:33.21810
[306]	validation_0-rmse:33.21791
[307]	validation_0-rmse:33.22205
[308]	validation_0-rmse:33.22091
[309]	validation_0-rmse:33.22302
[310]	validation_0-rmse:33.22338
[311]	validation_0-rmse:33.22582
[312]	validation_0-rmse:33.22366
[313]	validation_0-rmse:33.22282
[314]	validation_0-rmse:33.22268
[315]	validation_0-rmse:33.22217
[316]	validation_0-rmse:33.22134
[317]	validation_0-rmse:33.22179
[318]	validation_0-rmse:33.22538
[319]	validation_0-rmse:33.22366
[320]	validation_0-rmse:33.22180
[321]	validation_0-rmse:33.22130
[322]	validation_0-rmse:33.22175
[323]	validation_0-rmse:33.22526
[324]	validation_0-rmse:33.22545
[325]	validation_0-rmse:33.22494
[326]	validation_0-rmse:33.22655
[327]	validation_0-rmse:33.22590
[328]	validation_0-rmse:33.22560
[329]	validation_0-rmse:33.22765
[330]	validation_0-rmse:33.22828
[331]	validation_0-rmse:33.23042
[332]	validation_0-rmse:33.22966
[333]	validation_0-rmse:33.23106
[334]	validation_0-rmse:33.23215
[335]	validation_0-rmse:33.23402
[336]	validation_0-rmse:33.23534
[337]	validation_0-rmse:33.23523
[338]	validation_0-rmse:33.23800
[339]	validation_0-rmse:33.23894
[340]	validation_0-rmse:33.23832
[341]	validation_0-rmse:33.24054
[342]	validation_0-rmse:33.24151
[343]	validation_0-rmse:33.24198
[344]	validation_0-rmse:33.24088
[345]	validation_0-rmse:33.23881
[346]	validation_0-rmse:33.24318
[347]	validation_0-rmse:33.24330
[348]	validation_0-rmse:33.24189
[349]	validation_0-rmse:33.24244
[350]	validation_0-rmse:33.24353
[351]	validation_0-rmse:33.24335
[352]	validation_0-rmse:33.24530
[353]	validation_0-rmse:33.24361
[354]	validation_0-rmse:33.24270
[355]	validation_0-rmse:33.24350
[356]	validation_0-rmse:33.24081
[357]	validation_0-rmse:33.24034
[358]	validation_0-rmse:33.24159
[359]	validation_0-rmse:33.24150
[360]	validation_0-rmse:33.24403
[361]	validation_0-rmse:33.24445
[362]	validation_0-rmse:33.24381
[363]	validation_0-rmse:33.24472
[364]	validation_0-rmse:33.24420
[365]	validation_0-rmse:33.24651
[366]	validation_0-rmse:33.24559
[367]	validation_0-rmse:33.24595
[368]	validation_0-rmse:33.24666
[369]	validation_0-rmse:33.24883
[370]	validation_0-rmse:33.24879
[371]	validation_0-rmse:33.24768
[372]	validation_0-rmse:33.25021
[373]	validation_0-rmse:33.24955
[374]	validation_0-rmse:33.24973
[375]	validation_0-rmse:33.25051
[376]	validation_0-rmse:33.25258
[377]	validation_0-rmse:33.25235
[378]	validation_0-rmse:33.25499
[379]	validation_0-rmse:33.25615
[380]	validation_0-rmse:33.25640
[381]	validation_0-rmse:33.25694
[382]	validation_0-rmse:33.25777
[383]	validation_0-rmse:33.25828
[384]	validation_0-rmse:33.25708
[385]	validation_0-rmse:33.25485
[386]	validation_0-rmse:33.25750
[387]	validation_0-rmse:33.25923
[388]	validation_0-rmse:33.25860
[389]	validation_0-rmse:33.25804
[390]	validation_0-rmse:33.25769
[391]	validation_0-rmse:33.25757
[392]	validation_0-rmse:33.25838
[393]	validation_0-rmse:33.25887
[394]	validation_0-rmse:33.26077
[395]	validation_0-rmse:33.25946
[396]	validation_0-rmse:33.25813
[397]	validation_0-rmse:33.26007
[398]	validation_0-rmse:33.25998
[399]	validation_0-rmse:33.26026
[400]	validation_0-rmse:33.26247
[401]	validation_0-rmse:33.26352
[402]	validation_0-rmse:33.26331
[403]	validation_0-rmse:33.26300
[404]	validation_0-rmse:33.26405
[405]	validation_0-rmse:33.26454
[406]	validation_0-rmse:33.26376
[407]	validation_0-rmse:33.26355
[408]	validation_0-rmse:33.26307
[409]	validation_0-rmse:33.26233
[410]	validation_0-rmse:33.26335
[411]	validation_0-rmse:33.26466
[412]	validation_0-rmse:33.26500
[413]	validation_0-rmse:33.26449
[414]	validation_0-rmse:33.26382
[415]	validation_0-rmse:33.26427
[416]	validation_0-rmse:33.26237
[417]	validation_0-rmse:33.26153
[418]	validation_0-rmse:33.26244
[419]	validation_0-rmse:33.26208
[420]	validation_0-rmse:33.26123
[421]	validation_0-rmse:33.26239
[422]	validation_0-rmse:33.26169
[423]	validation_0-rmse:33.26247
[424]	validation_0-rmse:33.26261
[425]	validation_0-rmse:33.26361
[426]	validation_0-rmse:33.26406
[427]	validation_0-rmse:33.26538
[428]	validation_0-rmse:33.26504
[429]	validation_0-rmse:33.26484
[430]	validation_0-rmse:33.26432
[431]	validation_0-rmse:33.26413
[432]	validation_0-rmse:33.26329
[433]	validation_0-rmse:33.26312
[434]	validation_0-rmse:33.26448
[435]	validation_0-rmse:33.26450
[436]	validation_0-rmse:33.26468
[437]	validation_0-rmse:33.26531
[438]	validation_0-rmse:33.26542
[439]	validation_0-rmse:33.26593
[440]	validation_0-rmse:33.26700
[441]	validation_0-rmse:33.26746
[442]	validation_0-rmse:33.26546
[443]	validation_0-rmse:33.26469
[444]	validation_0-rmse:33.26508
[445]	validation_0-rmse:33.26615
[446]	validation_0-rmse:33.26584
[447]	validation_0-rmse:33.26482
[448]	validation_0-rmse:33.26465
[449]	validation_0-rmse:33.26291
[450]	validation_0-rmse:33.26381
[451]	validation_0-rmse:33.26501
[452]	validation_0-rmse:33.26477
[453]	validation_0-rmse:33.26386
[454]	validation_0-rmse:33.26332
[455]	validation_0-rmse:33.26408
[456]	validation_0-rmse:33.26405
[457]	validation_0-rmse:33.26439
[458]	validation_0-rmse:33.26347
[459]	validation_0-rmse:33.26379
[460]	validation_0-rmse:33.26422
[461]	validation_0-rmse:33.26397
[462]	validation_0-rmse:33.26427
[463]	validation_0-rmse:33.26429
[464]	validation_0-rmse:33.26383
[465]	validation_0-rmse:33.26364
[466]	validation_0-rmse:33.26367
[467]	validation_0-rmse:33.26426
[468]	validation_0-rmse:33.26495
[469]	validation_0-rmse:33.26512
[470]	validation_0-rmse:33.26484
[471]	validation_0-rmse:33.26461
[472]	validation_0-rmse:33.26330
[473]	validation_0-rmse:33.26521
[474]	validation_0-rmse:33.26597
[475]	validation_0-rmse:33.26512
[476]	validation_0-rmse:33.26500
[477]	validation_0-rmse:33.26440
[478]	validation_0-rmse:33.26501
[479]	validation_0-rmse:33.26483
[480]	validation_0-rmse:33.26468
[481]	validation_0-rmse:33.26459
[482]	validation_0-rmse:33.26431
[483]	validation_0-rmse:33.26445
[484]	validation_0-rmse:33.26405
[485]	validation_0-rmse:33.26421
[486]	validation_0-rmse:33.26497
[487]	validation_0-rmse:33.26535
[488]	validation_0-rmse:33.26542
[489]	validation_0-rmse:33.26473
[490]	validation_0-rmse:33.26473
[491]	validation_0-rmse:33.26456
[492]	validation_0-rmse:33.26628
[493]	validation_0-rmse:33.26660
[494]	validation_0-rmse:33.26674
[495]	validation_0-rmse:33.26680
[496]	validation_0-rmse:33.26609
[497]	validation_0-rmse:33.26605
[498]	validation_0-rmse:33.26611
[499]	validation_0-rmse:33.26545
[500]	validation_0-rmse:33.26524
[501]	validation_0-rmse:33.26404
[502]	validation_0-rmse:33.26318
[503]	validation_0-rmse:33.26305
[504]	validation_0-rmse:33.26366
[505]	validation_0-rmse:33.26335
[506]	validation_0-rmse:33.26393
[507]	validation_0-rmse:33.26411
[508]	validation_0-rmse:33.26437
[509]	validation_0-rmse:33.26440
[510]	validation_0-rmse:33.26447
[511]	validation_0-rmse:33.26458
[512]	validation_0-rmse:33.26492
[513]	validation_0-rmse:33.26482
[514]	validation_0-rmse:33.26533
[515]	validation_0-rmse:33.26634
[516]	validation_0-rmse:33.26636
[517]	validation_0-rmse:33.26596
[518]	validation_0-rmse:33.26600
[519]	validation_0-rmse:33.26578
[520]	validation_0-rmse:33.26592
[521]	validation_0-rmse:33.26507
[522]	validation_0-rmse:33.26624
[523]	validation_0-rmse:33.26599
[524]	validation_0-rmse:33.26547
[525]	validation_0-rmse:33.26620
[526]	validation_0-rmse:33.26601
[527]	validation_0-rmse:33.26587
[528]	validation_0-rmse:33.26570
[529]	validation_0-rmse:33.26633
[530]	validation_0-rmse:33.26667
[531]	validation_0-rmse:33.26644
[532]	validation_0-rmse:33.26589
[533]	validation_0-rmse:33.26585
[534]	validation_0-rmse:33.26628
[535]	validation_0-rmse:33.26665
[536]	validation_0-rmse:33.26617
[537]	validation_0-rmse:33.26624
[538]	validation_0-rmse:33.26647
[539]	validation_0-rmse:33.26742
[540]	validation_0-rmse:33.26640
[541]	validation_0-rmse:33.26650
[542]	validation_0-rmse:33.26625
[543]	validation_0-rmse:33.26643
[544]	validation_0-rmse:33.26678
[545]	validation_0-rmse:33.26705
[546]	validation_0-rmse:33.26697
[547]	validation_0-rmse:33.26735
[548]	validation_0-rmse:33.26685
[549]	validation_0-rmse:33.26705
[550]	validation_0-rmse:33.26724
[551]	validation_0-rmse:33.26651
[552]	validation_0-rmse:33.26700
[553]	validation_0-rmse:33.26666
[554]	validation_0-rmse:33.26650
[555]	validation_0-rmse:33.26643
[556]	validation_0-rmse:33.26675
[557]	validation_0-rmse:33.26656
[558]	validation_0-rmse:33.26640
[559]	validation_0-rmse:33.26611
[560]	validation_0-rmse:33.26623
[561]	validation_0-rmse:33.26598
[562]	validation_0-rmse:33.26610
[563]	validation_0-rmse:33.26646
[564]	validation_0-rmse:33.26690
[565]	validation_0-rmse:33.26707
[566]	validation_0-rmse:33.26754
[567]	validation_0-rmse:33.26787
[568]	validation_0-rmse:33.26776
[569]	validation_0-rmse:33.26769
[570]	validation_0-rmse:33.26751
[571]	validation_0-rmse:33.26755
[572]	validation_0-rmse:33.26759
[573]	validation_0-rmse:33.26672
[574]	validation_0-rmse:33.26668
[575]	validation_0-rmse:33.26677
[576]	validation_0-rmse:33.26651
[577]	validation_0-rmse:33.26672
[578]	validation_0-rmse:33.26653
[579]	validation_0-rmse:33.26645
[580]	validation_0-rmse:33.26654
[581]	validation_0-rmse:33.26659
[582]	validation_0-rmse:33.26631
[583]	validation_0-rmse:33.26616
[584]	validation_0-rmse:33.26604
[585]	validation_0-rmse:33.26586
[586]	validation_0-rmse:33.26598
[587]	validation_0-rmse:33.26589
[588]	validation_0-rmse:33.26566
[589]	validation_0-rmse:33.26528
[590]	validation_0-rmse:33.26531
[591]	validation_0-rmse:33.26513
[592]	validation_0-rmse:33.26479
[593]	validation_0-rmse:33.26465
[594]	validation_0-rmse:33.26443
[595]	validation_0-rmse:33.26473
[596]	validation_0-rmse:33.26478
[597]	validation_0-rmse:33.26488
[598]	validation_0-rmse:33.26423
[599]	validation_0-rmse:33.26444
[600]	validation_0-rmse:33.26489
[601]	validation_0-rmse:33.26486
[602]	validation_0-rmse:33.26496
[603]	validation_0-rmse:33.26511
[604]	validation_0-rmse:33.26524
[605]	validation_0-rmse:33.26517
[606]	validation_0-rmse:33.26445
[607]	validation_0-rmse:33.26437
[608]	validation_0-rmse:33.26429

In [12]:
results

{'Total Alkalinity':                         feature name    t-value  stat.significance  \
 0                   skin_temperature  18.392507       2.369725e-67
 1                 cec_pH_interaction  14.926905       1.246000e-46
 2                          elevation  11.401734       9.020171e-29
 3                  flow_accumulation   8.811196       3.882902e-18
 4                                EVI   8.675614       1.207699e-17
 5                             swir22   6.425324       1.842704e-10
 6    evaporation_precipitation_ratio   6.357067       2.841427e-10
 7                               clay   4.749550       2.265404e-06
 8           Land Surface Temperature   3.039231       2.419335e-03
 9                                 pH   2.424059       1.548454e-02
 10                  soil_temperature   2.322332       2.036946e-02
 11        phosphorous_pH_interaction   2.189053       2.877116e-02
 12  flow_acc_phosphorous_interaction   1.859463       6.318870e-02
 13             total_evaporation_sum   1.555471       1.200790e-01
 14                               pet   0.284734       7.758934e-01
 15                              NDMI  -0.409728       6.820733e-01
 16         flow_acc_clay_interaction  -0.976018       3.292392e-01
 17                            swir16  -0.994238       3.202943e-01
 18                     precipitation  -0.995729       3.195687e-01
 19                    cec_clay_ratio  -1.046102       2.957105e-01
 20                               nir  -1.530757       1.260758e-01
 21                             green  -1.547769       1.219246e-01
 22              NDVI_LST_interaction  -2.642226       8.336591e-03
 23                             MNDWI  -2.723895       6.539397e-03
 24           total_precipitation_sum  -3.116931       1.868130e-03
 25                               cec  -4.440622       9.743705e-06
 26                              NDVI  -4.477953       8.208805e-06
 27             volumetric_soil_water  -7.069911       2.546157e-12
 28                       phosphorous  -7.256191       6.889034e-13
 29                    temperature_2m -11.431195       7.052518e-29

     coefficient  selected
 0     24.090795         1
 1      1.667817         1
 2      2.186811         1
 3      2.113309         1
 4      9.881992         1
 5      5.340575         1
 6      9.294361         1
 7      2.747783         1
 8      1.446652         1
 9      1.745541         1
 10     2.284804         1
 11     0.805254         1
 12     2.121495         0
 13     0.459182         0
 14     0.159234         0
 15    -0.404439        -1
 16    -0.624303        -1
 17    -0.962892        -1
 18    -1.095472        -1
 19    -0.638244        -1
 20    -1.268241        -1
 21    -1.935501        -1
 22    -3.427538        -1
 23    -2.191494        -1
 24    -3.581376        -1
 25    -2.467509        -1
 26    -5.374174        -1
 27    -3.191127        -1
 28    -4.188329        -1
 29   -12.784751        -1  ,
 'Electrical Conductance':                         feature name    t-value  stat.significance  \
 0                                pet  12.910488       5.668502e-36
 1               NDVI_LST_interaction  12.199016       1.726012e-32
 2   flow_acc_phosphorous_interaction  10.893282       1.659595e-26
 3    evaporation_precipitation_ratio   9.981585       1.169537e-22
 4         phosphorous_pH_interaction   9.358317       3.434344e-20
 5                   soil_temperature   7.882345       6.756079e-15
 6                               clay   5.882709       5.128985e-09
 7              total_evaporation_sum   5.828441       7.051445e-09
 8                        phosphorous   4.930704       9.254285e-07
 9           Land Surface Temperature   3.925850       9.097204e-05
 10                         elevation   3.747449       1.865105e-04
 11                cec_pH_interaction   2.996531       2.782744e-03
 12                               EVI   1.648412       9.951137e-02
 13                    cec_clay_ratio   1.401778       1.612218e-01
 14         flow_acc_clay_interaction   1.363054       1.731034e-01
 15             volumetric_soil_water   1.169518       2.424111e-01
 16                                pH   0.789554       4.299335e-01
 17                              NDMI   0.786569       4.316786e-01
 18                             MNDWI   0.697451       4.856465e-01
 19                             green   0.193496       8.466014e-01
 20           total_precipitation_sum  -0.020751       9.834474e-01
 21                            swir16  -0.224508       8.223975e-01
 22                               nir  -0.898931       3.688581e-01
 23                 flow_accumulation  -1.255332       2.095873e-01
 24                               cec  -1.995235       4.622890e-02
 25                     precipitation  -2.284102       2.252881e-02
 26                            swir22  -2.925378       3.501125e-03
 27                    temperature_2m  -3.767795       1.722023e-04
 28                  skin_temperature  -5.594246       2.708500e-08
 29                              NDVI  -6.151993       1.022461e-09

     coefficient  selected
 0      2.573811         1
 1     19.296695         1
 2     12.492382         1
 3     15.277750         1
 4      4.235290         1
 5     12.132992         1
 6      1.442028         1
 7      1.643999         1
 8      1.933301         1
 9      2.013242         1
 10     0.553098         1
 11     0.735432         1
 12     1.570484         0
 13     0.388965         0
 14     1.139157         0
 15     0.787534         0
 16     0.368047         0
 17     1.352594         0
 18     0.538937         0
 19     0.184353         0
 20    -0.028025        -1
 21    -0.286388        -1
 22    -1.394502        -1
 23    -0.587820        -1
 24    -2.229358        -1
 25    -2.778248        -1
 26    -3.443516        -1
 27    -3.976540        -1
 28    -7.510980        -1
 29    -7.098090        -1  ,
 'Dissolved Reactive Phosphorus':                         feature name    t-value  stat.significance  \
 0         phosphorous_pH_interaction  19.613703       2.894143e-75
 1                   soil_temperature  14.069932       5.799086e-42
 2                               clay  11.768134       1.869819e-30
 3                                pet  10.716649       9.723430e-26
 4              total_evaporation_sum   6.888636       8.751126e-12
 5                                 pH   5.189601       2.443141e-07
 6               NDVI_LST_interaction   5.140065       3.167301e-07
 7                               NDMI   4.395611       1.194832e-05
 8                 cec_pH_interaction   4.148885       3.558678e-05
 9                                nir   3.485642       5.073662e-04
 10                         elevation   3.385853       7.308479e-04
 11                             green   2.965332       3.079015e-03
 12                 flow_accumulation   1.591036       1.118463e-01
 13                               cec   1.576701       1.151092e-01
 14                               EVI   1.484098       1.380273e-01
 15                     precipitation   1.364801       1.725539e-01
 16           total_precipitation_sum   0.392655       6.946393e-01
 17                    cec_clay_ratio   0.042269       9.662904e-01
 18                            swir16   0.006416       9.948819e-01
 19                             MNDWI  -0.462876       6.435315e-01
 20             volumetric_soil_water  -0.536787       5.915074e-01
 21  flow_acc_phosphorous_interaction  -0.821381       4.115820e-01
 22          Land Surface Temperature  -1.165855       2.438900e-01
 23         flow_acc_clay_interaction  -1.223517       2.213594e-01
 24                    temperature_2m  -1.335872       1.818287e-01
 25                              NDVI  -2.093187       3.652909e-02
 26                       phosphorous  -2.160079       3.095197e-02
 27   evaporation_precipitation_ratio  -3.692516       2.314155e-04
 28                  skin_temperature  -6.356855       2.860820e-10
 29                            swir22  -8.699352       1.011907e-17

     coefficient  selected
 0      2.127212         1
 1      4.524584         1
 2      9.051451         1
 3      2.026794         1
 4      2.873421         1
 5      3.572505         1
 6      4.194161         1
 7      2.464580         1
 8      1.614222         1
 9      2.210153         1
 10     0.492179         1
 11     1.945738         1
 12     0.329904         0
 13     0.553443         0
 14     0.952205         0
 15     0.818412         0
 16     0.201565         0
 17     0.012084         0
 18     0.004197         0
 19    -0.193222        -1
 20    -0.272373        -1
 21    -0.635343        -1
 22    -0.482540        -1
 23    -0.799156        -1
 24    -0.734733        -1
 25    -0.998628        -1
 26    -1.384505        -1
 27    -1.921900        -1
 28    -2.416343        -1
 29    -5.453293        -1  }

In [8]:
alk_feats = [
    "skin_temperature",
    "cec_pH_interaction",
    "elevation",
    "flow_accumulation",
    "EVI",
    "swir22",
    "evaporation_precipitation_ratio",
    "clay",
    "Land Surface Temperature",
    "pH",
    "soil_temperature",
    "phosphorous_pH_interaction"
]

len(alk_feats)

12

In [9]:
elec_feats = [
    "pet",
    "NDVI_LST_interaction",
    "flow_acc_phosphorous_interaction",
    "evaporation_precipitation_ratio",
    "phosphorous_pH_interaction",
    "soil_temperature",
    "clay",
    "total_evaporation_sum",
    "phosphorous",
    "Land Surface Temperature",
    "elevation",
    "cec_pH_interaction"
]

len(elec_feats)

12

In [10]:
drp_feats = [
    "phosphorous_pH_interaction",
    "soil_temperature",
    "clay",
    "pet",
    "total_evaporation_sum",
    "pH",
    "NDVI_LST_interaction",
    "NDMI",
    "cec_pH_interaction",
    "nir",
    "elevation",
    "green"
]

len(drp_feats)

12

In [11]:
selected_feats = list(set(alk_feats + elec_feats + drp_feats))

len(selected_feats)

20

## **Hyperparamter Optimization**

In [12]:
# Define new X_train and X_test based on feature selection results

X_train_fe = X_train[selected_feats]
X_test_fe = X_test[selected_feats]

X_train_fe.head()

,nir,total_evaporation_sum,EVI,phosphorous,pet,green,clay,pH,NDMI,cec_pH_interaction,elevation,NDVI_LST_interaction,skin_temperature,phosphorous_pH_interaction,evaporation_precipitation_ratio,soil_temperature,Land Surface Temperature,flow_accumulation,swir22,flow_acc_phosphorous_interaction
9297,18988.0,-0.000666,2142.0,19.0,218.20000,11249.5,25.0,66.0,0.050352,1584.0,1251.639625,62819712.0,303.094239,1254.0,-43.684083,303.376458,15936.0,1.000000,13577.0,19.000000
6378,13386.0,-0.000064,1247.0,21.0,225.60000,10901.0,27.0,73.0,-0.072333,1825.0,1012.728952,31571304.0,287.940814,1533.0,-34.438005,288.664629,14698.0,175.000000,13434.5,3675.000000
2420,11392.0,-0.000864,2681.0,26.0,210.20000,8999.0,24.0,70.0,0.058859,1540.0,171.655566,88964670.0,281.286717,1820.0,-0.532222,282.291864,14370.0,14123.536585,8997.0,367211.951220
6245,14316.0,-0.001014,1588.0,25.0,150.40001,10061.5,33.0,58.0,-0.061184,1276.0,1471.364299,44396740.0,276.171721,1450.0,-545.844320,276.449640,14585.0,65.000000,13487.5,1625.000000
4228,14446.5,-0.001255,1396.0,26.0,155.10000,10435.5,25.0,64.0,-0.078535,1536.0,898.500244,50134676.0,284.493027,1664.0,-9.226335,284.857243,14591.0,5514.232558,13974.0,143370.046512

In [19]:
# Next steps: perform hyperparameter optimization using Optuna. Then, using optimal
# hyperparameters retrain model for final testing.

def objective(trial):
    alpha = trial.suggest_float("alpha", 1e-4, 100.0, log=True)
    solver = trial.suggest_categorical("solver", ["auto", "cholesky", "svd", "sag", "saga"])

    pipe = make_pipeline(preprocessor, MultiOutputRegressor(Ridge(alpha=alpha, solver=solver)))
    
    score = cross_val_score(pipe, X_train_fe, y_train, cv=5, scoring="r2", n_jobs=-1).mean()

    return score

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=300)

[I 2026-03-12 17:36:17,230] A new study created in memory with name: no-name-a1a03038-c501-4b6b-8be9-db1a00a97650
[I 2026-03-12 17:36:18,811] Trial 0 finished with value: 0.26987427272831555 and parameters: {'alpha': 27.394312140538556, 'solver': 'cholesky'}. Best is trial 0 with value: 0.26987427272831555.
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2026-03-12 17:36:21,313] Trial 1 finished with value: 0.2727189579829215 and parameters: {'alpha': 0.9602869183525773, 'solver': 'saga'}. Best is trial 1 with value: 0.2727189579829215.
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2026-03-12 17:36:23,761] Trial 2 finished with value: 0.27284201990686835 and parameters: {'alpha': 0.4400142521716152, 'solver': 'saga'}. Best is trial 2 with value: 0.27284201990686835.
[I 2026-03-12 17:36:24,855] Trial 3 finished with value: 0.270014233886812 and parameters: {'alpha': 23.38383602356179, 'solver': 'sag'}. Best is trial 2 with value: 0.27284201990686835.
[I 2026-03-12 17:36:25,090] Trial 4 finished with value: 0.26997866667885984 and parameters: {'alpha': 24.297567875036687, 'solver': 'sag'}. Best is trial 2 with value: 0.27284201990686835.
[I 2026-03-12 17:36:25,130] Trial 5 finished with value: 0.2704959822520058 and parameters: {'alpha': 14.610866324094706, 'solver': 'svd'}. Best is trial 2 with value: 0.27284201990686835.
[I 2026-03-12 17:36:25,168] Trial 6 finished with value: 0.27308325021302754 and parameters: {'alpha': 0.0035497797688917297, 'solver': 'svd'}. Best is trial 6 with value: 0.27308325021302754.
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2026-03-12 17:36:26,342] Trial 7 finished with value: 0.27300439599678145 and parameters: {'alpha': 0.525715158095497, 'solver': 'sag'}. Best is trial 6 with value: 0.27308325021302754.
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2026-03-12 17:36:27,578] Trial 8 finished with value: 0.27302935906768944 and parameters: {'alpha': 0.4223666833876787, 'solver': 'sag'}. Best is trial 6 with value: 0.27308325021302754.
[I 2026-03-12 17:36:27,614] Trial 9 finished with value: 0.2730738612897213 and parameters: {'alpha': 0.40061362909743625, 'solver': 'cholesky'}. Best is trial 6 with value: 0.27308325021302754.
[I 2026-03-12 17:36:27,655] Trial 10 finished with value: 0.27308251911787884 and parameters: {'alpha': 0.00034595829041464697, 'solver': 'svd'}. Best is trial 6 with value: 0.27308325021302754.
[I 2026-03-12 17:36:27,695] Trial 11 finished with value: 0.27308253388609616 and parameters: {'alpha': 0.00040987741099318594, 'solver': 'svd'}. Best is trial 6 with value: 0.27308325021302754.
[I 2026-03-12 17:36:27,736] Trial 12 finished with value: 0.27308267090020816 and parameters: {'alpha': 0.0010044380721020445, 'solver': 'svd'}. Best is trial 6 with value: 0.27308325021302754.
[I 2026-03-12 17:36:27,779] Trial 13 finished with value: 0.2730837040447097 and parameters: {'alpha': 0.0055806402752301846, 'solver': 'auto'}. Best is trial 13 with value: 0.2730837040447097.
[I 2026-03-12 17:36:27,819] Trial 14 finished with value: 0.273084515967169 and parameters: {'alpha': 0.009299536599666496, 'solver': 'auto'}. Best is trial 14 with value: 0.273084515967169.
[I 2026-03-12 17:36:27,847] Trial 15 finished with value: 0.27308754719611195 and parameters: {'alpha': 0.024311529503092382, 'solver': 'auto'}. Best is trial 15 with value: 0.27308754719611195.
[I 2026-03-12 17:36:27,888] Trial 16 finished with value: 0.27309045466349857 and parameters: {'alpha': 0.04090368577044908, 'solver': 'auto'}. Best is trial 16 with value: 0.27309045466349857.
[I 2026-03-12 17:36:27,928] Trial 17 finished with value: 0.2730898396756045 and parameters: {'alpha': 0.037169284336730654, 'solver': 'auto'}. Best is trial 16 with value: 0.27309045466349857.
[I 2026-03-12 17:36:27,967] Trial 18 finished with value: 0.27309021197966793 and parameters: {'alpha': 0.039413628160270386, 'solver': 'auto'}. Best is trial 16 with value: 0.27309045466349857.
[I 2026-03-12 17:36:28,009] Trial 19 finished with value: 0.27309552536013193 and parameters: {'alpha': 0.07932541307130402, 'solver': 'auto'}. Best is trial 19 with value: 0.27309552536013193.
[I 2026-03-12 17:36:28,049] Trial 20 finished with value: 0.2719985710192789 and parameters: {'alpha': 3.7987762746323197, 'solver': 'auto'}. Best is trial 19 with value: 0.27309552536013193.
[I 2026-03-12 17:36:28,115] Trial 21 finished with value: 0.27309555983799716 and parameters: {'alpha': 0.07965956292392733, 'solver': 'auto'}. Best is trial 21 with value: 0.27309555983799716.
[I 2026-03-12 17:36:28,143] Trial 22 finished with value: 0.2730977862115189 and parameters: {'alpha': 0.10595692889961288, 'solver': 'auto'}. Best is trial 22 with value: 0.2730977862115189.
[I 2026-03-12 17:36:28,171] Trial 23 finished with value: 0.27236136706212905 and parameters: {'alpha': 2.5468230537905083, 'solver': 'auto'}. Best is trial 22 with value: 0.2730977862115189.
[I 2026-03-12 17:36:28,201] Trial 24 finished with value: 0.27309823106971437 and parameters: {'alpha': 0.11311162503349072, 'solver': 'auto'}. Best is trial 24 with value: 0.27309823106971437.
[I 2026-03-12 17:36:28,241] Trial 25 finished with value: 0.2730993932186279 and parameters: {'alpha': 0.1431026980209328, 'solver': 'auto'}. Best is trial 25 with value: 0.2730993932186279.
[I 2026-03-12 17:36:28,269] Trial 26 finished with value: 0.2730995443571141 and parameters: {'alpha': 0.16841353850469523, 'solver': 'auto'}. Best is trial 26 with value: 0.2730995443571141.
[I 2026-03-12 17:36:28,298] Trial 27 finished with value: 0.2730993655306252 and parameters: {'alpha': 0.1805246635135953, 'solver': 'cholesky'}. Best is trial 26 with value: 0.2730995443571141.
[I 2026-03-12 17:36:28,334] Trial 28 finished with value: 0.27249996449591074 and parameters: {'alpha': 2.1261563744753094, 'solver': 'cholesky'}. Best is trial 26 with value: 0.2730995443571141.
[I 2026-03-12 17:36:28,373] Trial 29 finished with value: 0.26917498796606165 and parameters: {'alpha': 66.0058460386979, 'solver': 'cholesky'}. Best is trial 26 with value: 0.2730995443571141.
[I 2026-03-12 17:36:28,414] Trial 30 finished with value: 0.2730857613752296 and parameters: {'alpha': 0.015236019288923135, 'solver': 'cholesky'}. Best is trial 26 with value: 0.2730995443571141.
[I 2026-03-12 17:36:28,442] Trial 31 finished with value: 0.2730995650260316 and parameters: {'alpha': 0.1652188212237921, 'solver': 'cholesky'}. Best is trial 31 with value: 0.2730995650260316.
[I 2026-03-12 17:36:28,471] Trial 32 finished with value: 0.2730993223295276 and parameters: {'alpha': 0.18246601919950997, 'solver': 'cholesky'}. Best is trial 31 with value: 0.2730995650260316.
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/rohan/Desktop/EY-Data-And-AI-Challenge/EY-AI-And-Data-Challenge/venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [20]:
study.best_params

{'alpha': 0.16103344304967634, 'solver': 'cholesky'}

In [21]:
study.best_value

0.27309957503712284

Clearly not performing very well, but for the purposes of stacking, lets continue to test it.

In [22]:
# Test performance with Regressor Chaining, given the optimized hyperparamters.
from itertools import permutations

targets = ['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']
combinations = list(permutations(range(len(targets))))

# alkalinity = 0, electrical conductance = 1, dissolved reactive phosphorous = 2
combinations

[(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]

In [23]:
# Test with all possible chain combinations!

ridge = Ridge(alpha=0.16, solver='cholesky')
scores = []

for combo in combinations:
    chain = RegressorChain(base_estimator=ridge, order=combo)
    pipe = make_pipeline(preprocessor, chain)

    cv_scores = cross_validate(pipe, X_train_fe, y_train, cv=5, return_train_score=True, n_jobs=-1)

    scores.append({
        'order': combo,
        'mean_train_score': np.mean(cv_scores['train_score']),
        'mean_test_score': np.mean(cv_scores['test_score']),
        "mean_fit_time": np.mean(cv_scores["fit_time"]),
        "mean_score_time": np.mean(cv_scores["score_time"])
    })

In [25]:
pd.DataFrame(scores)

,order,mean_train_score,mean_test_score,mean_fit_time,mean_score_time
0,"(0, 1, 2)",0.278975,0.2731,0.022816,0.001588
1,"(0, 2, 1)",0.278975,0.2731,0.011703,0.001636
2,"(1, 0, 2)",0.278975,0.2731,0.012251,0.001361
3,"(1, 2, 0)",0.278975,0.2731,0.011741,0.001691
4,"(2, 0, 1)",0.278975,0.2731,0.011292,0.001268
5,"(2, 1, 0)",0.278975,0.2731,0.013060,0.001815

In [26]:
## FINAL MODEL EVALUATION ON TEST SET TO SEE PERFORMANCE, using Multi Output Regressor

final_ridge = make_pipeline(preprocessor, MultiOutputRegressor(Ridge(alpha=0.16, solver='cholesky')))

final_ridge.fit(X_train_fe, y_train)
score = final_ridge.score(X_test_fe, y_test)

score

0.2726392670090901

In [27]:
## Predict Output for Submission Set

submission_df = pd.read_csv('../data/validation_set.csv')
submission_df.head()

,Unnamed: 0,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,elevation,EVI,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
0,0,-32.043333,27.822778,01-09-2014,NaN,NaN,NaN,161.90001,780.299056,1628.0,...,0.000007,0.136892,0.000000,1742.0,1742.0,4.542096e+07,351115.714286,338111.428571,-95.760822,0.962963
1,1,-33.329167,26.077500,16-09-2015,NaN,NaN,NaN,177.60000,279.351413,2933.0,...,0.000550,0.259777,27.521283,1495.0,1690.0,1.069767e+08,202225.000000,210314.000000,-3.653135,0.920000
2,2,-32.991639,27.640028,07-05-2015,NaN,NaN,NaN,158.40001,163.622679,4032.0,...,0.000174,0.232120,14.464016,1403.0,1525.0,1.034820e+08,121744.000000,126816.666667,-10.921542,0.958333
3,3,-34.096389,24.439167,07-02-2012,NaN,NaN,NaN,130.00000,44.046365,4701.0,...,NaN,NaN,42.085633,1121.0,1416.0,1.123978e+08,18889.531915,18889.531915,NaN,0.791667
4,4,-32.000556,28.581667,01-10-2014,NaN,NaN,NaN,152.50000,333.249422,1498.0,...,0.000618,0.336999,30.467072,1674.0,1674.0,6.468512e+07,410099.609756,381816.878049,-4.473473,0.931034

In [28]:
check_df = submission_df.drop(columns=['Unnamed: 0', 'Latitude', 
'Longitude', 'Sample Date', 
"Total Alkalinity", "Electrical Conductance",
'Dissolved Reactive Phosphorus'])

check_df.head()

,pet,elevation,EVI,NDVI,Land Surface Temperature,nir,green,swir16,swir22,NDMI,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
0,161.90001,780.299056,1628.0,3016.0,15060.0,15229.0,12868.0,14797.0,12421.0,0.014388,...,0.000007,0.136892,0.000000,1742.0,1742.0,4.542096e+07,351115.714286,338111.428571,-95.760822,0.962963
1,177.60000,279.351413,2933.0,7263.0,14729.0,NaN,NaN,NaN,NaN,NaN,...,0.000550,0.259777,27.521283,1495.0,1690.0,1.069767e+08,202225.000000,210314.000000,-3.653135,0.920000
2,158.40001,163.622679,4032.0,7036.0,14707.5,16221.0,9304.5,12536.5,9958.0,0.128123,...,0.000174,0.232120,14.464016,1403.0,1525.0,1.034820e+08,121744.000000,126816.666667,-10.921542,0.958333
3,130.00000,44.046365,4701.0,7474.5,15037.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,42.085633,1121.0,1416.0,1.123978e+08,18889.531915,18889.531915,NaN,0.791667
4,152.50000,333.249422,1498.0,4257.0,15195.0,9125.0,11100.5,9455.0,8711.0,-0.017761,...,0.000618,0.336999,30.467072,1674.0,1674.0,6.468512e+07,410099.609756,381816.878049,-4.473473,0.931034

In [29]:
test_df = check_df[selected_feats]

test_df.head()

,nir,total_evaporation_sum,EVI,phosphorous,pet,green,clay,pH,NDMI,cec_pH_interaction,elevation,NDVI_LST_interaction,skin_temperature,phosphorous_pH_interaction,evaporation_precipitation_ratio,soil_temperature,Land Surface Temperature,flow_accumulation,swir22,flow_acc_phosphorous_interaction
0,15229.0,-0.000788,1628.0,26.0,161.90001,12868.0,27.0,67.0,0.014388,1742.0,780.299056,4.542096e+07,288.386807,1742.0,-95.760822,288.264334,15060.0,13004.285714,12421.0,338111.428571
1,NaN,-0.002014,2933.0,26.0,177.60000,NaN,25.0,65.0,NaN,1495.0,279.351413,1.069767e+08,288.667907,1690.0,-3.653135,289.132705,14729.0,8089.000000,NaN,210314.000000
2,16221.0,-0.001915,4032.0,25.0,158.40001,9304.5,24.0,61.0,0.128123,1403.0,163.622679,1.034820e+08,291.107708,1525.0,-10.921542,291.689069,14707.5,5072.666667,9958.0,126816.666667
3,NaN,NaN,4701.0,24.0,130.00000,NaN,24.0,59.0,NaN,1121.0,44.046365,1.123978e+08,NaN,1416.0,NaN,NaN,15037.5,787.063830,NaN,18889.531915
4,9125.0,-0.002771,1498.0,27.0,152.50000,11100.5,29.0,62.0,-0.017761,1674.0,333.249422,6.468512e+07,288.706654,1674.0,-4.473473,289.314471,15195.0,14141.365854,8711.0,381816.878049

In [30]:
vals = final_ridge.predict(test_df)
val_df = pd.DataFrame(vals)
val_df.columns = ['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']

val_df

     Total Alkalinity  Electrical Conductance  Dissolved Reactive Phosphorus
0          117.791858              340.964798                      14.293684
1           82.681887              437.774868                      28.408598
2           74.735185              420.600599                      27.648816
3           52.519699              397.892213                      18.799831
4           66.903507              235.008298                      11.388053
..                ...                     ...                            ...
195         63.247680              283.789155                       4.623760
196         45.808492              286.341846                      10.967656
197         93.860789              245.483984                      20.972063
198         89.693633              269.390241                      18.001099
199        106.890403              409.893433                      22.733231

[200 rows x 3 columns]

In [31]:
submission = pd.DataFrame({
    'Longitude': submission_df['Longitude'],
    'Latitude': submission_df['Latitude'],
    'Sample Date': submission_df['Sample Date'],
    'Total Alkalinity': val_df['Total Alkalinity'],
    'Electrical Conductance': val_df['Electrical Conductance'],
    'Dissolved Reactive Phosphorus': val_df['Dissolved Reactive Phosphorus']
})

submission

,Longitude,Latitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus
0,27.822778,-32.043333,01-09-2014,117.791858,340.964798,14.293684
1,26.077500,-33.329167,16-09-2015,82.681887,437.774868,28.408598
2,27.640028,-32.991639,07-05-2015,74.735185,420.600599,27.648816
3,24.439167,-34.096389,07-02-2012,52.519699,397.892213,18.799831
4,28.581667,-32.000556,01-10-2014,66.903507,235.008298,11.388053
...,...,...,...,...,...,...
195,25.386667,-33.771111,06-12-2012,63.247680,283.789155,4.623760
196,27.390750,-33.185361,04-09-2014,45.808492,286.341846,10.967656
197,27.822778,-32.043333,28-09-2015,93.860789,245.483984,20.972063
198,25.161389,-33.001667,08-01-2015,89.693633,269.390241,18.001099
199,26.994720,-33.237780,27-03-2013,106.890403,409.893433,22.733231

In [32]:
submission.to_csv('../submission.csv', index=False)