# Evaluate Performance Using SVM Regression (RBF Kernel)

In [1]:
# Import statements (add as needed)

import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score, cross_validate, train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, FunctionTransformer, PowerTransformer
from sklearn.impute import SimpleImputer

from sklearn.compose import (
    TransformedTargetRegressor,
    make_column_transformer,
)

from sklearn.pipeline import make_pipeline
from skopt import BayesSearchCV

In [ ]:
# load both feature engineered dataset.

fe_df = pd.read_csv('../data/feature_engineered_training_set.csv')

In [3]:
fe_df = fe_df.drop(columns=['Unnamed: 0'])
fe_df.head()

,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,elevation,EVI,NDVI,Land Surface Temperature,nir,green,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
0,128.912,555.0,10.0,174.2,167.155040,241.0,636.0,15845.0,11190.0,11426.0,...,0.000001,0.008799,0.488024,1800.0,1725.0,10077420.0,8.676030e+07,9.502319e+07,-37.216627,1.142857
1,74.720,162.9,163.0,124.1,1521.251493,4643.0,7656.0,15190.0,17658.5,9550.0,...,0.007830,0.458929,97.342756,1755.0,1365.0,116294640.0,3.369889e+05,2.440265e+05,-0.523901,0.931034
2,89.254,573.0,80.0,127.5,1471.379902,3984.0,6276.0,14879.0,15210.0,10720.0,...,0.006964,0.393498,96.911494,1472.0,1344.0,93380604.0,2.800000e+01,2.100000e+01,-0.575803,0.821429
3,82.000,203.6,101.0,129.7,1342.659998,2217.0,3957.0,15228.5,14887.0,10943.0,...,0.007228,0.409018,102.307634,1495.0,1430.0,60259174.5,4.884100e+05,4.132700e+05,-0.538889,0.884615
4,56.100,145.1,151.0,129.2,1355.983661,4136.0,7396.0,15130.0,16828.5,9502.5,...,0.004980,0.437815,96.513882,1600.0,1280.0,111901480.0,1.337840e+05,9.556000e+04,-0.784851,0.892857

**SVM is quite sensitive to scaling, hence scale with standard scaler. Lets see if feature engineering helped during feature selection**

In [4]:
train_df, test_df = train_test_split(fe_df, test_size=0.3)      # create train set and test set to eval performance

In [5]:
train_df.head()

,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,elevation,EVI,NDVI,Land Surface Temperature,nir,green,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
6709,180.469,528.00,20.0,248.30000,305.502681,767.5,1254.5,15258.5,9801.5,9961.5,...,0.000001,0.023224,0.000000,1606.0,1533.0,1.914179e+07,315.000000,315.000000,-13.640771,1.047619
4754,209.156,1056.45,184.0,187.40001,1252.920472,2178.0,3693.0,15533.0,14829.5,10139.5,...,0.000041,0.232401,43.544638,1518.0,1320.0,5.736337e+07,812249.418605,649799.534884,-47.878838,0.920000
7640,91.340,401.00,20.0,165.00000,827.817958,4577.0,7175.0,14957.0,16977.0,8880.5,...,0.001658,0.398513,126.332161,1176.0,1288.0,1.073165e+08,111129.289474,82450.763158,-1.944391,0.677419
6875,123.278,340.50,23.0,158.60000,1560.779641,1363.5,2916.0,15228.0,12535.5,10114.0,...,0.000390,0.307589,53.536292,1690.0,1300.0,4.440485e+07,969493.000000,692495.000000,-3.824146,0.928571
6970,10.000,61.40,20.0,172.20000,1141.929640,2445.0,4066.0,15389.5,16524.5,10678.0,...,0.002143,0.375245,15.038089,1159.0,1220.0,6.257371e+07,47.923077,45.641026,-1.342796,0.904762

In [6]:
train_df.shape

(6523, 33)