# Evaluate Performance Using SVM Regression (RBF Kernel)

In [20]:
# Import statements (add as needed)

import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score, cross_validate, train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, FunctionTransformer, PowerTransformer
from sklearn.impute import SimpleImputer

from sklearn.compose import (
    TransformedTargetRegressor,
    make_column_transformer,
)

from sklearn.pipeline import make_pipeline
from skopt import BayesSearchCV
from missforest import MissForest

from sklearn.multioutput import MultiOutputRegressor
from sklearn.multioutput import RegressorChain
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from shap_select import shap_select
import xgboost as xgb
from xgboost import XGBRegressor

In [3]:
# load both feature engineered dataset.

fe_df = pd.read_csv('../data/feature_engineered_training_set.csv')

In [4]:
fe_df = fe_df.drop(columns=['Unnamed: 0'])
fe_df.head()

,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,elevation,EVI,NDVI,Land Surface Temperature,nir,green,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
0,128.912,555.0,10.0,174.2,167.155040,241.0,636.0,15845.0,11190.0,11426.0,...,0.000001,0.008799,0.488024,1800.0,1725.0,10077420.0,8.676030e+07,9.502319e+07,-37.216627,1.142857
1,74.720,162.9,163.0,124.1,1521.251493,4643.0,7656.0,15190.0,17658.5,9550.0,...,0.007830,0.458929,97.342756,1755.0,1365.0,116294640.0,3.369889e+05,2.440265e+05,-0.523901,0.931034
2,89.254,573.0,80.0,127.5,1471.379902,3984.0,6276.0,14879.0,15210.0,10720.0,...,0.006964,0.393498,96.911494,1472.0,1344.0,93380604.0,2.800000e+01,2.100000e+01,-0.575803,0.821429
3,82.000,203.6,101.0,129.7,1342.659998,2217.0,3957.0,15228.5,14887.0,10943.0,...,0.007228,0.409018,102.307634,1495.0,1430.0,60259174.5,4.884100e+05,4.132700e+05,-0.538889,0.884615
4,56.100,145.1,151.0,129.2,1355.983661,4136.0,7396.0,15130.0,16828.5,9502.5,...,0.004980,0.437815,96.513882,1600.0,1280.0,111901480.0,1.337840e+05,9.556000e+04,-0.784851,0.892857

**SVM is quite sensitive to scaling, hence scale with standard scaler. Lets see if feature engineering helped during feature selection**

In [5]:
train_df, test_df = train_test_split(fe_df, test_size=0.3)      # create train set and test set to eval performance

In [6]:
train_df.head()

,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,elevation,EVI,NDVI,Land Surface Temperature,nir,green,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
2662,177.103,452.0,10.0,154.20000,1496.121764,1131.0,2365.0,15121.0,NaN,NaN,...,1.722232e-06,0.257460,0.000000,1716.0,1188.0,35761165.00,2.357606e+06,1.463341e+06,-40.286367,0.896552
2649,81.079,243.8,10.0,134.90001,232.428267,3100.0,5526.0,14860.0,18055.0,9539.5,...,4.234621e-04,0.286886,0.000000,1500.0,1620.0,82116360.00,3.978163e+04,3.703807e+04,-5.702253,0.862069
1835,93.680,186.9,10.0,170.80000,1295.731321,2824.0,5599.0,15227.0,NaN,NaN,...,8.240361e-06,0.229584,14.154877,1820.0,1540.0,85255973.00,3.653896e+06,2.870918e+06,-443.982536,0.928571
8420,163.440,591.0,20.0,182.40001,1521.251493,1493.0,2598.5,14735.5,14232.0,10420.5,...,8.583069e-07,0.204995,0.000000,1755.0,1365.0,38290196.75,3.369889e+05,2.440265e+05,-84.782466,0.931034
2670,146.398,672.0,115.0,173.80000,1320.711972,1525.0,3340.5,15017.0,9872.0,9824.0,...,1.938298e-06,0.200379,7.927866,1342.0,1342.0,50164288.50,6.188652e+06,5.672931e+06,-29.499135,0.916667

In [7]:
train_df.shape

(6523, 33)

### Preprocess Data (Scale + Impute)

In [8]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6523 entries, 2662 to 488
Data columns (total 33 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Total Alkalinity                  6523 non-null   float64
 1   Electrical Conductance            6523 non-null   float64
 2   Dissolved Reactive Phosphorus     6523 non-null   float64
 3   pet                               6523 non-null   float64
 4   elevation                         6523 non-null   float64
 5   EVI                               6523 non-null   float64
 6   NDVI                              6523 non-null   float64
 7   Land Surface Temperature          6523 non-null   float64
 8   nir                               5790 non-null   float64
 9   green                             5790 non-null   float64
 10  swir16                            5790 non-null   float64
 11  swir22                            5790 non-null   float64
 12  NDMI                              5790 non-null   float64
 13  MNDWI                             5790 non-null   float64
 14  cec                               6523 non-null   float64
 15  clay                              6523 non-null   float64
 16  pH                                6523 non-null   float64
 17  phosphorous                       6523 non-null   float64
 18  flow_accumulation                 6523 non-null   float64
 19  skin_temperature                  6329 non-null   float64
 20  soil_temperature                  6329 non-null   float64
 21  temperature_2m                    6329 non-null   float64
 22  total_evaporation_sum             6329 non-null   float64
 23  total_precipitation_sum           6329 non-null   float64
 24  volumetric_soil_water             6329 non-null   float64
 25  precipitation                     6493 non-null   float64
 26  cec_pH_interaction                6523 non-null   float64
 27  phosphorous_pH_interaction        6523 non-null   float64
 28  NDVI_LST_interaction              6523 non-null   float64
 29  flow_acc_clay_interaction         6523 non-null   float64
 30  flow_acc_phosphorous_interaction  6523 non-null   float64
 31  evaporation_precipitation_ratio   6329 non-null   float64
 32  cec_clay_ratio                    6523 non-null   float64
dtypes: float64(33)
memory usage: 1.7 MB

In [9]:
train_df.columns[train_df.isnull().any()].tolist()

['nir',
 'green',
 'swir16',
 'swir22',
 'NDMI',
 'MNDWI',
 'skin_temperature',
 'soil_temperature',
 'temperature_2m',
 'total_evaporation_sum',
 'total_precipitation_sum',
 'volumetric_soil_water',
 'precipitation',
 'evaporation_precipitation_ratio']

Preprocessing must handle missing values, then scale all data. Can be done in a pipeline. Scaling for all features, imputation only for those with missing values.

In [10]:
## Data to be imputed with iterative imputer using random forest estimator to approximate miss forest.

imputing_feats = ['nir',
 'green',
 'swir16',
 'swir22',
 'NDMI',
 'MNDWI',
 'skin_temperature',
 'soil_temperature',
 'temperature_2m',
 'total_evaporation_sum',
 'total_precipitation_sum',
 'volumetric_soil_water',
 'precipitation',
 'evaporation_precipitation_ratio']

In [11]:
# Split train_df and test_df into X_train, X_test, y_train and y_test

X_train = train_df.drop(columns=['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus'])
y_train = train_df[['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']]

X_test = test_df.drop(columns=['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus'])
y_test = test_df[['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']]

In [12]:
X_train.head()

,pet,elevation,EVI,NDVI,Land Surface Temperature,nir,green,swir16,swir22,NDMI,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
2662,154.20000,1496.121764,1131.0,2365.0,15121.0,NaN,NaN,NaN,NaN,NaN,...,1.722232e-06,0.257460,0.000000,1716.0,1188.0,35761165.00,2.357606e+06,1.463341e+06,-40.286367,0.896552
2649,134.90001,232.428267,3100.0,5526.0,14860.0,18055.0,9539.5,14137.0,10647.0,0.121707,...,4.234621e-04,0.286886,0.000000,1500.0,1620.0,82116360.00,3.978163e+04,3.703807e+04,-5.702253,0.862069
1835,170.80000,1295.731321,2824.0,5599.0,15227.0,NaN,NaN,NaN,NaN,NaN,...,8.240361e-06,0.229584,14.154877,1820.0,1540.0,85255973.00,3.653896e+06,2.870918e+06,-443.982536,0.928571
8420,182.40001,1521.251493,1493.0,2598.5,14735.5,14232.0,10420.5,17884.5,14877.0,-0.113727,...,8.583069e-07,0.204995,0.000000,1755.0,1365.0,38290196.75,3.369889e+05,2.440265e+05,-84.782466,0.931034
2670,173.80000,1320.711972,1525.0,3340.5,15017.0,9872.0,9824.0,9109.0,8584.0,0.040198,...,1.938298e-06,0.200379,7.927866,1342.0,1342.0,50164288.50,6.188652e+06,5.672931e+06,-29.499135,0.916667

In [14]:
# Create a pipeline to first impute and then scale data.

preprocessor = make_pipeline(
    IterativeImputer(RandomForestRegressor(n_estimators=100, n_jobs=-1)),
    StandardScaler())

## **Feature Selection**

In [25]:
# Conduct Feature selection using shap-select.
# Convert X_train, y_train, X_test, y_test to dMatrix for quicker computation with XGBoost.

X_tr, X_te, y_tr, y_te = train_test_split(X_train, y_train, test_size=0.2)# split X and y train to conduct feature selection with less risk of overfitting.

imputer = IterativeImputer(RandomForestRegressor(n_estimators=100, n_jobs=-1))

X_tr_fe = imputer.fit_transform(X_tr)
X_te_fe = imputer.transform(X_te)

model = XGBRegressor(n_estimators=1000, verbosity = 0, eval_metric='rmse', objective='reg:squarederror')
model.fit(X_tr_fe, y_tr, eval_set=[(X_te_fe, y_te)])

[0]	validation_0-rmse:168.04381
[1]	validation_0-rmse:146.59254
[2]	validation_0-rmse:130.73105
[3]	validation_0-rmse:120.45616
[4]	validation_0-rmse:111.20117
[5]	validation_0-rmse:106.47870
[6]	validation_0-rmse:101.55609
[7]	validation_0-rmse:98.60203
[8]	validation_0-rmse:96.67591
[9]	validation_0-rmse:94.77552
[10]	validation_0-rmse:93.43011
[11]	validation_0-rmse:92.33267
[12]	validation_0-rmse:91.23877
[13]	validation_0-rmse:90.66998
[14]	validation_0-rmse:89.78317
[15]	validation_0-rmse:89.52940
[16]	validation_0-rmse:88.83717
[17]	validation_0-rmse:88.64103
[18]	validation_0-rmse:88.31201
[19]	validation_0-rmse:87.69775
[20]	validation_0-rmse:87.75310
[21]	validation_0-rmse:87.49676
[22]	validation_0-rmse:87.00309
[23]	validation_0-rmse:86.94456
[24]	validation_0-rmse:87.10972
[25]	validation_0-rmse:86.95969
[26]	validation_0-rmse:86.79934
[27]	validation_0-rmse:85.77407
[28]	validation_0-rmse:85.90435
[29]	validation_0-rmse:85.83699
[30]	validation_0-rmse:85.94894
[31]	validation_0-rmse:85.86304
[32]	validation_0-rmse:85.75793
[33]	validation_0-rmse:85.93654
[34]	validation_0-rmse:85.92862
[35]	validation_0-rmse:85.68008
[36]	validation_0-rmse:85.62030
[37]	validation_0-rmse:85.67199
[38]	validation_0-rmse:85.52369
[39]	validation_0-rmse:85.64626
[40]	validation_0-rmse:85.82732
[41]	validation_0-rmse:85.83667
[42]	validation_0-rmse:85.64967
[43]	validation_0-rmse:85.35906
[44]	validation_0-rmse:85.37949
[45]	validation_0-rmse:85.19159
[46]	validation_0-rmse:85.21638
[47]	validation_0-rmse:85.30969
[48]	validation_0-rmse:85.26365
[49]	validation_0-rmse:85.17878
[50]	validation_0-rmse:85.07121
[51]	validation_0-rmse:84.97266
[52]	validation_0-rmse:84.77059
[53]	validation_0-rmse:84.62401
[54]	validation_0-rmse:84.72656
[55]	validation_0-rmse:84.57086
[56]	validation_0-rmse:84.48656
[57]	validation_0-rmse:84.34700
[58]	validation_0-rmse:84.37012
[59]	validation_0-rmse:84.31454
[60]	validation_0-rmse:84.27638
[61]	validation_0-rmse:84.23186
[62]	validation_0-rmse:84.21882
[63]	validation_0-rmse:84.16642
[64]	validation_0-rmse:84.22826
[65]	validation_0-rmse:84.22742
[66]	validation_0-rmse:84.09641
[67]	validation_0-rmse:84.15321
[68]	validation_0-rmse:84.18579
[69]	validation_0-rmse:84.17732
[70]	validation_0-rmse:84.09299
[71]	validation_0-rmse:84.05608
[72]	validation_0-rmse:84.00324
[73]	validation_0-rmse:84.01934
[74]	validation_0-rmse:83.91879
[75]	validation_0-rmse:83.89632
[76]	validation_0-rmse:83.94361
[77]	validation_0-rmse:83.80917
[78]	validation_0-rmse:83.82682
[79]	validation_0-rmse:83.86056
[80]	validation_0-rmse:83.86123
[81]	validation_0-rmse:83.87745
[82]	validation_0-rmse:83.85471
[83]	validation_0-rmse:83.81870
[84]	validation_0-rmse:83.82936
[85]	validation_0-rmse:83.87119
[86]	validation_0-rmse:83.79284
[87]	validation_0-rmse:83.89181
[88]	validation_0-rmse:83.78879
[89]	validation_0-rmse:83.81421
[90]	validation_0-rmse:83.80168
[91]	validation_0-rmse:83.76473
[92]	validation_0-rmse:83.75889
[93]	validation_0-rmse:83.74140
[94]	validation_0-rmse:83.67569
[95]	validation_0-rmse:83.65731
[96]	validation_0-rmse:83.68514
[97]	validation_0-rmse:83.68559
[98]	validation_0-rmse:83.71251
[99]	validation_0-rmse:83.69755
[100]	validation_0-rmse:83.74696
[101]	validation_0-rmse:83.71143
[102]	validation_0-rmse:83.72929
[103]	validation_0-rmse:83.67486
[104]	validation_0-rmse:83.68309
[105]	validation_0-rmse:83.66462
[106]	validation_0-rmse:83.67876
[107]	validation_0-rmse:83.65657
[108]	validation_0-rmse:83.56331
[109]	validation_0-rmse:83.55549
[110]	validation_0-rmse:83.57556
[111]	validation_0-rmse:83.63111
[112]	validation_0-rmse:83.62111
[113]	validation_0-rmse:83.62563
[114]	validation_0-rmse:83.67338
[115]	validation_0-rmse:83.59674
[116]	validation_0-rmse:83.60348
[117]	validation_0-rmse:83.62910
[118]	validation_0-rmse:83.60240
[119]	validation_0-rmse:83.64635
[120]	validation_0-rmse:83.61839
[121]	validation_0-rmse:83.63077
[122]	validation_0-rmse:83.61708
[123]	validation_0-rmse:83.62198
[124]	validation_0-rmse:83.60091
[125]	validation_0-rmse:83.61892
[126]	validation_0-rmse:83.61530
[127]	validation_0-rmse:83.63914
[128]	validation_0-rmse:83.57536
[129]	validation_0-rmse:83.54555
[130]	validation_0-rmse:83.46464
[131]	validation_0-rmse:83.52622
[132]	validation_0-rmse:83.56979
[133]	validation_0-rmse:83.56002
[134]	validation_0-rmse:83.58516
[135]	validation_0-rmse:83.58913
[136]	validation_0-rmse:83.62002
[137]	validation_0-rmse:83.61752
[138]	validation_0-rmse:83.60275
[139]	validation_0-rmse:83.55297
[140]	validation_0-rmse:83.60429
[141]	validation_0-rmse:83.61342
[142]	validation_0-rmse:83.57716
[143]	validation_0-rmse:83.58040
[144]	validation_0-rmse:83.62306
[145]	validation_0-rmse:83.61602
[146]	validation_0-rmse:83.64599
[147]	validation_0-rmse:83.65889
[148]	validation_0-rmse:83.57120
[149]	validation_0-rmse:83.53804
[150]	validation_0-rmse:83.53749
[151]	validation_0-rmse:83.52114
[152]	validation_0-rmse:83.52126
[153]	validation_0-rmse:83.47667
[154]	validation_0-rmse:83.48123
[155]	validation_0-rmse:83.45696
[156]	validation_0-rmse:83.47681
[157]	validation_0-rmse:83.44884
[158]	validation_0-rmse:83.44697
[159]	validation_0-rmse:83.44588
[160]	validation_0-rmse:83.47337
[161]	validation_0-rmse:83.47962
[162]	validation_0-rmse:83.47028
[163]	validation_0-rmse:83.44340
[164]	validation_0-rmse:83.42911
[165]	validation_0-rmse:83.41928
[166]	validation_0-rmse:83.42006
[167]	validation_0-rmse:83.45095
[168]	validation_0-rmse:83.42348
[169]	validation_0-rmse:83.44741
[170]	validation_0-rmse:83.44994
[171]	validation_0-rmse:83.45895
[172]	validation_0-rmse:83.43484
[173]	validation_0-rmse:83.44986
[174]	validation_0-rmse:83.44625
[175]	validation_0-rmse:83.44033
[176]	validation_0-rmse:83.42704
[177]	validation_0-rmse:83.44247
[178]	validation_0-rmse:83.44210
[179]	validation_0-rmse:83.44460
[180]	validation_0-rmse:83.44215
[181]	validation_0-rmse:83.45001
[182]	validation_0-rmse:83.45879
[183]	validation_0-rmse:83.45858
[184]	validation_0-rmse:83.45595
[185]	validation_0-rmse:83.44277
[186]	validation_0-rmse:83.45623
[187]	validation_0-rmse:83.41154
[188]	validation_0-rmse:83.37795
[189]	validation_0-rmse:83.36910
[190]	validation_0-rmse:83.35734
[191]	validation_0-rmse:83.39321
[192]	validation_0-rmse:83.37957
[193]	validation_0-rmse:83.37981
[194]	validation_0-rmse:83.35597
[195]	validation_0-rmse:83.34774
[196]	validation_0-rmse:83.35130
[197]	validation_0-rmse:83.33385
[198]	validation_0-rmse:83.33370
[199]	validation_0-rmse:83.33574
[200]	validation_0-rmse:83.33235
[201]	validation_0-rmse:83.33560
[202]	validation_0-rmse:83.34727
[203]	validation_0-rmse:83.29417
[204]	validation_0-rmse:83.29644
[205]	validation_0-rmse:83.23225
[206]	validation_0-rmse:83.23725
[207]	validation_0-rmse:83.22926
[208]	validation_0-rmse:83.23420
[209]	validation_0-rmse:83.20315
[210]	validation_0-rmse:83.21868
[211]	validation_0-rmse:83.20631
[212]	validation_0-rmse:83.21113
[213]	validation_0-rmse:83.22293
[214]	validation_0-rmse:83.23618
[215]	validation_0-rmse:83.23889
[216]	validation_0-rmse:83.24943
[217]	validation_0-rmse:83.25378
[218]	validation_0-rmse:83.24824
[219]	validation_0-rmse:83.25942
[220]	validation_0-rmse:83.25776
[221]	validation_0-rmse:83.26085
[222]	validation_0-rmse:83.27519
[223]	validation_0-rmse:83.25422
[224]	validation_0-rmse:83.24978
[225]	validation_0-rmse:83.26767
[226]	validation_0-rmse:83.27466
[227]	validation_0-rmse:83.27998
[228]	validation_0-rmse:83.27185
[229]	validation_0-rmse:83.27953
[230]	validation_0-rmse:83.27933
[231]	validation_0-rmse:83.29422
[232]	validation_0-rmse:83.33468
[233]	validation_0-rmse:83.34294
[234]	validation_0-rmse:83.32772
[235]	validation_0-rmse:83.32555
[236]	validation_0-rmse:83.31758
[237]	validation_0-rmse:83.30934
[238]	validation_0-rmse:83.28406
[239]	validation_0-rmse:83.28630
[240]	validation_0-rmse:83.27833
[241]	validation_0-rmse:83.27611
[242]	validation_0-rmse:83.27836
[243]	validation_0-rmse:83.27641
[244]	validation_0-rmse:83.27272
[245]	validation_0-rmse:83.26666
[246]	validation_0-rmse:83.27112
[247]	validation_0-rmse:83.25185
[248]	validation_0-rmse:83.23743
[249]	validation_0-rmse:83.24168
[250]	validation_0-rmse:83.24013
[251]	validation_0-rmse:83.24802
[252]	validation_0-rmse:83.25403
[253]	validation_0-rmse:83.24358
[254]	validation_0-rmse:83.23904
[255]	validation_0-rmse:83.24078
[256]	validation_0-rmse:83.23519
[257]	validation_0-rmse:83.23251
[258]	validation_0-rmse:83.22008
[259]	validation_0-rmse:83.21417
[260]	validation_0-rmse:83.20144
[261]	validation_0-rmse:83.20911
[262]	validation_0-rmse:83.20905
[263]	validation_0-rmse:83.20694
[264]	validation_0-rmse:83.21036
[265]	validation_0-rmse:83.20914
[266]	validation_0-rmse:83.20928
[267]	validation_0-rmse:83.21621
[268]	validation_0-rmse:83.20703
[269]	validation_0-rmse:83.21325
[270]	validation_0-rmse:83.21242
[271]	validation_0-rmse:83.21454
[272]	validation_0-rmse:83.21864
[273]	validation_0-rmse:83.22981
[274]	validation_0-rmse:83.24034
[275]	validation_0-rmse:83.24383
[276]	validation_0-rmse:83.24208
[277]	validation_0-rmse:83.24074
[278]	validation_0-rmse:83.24722
[279]	validation_0-rmse:83.25014
[280]	validation_0-rmse:83.24180
[281]	validation_0-rmse:83.24936
[282]	validation_0-rmse:83.24632
[283]	validation_0-rmse:83.24886
[284]	validation_0-rmse:83.24694
[285]	validation_0-rmse:83.23418
[286]	validation_0-rmse:83.24601
[287]	validation_0-rmse:83.24719
[288]	validation_0-rmse:83.25839
[289]	validation_0-rmse:83.26430
[290]	validation_0-rmse:83.26539
[291]	validation_0-rmse:83.27206
[292]	validation_0-rmse:83.27034
[293]	validation_0-rmse:83.27142
[294]	validation_0-rmse:83.27315
[295]	validation_0-rmse:83.25876
[296]	validation_0-rmse:83.25838
[297]	validation_0-rmse:83.24846
[298]	validation_0-rmse:83.25334
[299]	validation_0-rmse:83.24474
[300]	validation_0-rmse:83.25099
[301]	validation_0-rmse:83.25397
[302]	validation_0-rmse:83.25454
[303]	validation_0-rmse:83.25031
[304]	validation_0-rmse:83.25029
[305]	validation_0-rmse:83.25055
[306]	validation_0-rmse:83.23843
[307]	validation_0-rmse:83.23790
[308]	validation_0-rmse:83.24008
[309]	validation_0-rmse:83.24439
[310]	validation_0-rmse:83.24930
[311]	validation_0-rmse:83.24007
[312]	validation_0-rmse:83.23256
[313]	validation_0-rmse:83.23527
[314]	validation_0-rmse:83.23714
[315]	validation_0-rmse:83.23673
[316]	validation_0-rmse:83.22069
[317]	validation_0-rmse:83.22041
[318]	validation_0-rmse:83.22389
[319]	validation_0-rmse:83.22458
[320]	validation_0-rmse:83.22947
[321]	validation_0-rmse:83.23103
[322]	validation_0-rmse:83.23749
[323]	validation_0-rmse:83.23516
[324]	validation_0-rmse:83.23364
[325]	validation_0-rmse:83.23253
[326]	validation_0-rmse:83.23361
[327]	validation_0-rmse:83.23377
[328]	validation_0-rmse:83.23045
[329]	validation_0-rmse:83.23130
[330]	validation_0-rmse:83.23007
[331]	validation_0-rmse:83.22330
[332]	validation_0-rmse:83.22538
[333]	validation_0-rmse:83.22381
[334]	validation_0-rmse:83.22593
[335]	validation_0-rmse:83.22521
[336]	validation_0-rmse:83.22557
[337]	validation_0-rmse:83.22383
[338]	validation_0-rmse:83.22460
[339]	validation_0-rmse:83.22099
[340]	validation_0-rmse:83.22280
[341]	validation_0-rmse:83.22638
[342]	validation_0-rmse:83.22821
[343]	validation_0-rmse:83.22823
[344]	validation_0-rmse:83.23269
[345]	validation_0-rmse:83.23669
[346]	validation_0-rmse:83.23814
[347]	validation_0-rmse:83.23596
[348]	validation_0-rmse:83.24738
[349]	validation_0-rmse:83.25112
[350]	validation_0-rmse:83.24974
[351]	validation_0-rmse:83.25647
[352]	validation_0-rmse:83.25458
[353]	validation_0-rmse:83.25785
[354]	validation_0-rmse:83.25708
[355]	validation_0-rmse:83.25843
[356]	validation_0-rmse:83.26288
[357]	validation_0-rmse:83.26121
[358]	validation_0-rmse:83.26224
[359]	validation_0-rmse:83.26278
[360]	validation_0-rmse:83.26190
[361]	validation_0-rmse:83.25629
[362]	validation_0-rmse:83.25553
[363]	validation_0-rmse:83.25696
[364]	validation_0-rmse:83.26036
[365]	validation_0-rmse:83.26237
[366]	validation_0-rmse:83.26203
[367]	validation_0-rmse:83.26588
[368]	validation_0-rmse:83.26491
[369]	validation_0-rmse:83.26691
[370]	validation_0-rmse:83.27000
[371]	validation_0-rmse:83.27254
[372]	validation_0-rmse:83.27629
[373]	validation_0-rmse:83.28212
[374]	validation_0-rmse:83.28375
[375]	validation_0-rmse:83.29166
[376]	validation_0-rmse:83.29598
[377]	validation_0-rmse:83.30067
[378]	validation_0-rmse:83.29997
[379]	validation_0-rmse:83.30143
[380]	validation_0-rmse:83.29998
[381]	validation_0-rmse:83.30345
[382]	validation_0-rmse:83.30795
[383]	validation_0-rmse:83.30924
[384]	validation_0-rmse:83.30815
[385]	validation_0-rmse:83.30258
[386]	validation_0-rmse:83.30365
[387]	validation_0-rmse:83.30021
[388]	validation_0-rmse:83.30294
[389]	validation_0-rmse:83.30041
[390]	validation_0-rmse:83.30440
[391]	validation_0-rmse:83.30142
[392]	validation_0-rmse:83.31001
[393]	validation_0-rmse:83.30994
[394]	validation_0-rmse:83.30658
[395]	validation_0-rmse:83.30906
[396]	validation_0-rmse:83.30661
[397]	validation_0-rmse:83.30995
[398]	validation_0-rmse:83.30526
[399]	validation_0-rmse:83.30455
[400]	validation_0-rmse:83.30493
[401]	validation_0-rmse:83.30851
[402]	validation_0-rmse:83.30683
[403]	validation_0-rmse:83.31135
[404]	validation_0-rmse:83.30873
[405]	validation_0-rmse:83.30492
[406]	validation_0-rmse:83.30791
[407]	validation_0-rmse:83.30834
[408]	validation_0-rmse:83.30977
[409]	validation_0-rmse:83.31292
[410]	validation_0-rmse:83.31082
[411]	validation_0-rmse:83.31324
[412]	validation_0-rmse:83.31186
[413]	validation_0-rmse:83.31032
[414]	validation_0-rmse:83.31121
[415]	validation_0-rmse:83.31361
[416]	validation_0-rmse:83.31267
[417]	validation_0-rmse:83.31081
[418]	validation_0-rmse:83.31038
[419]	validation_0-rmse:83.31111
[420]	validation_0-rmse:83.31341
[421]	validation_0-rmse:83.31151
[422]	validation_0-rmse:83.31375
[423]	validation_0-rmse:83.31372
[424]	validation_0-rmse:83.31340
[425]	validation_0-rmse:83.31318
[426]	validation_0-rmse:83.31273
[427]	validation_0-rmse:83.31277
[428]	validation_0-rmse:83.31335
[429]	validation_0-rmse:83.31286
[430]	validation_0-rmse:83.31435
[431]	validation_0-rmse:83.31533
[432]	validation_0-rmse:83.31446
[433]	validation_0-rmse:83.31573
[434]	validation_0-rmse:83.31507
[435]	validation_0-rmse:83.31546
[436]	validation_0-rmse:83.31706
[437]	validation_0-rmse:83.31397
[438]	validation_0-rmse:83.31401
[439]	validation_0-rmse:83.31541
[440]	validation_0-rmse:83.31385
[441]	validation_0-rmse:83.31776
[442]	validation_0-rmse:83.31780
[443]	validation_0-rmse:83.31887
[444]	validation_0-rmse:83.32431
[445]	validation_0-rmse:83.32702
[446]	validation_0-rmse:83.32916
[447]	validation_0-rmse:83.32780
[448]	validation_0-rmse:83.32756
[449]	validation_0-rmse:83.32898
[450]	validation_0-rmse:83.32785
[451]	validation_0-rmse:83.32829
[452]	validation_0-rmse:83.32984
[453]	validation_0-rmse:83.32912
[454]	validation_0-rmse:83.33127
[455]	validation_0-rmse:83.33210
[456]	validation_0-rmse:83.32981
[457]	validation_0-rmse:83.32577
[458]	validation_0-rmse:83.32468
[459]	validation_0-rmse:83.32413
[460]	validation_0-rmse:83.32457
[461]	validation_0-rmse:83.32558
[462]	validation_0-rmse:83.32486
[463]	validation_0-rmse:83.32516
[464]	validation_0-rmse:83.32662
[465]	validation_0-rmse:83.32795
[466]	validation_0-rmse:83.32857
[467]	validation_0-rmse:83.32913
[468]	validation_0-rmse:83.33082
[469]	validation_0-rmse:83.33305
[470]	validation_0-rmse:83.33451
[471]	validation_0-rmse:83.33403
[472]	validation_0-rmse:83.33679
[473]	validation_0-rmse:83.33626
[474]	validation_0-rmse:83.33376
[475]	validation_0-rmse:83.33184
[476]	validation_0-rmse:83.33093
[477]	validation_0-rmse:83.33132
[478]	validation_0-rmse:83.33069
[479]	validation_0-rmse:83.33121
[480]	validation_0-rmse:83.33178
[481]	validation_0-rmse:83.33363
[482]	validation_0-rmse:83.33413
[483]	validation_0-rmse:83.33420
[484]	validation_0-rmse:83.33368
[485]	validation_0-rmse:83.33386
[486]	validation_0-rmse:83.33482
[487]	validation_0-rmse:83.33446
[488]	validation_0-rmse:83.33568
[489]	validation_0-rmse:83.33701
[490]	validation_0-rmse:83.33648
[491]	validation_0-rmse:83.33636
[492]	validation_0-rmse:83.33955
[493]	validation_0-rmse:83.33969
[494]	validation_0-rmse:83.33887
[495]	validation_0-rmse:83.33891
[496]	validation_0-rmse:83.34091
[497]	validation_0-rmse:83.34018
[498]	validation_0-rmse:83.34031
[499]	validation_0-rmse:83.34371
[500]	validation_0-rmse:83.34296
[501]	validation_0-rmse:83.34236
[502]	validation_0-rmse:83.34380
[503]	validation_0-rmse:83.34284
[504]	validation_0-rmse:83.34322
[505]	validation_0-rmse:83.34195
[506]	validation_0-rmse:83.34206
[507]	validation_0-rmse:83.33998
[508]	validation_0-rmse:83.33973
[509]	validation_0-rmse:83.33983
[510]	validation_0-rmse:83.33986
[511]	validation_0-rmse:83.33931
[512]	validation_0-rmse:83.34007
[513]	validation_0-rmse:83.33983
[514]	validation_0-rmse:83.33991
[515]	validation_0-rmse:83.34044
[516]	validation_0-rmse:83.33983
[517]	validation_0-rmse:83.33817
[518]	validation_0-rmse:83.33966
[519]	validation_0-rmse:83.33750
[520]	validation_0-rmse:83.33913
[521]	validation_0-rmse:83.33919
[522]	validation_0-rmse:83.33855
[523]	validation_0-rmse:83.33710
[524]	validation_0-rmse:83.33712
[525]	validation_0-rmse:83.33609
[526]	validation_0-rmse:83.33680
[527]	validation_0-rmse:83.33754
[528]	validation_0-rmse:83.33968
[529]	validation_0-rmse:83.34071
[530]	validation_0-rmse:83.33998
[531]	validation_0-rmse:83.34034
[532]	validation_0-rmse:83.34101
[533]	validation_0-rmse:83.34001
[534]	validation_0-rmse:83.33924
[535]	validation_0-rmse:83.33764
[536]	validation_0-rmse:83.33796
[537]	validation_0-rmse:83.33706
[538]	validation_0-rmse:83.33846
[539]	validation_0-rmse:83.33913
[540]	validation_0-rmse:83.33786
[541]	validation_0-rmse:83.33659
[542]	validation_0-rmse:83.33668
[543]	validation_0-rmse:83.33774
[544]	validation_0-rmse:83.33882
[545]	validation_0-rmse:83.33788
[546]	validation_0-rmse:83.33927
[547]	validation_0-rmse:83.33894
[548]	validation_0-rmse:83.33846
[549]	validation_0-rmse:83.33804
[550]	validation_0-rmse:83.33788
[551]	validation_0-rmse:83.33873
[552]	validation_0-rmse:83.33918
[553]	validation_0-rmse:83.33953
[554]	validation_0-rmse:83.34010
[555]	validation_0-rmse:83.34000
[556]	validation_0-rmse:83.34022
[557]	validation_0-rmse:83.34188
[558]	validation_0-rmse:83.34203
[559]	validation_0-rmse:83.34142
[560]	validation_0-rmse:83.34172
[561]	validation_0-rmse:83.34179
[562]	validation_0-rmse:83.34275
[563]	validation_0-rmse:83.34362
[564]	validation_0-rmse:83.34328
[565]	validation_0-rmse:83.34345
[566]	validation_0-rmse:83.34481
[567]	validation_0-rmse:83.34482
[568]	validation_0-rmse:83.34439
[569]	validation_0-rmse:83.34276
[570]	validation_0-rmse:83.34151
[571]	validation_0-rmse:83.34178
[572]	validation_0-rmse:83.34383
[573]	validation_0-rmse:83.34307
[574]	validation_0-rmse:83.34229
[575]	validation_0-rmse:83.34268
[576]	validation_0-rmse:83.34332
[577]	validation_0-rmse:83.34423
[578]	validation_0-rmse:83.34458
[579]	validation_0-rmse:83.34420
[580]	validation_0-rmse:83.34423
[581]	validation_0-rmse:83.34438
[582]	validation_0-rmse:83.34562
[583]	validation_0-rmse:83.34624
[584]	validation_0-rmse:83.34627
[585]	validation_0-rmse:83.34635
[586]	validation_0-rmse:83.34629
[587]	validation_0-rmse:83.34571
[588]	validation_0-rmse:83.34545
[589]	validation_0-rmse:83.34598
[590]	validation_0-rmse:83.34566
[591]	validation_0-rmse:83.34473
[592]	validation_0-rmse:83.34530
[593]	validation_0-rmse:83.34501
[594]	validation_0-rmse:83.34585
[595]	validation_0-rmse:83.34574
[596]	validation_0-rmse:83.34595
[597]	validation_0-rmse:83.34599
[598]	validation_0-rmse:83.34545
[599]	validation_0-rmse:83.34570
[600]	validation_0-rmse:83.34610
[601]	validation_0-rmse:83.34688
[602]	validation_0-rmse:83.34725
[603]	validation_0-rmse:83.34753
[604]	validation_0-rmse:83.34840
[605]	validation_0-rmse:83.34742
[606]	validation_0-rmse:83.34708
[607]	validation_0-rmse:83.34599
[608]	validation_0-rmse:83.34533

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=1000,
             n_jobs=None, num_parallel_tree=None, ...)

In [45]:
# Next steps: Scale data and perform hyperparameter optimization

pipe = make_pipeline(StandardScaler(), MultiOutputRegressor(SVR()))
search_space = {
    "multioutputregressor__estimator__C": np.logspace(0, 2, 10),
    "multioutputregressor__estimator__gamma": 10.0 ** np.logspace(-3, 0, 10),
    "multioutputregressor__estimator__epsilon": np.logspace(-3, 0, 10)
}

search = BayesSearchCV(pipe, search_spaces=search_space, cv=10, return_train_score=True)
search.fit(X_train_rfe, y_train)

BayesSearchCV(cv=10,
              estimator=Pipeline(steps=[('standardscaler', StandardScaler()),
                                        ('multioutputregressor',
                                         MultiOutputRegressor(estimator=SVR()))]),
              return_train_score=True,
              search_spaces={'multioutputregressor__estimator__C': array([  1.        ,   1.66810054,   2.7825594 ,   4.64158883,
         7.74263683,  12.91549665,  21.5443469 ,  35.93813664,
        59.94842503, 100.        ]),
                             'multioutputregressor__estimator__epsilon': array([0.001     , 0.00215443, 0.00464159, 0.01      , 0.02154435,
       0.04641589, 0.1       , 0.21544347, 0.46415888, 1.        ]),
                             'multioutputregressor__estimator__gamma': array([ 1.00230524,  1.00497309,  1.01074497,  1.02329299,  1.05085876,
        1.11279685,  1.25892541,  1.64226588,  2.91178218, 10.        ])})

In [50]:
pd.DataFrame(search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_multioutputregressor__estimator__C,param_multioutputregressor__estimator__epsilon,param_multioutputregressor__estimator__gamma,params,split0_test_score,split1_test_score,...,split3_train_score,split4_train_score,split5_train_score,split6_train_score,split7_train_score,split8_train_score,split9_train_score,mean_train_score,std_train_score,rank_train_score
0,1.582671,0.042356,0.304575,0.008335,7.742637,0.002154,1.010745,{'multioutputregressor__estimator__C': 7.74263...,0.086708,0.043829,...,0.169461,0.169616,0.170576,0.168989,0.171299,0.169995,0.170697,0.169459,0.001849,38
1,1.561258,0.017597,0.311083,0.005713,4.641589,0.004642,1.023293,{'multioutputregressor__estimator__C': 4.64158...,0.025693,-0.012033,...,0.074099,0.075233,0.075764,0.074198,0.076496,0.074741,0.075953,0.074958,0.001388,42
2,1.488706,0.031019,0.308189,0.006614,1.000000,0.002154,2.911782,"{'multioutputregressor__estimator__C': 1.0, 'm...",-0.073953,-0.104523,...,-0.072780,-0.071753,-0.071788,-0.071822,-0.071609,-0.073005,-0.071716,-0.071921,0.000605,50
3,1.577950,0.032292,0.305206,0.006029,7.742637,0.021544,1.642266,{'multioutputregressor__estimator__C': 7.74263...,0.013309,-0.028764,...,0.102287,0.103257,0.103419,0.102695,0.104507,0.102391,0.103726,0.102773,0.001454,41
4,1.393734,0.008978,0.288003,0.001420,1.000000,0.100000,1.642266,"{'multioutputregressor__estimator__C': 1.0, 'm...",-0.066815,-0.098045,...,-0.066105,-0.065083,-0.065059,-0.065288,-0.064770,-0.066132,-0.064857,-0.065241,0.000608,49
5,1.806105,0.087685,0.311249,0.010119,21.544347,0.464159,1.010745,{'multioutputregressor__estimator__C': 21.5443...,0.260762,0.214463,...,0.449641,0.447490,0.449922,0.450667,0.450451,0.449412,0.451393,0.448558,0.002632,32
6,1.710354,0.016773,0.302228,0.004521,12.915497,0.001000,1.112797,{'multioutputregressor__estimator__C': 12.9154...,0.144971,0.096487,...,0.276872,0.276172,0.277204,0.276098,0.278631,0.277058,0.278218,0.276272,0.002338,36
7,2.162698,0.029628,0.311185,0.004723,59.948425,0.100000,10.000000,{'multioutputregressor__estimator__C': 59.9484...,0.039879,0.006691,...,0.598565,0.596552,0.596963,0.599801,0.599249,0.597284,0.598927,0.597844,0.001281,27
8,1.570883,0.025779,0.302421,0.004542,7.742637,0.001000,1.258925,{'multioutputregressor__estimator__C': 7.74263...,0.048369,0.005425,...,0.133912,0.134856,0.135374,0.134141,0.136343,0.134235,0.135409,0.134400,0.001656,40
9,2.045654,0.022148,0.303204,0.005257,35.938137,0.002154,1.010745,{'multioutputregressor__estimator__C': 35.9381...,0.355781,0.311600,...,0.605819,0.602874,0.606087,0.606946,0.605782,0.605228,0.607010,0.604591,0.002102,23
10,2.105098,0.073888,0.305881,0.010923,35.938137,0.001000,1.010745,{'multioutputregressor__estimator__C': 35.9381...,0.355780,0.311598,...,0.605817,0.602873,0.606086,0.606944,0.605781,0.605226,0.607009,0.604590,0.002102,24
11,1.993444,0.018472,0.302517,0.007392,35.938137,0.010000,1.010745,{'multioutputregressor__estimator__C': 35.9381...,0.355791,0.311613,...,0.605830,0.602885,0.606098,0.606956,0.605793,0.605239,0.607021,0.604602,0.002102,22
12,1.980728,0.021371,0.308102,0.022677,35.938137,0.021544,1.010745,{'multioutputregressor__estimator__C': 35.9381...,0.355805,0.311631,...,0.605845,0.602900,0.606114,0.606971,0.605809,0.605254,0.607036,0.604618,0.002102,21
13,1.881282,0.039203,0.301132,0.006878,35.938137,0.464159,1.010745,{'multioutputregressor__estimator__C': 35.9381...,0.356354,0.312320,...,0.606429,0.603486,0.606705,0.607530,0.606399,0.605822,0.607610,0.605200,0.002094,18
14,1.973923,0.045921,0.304509,0.006005,35.938137,0.046416,1.010745,{'multioutputregressor__estimator__C': 35.9381...,0.355835,0.311670,...,0.605879,0.602934,0.606149,0.607004,0.605844,0.605287,0.607069,0.604652,0.002102,20
15,1.852990,0.019133,0.300237,0.004132,35.938137,0.464159,1.258925,{'multioutputregressor__estimator__C': 35.9381...,0.295687,0.246410,...,0.571161,0.568790,0.571083,0.572084,0.571690,0.570470,0.572763,0.570021,0.002226,29
16,1.920565,0.035391,0.303999,0.005134,35.938137,0.215443,1.010745,{'multioutputregressor__estimator__C': 35.9381...,0.356046,0.311934,...,0.606106,0.603161,0.606380,0.607222,0.606075,0.605508,0.607291,0.604879,0.002099,19
17,1.819772,0.015851,0.296910,0.005487,35.938137,1.000000,1.010745,{'multioutputregressor__estimator__C': 35.9381...,0.357017,0.313141,...,0.607069,0.604129,0.607351,0.608133,0.607039,0.606442,0.608245,0.605839,0.002083,17
18,1.807081,0.016433,0.294600,0.003304,35.938137,1.000000,1.112797,{'multioutputregressor__estimator__C': 35.9381...,0.330375,0.283903,...,0.591429,0.588919,0.591807,0.592629,0.591808,0.590853,0.593062,0.590396,0.002161,28
19,1.820787,0.025019,0.297886,0.007664,35.938137,1.000000,1.050859,{'multioutputregressor__estimator__C': 35.9381...,0.346285,0.301289,...,0.600769,0.598046,0.601076,0.601881,0.600875,0.600190,0.602078,0.599611,0.002109,26
20,1.814740,0.023066,0.295255,0.004546,35.938137,1.000000,1.004973,{'multioutputregressor__estimator__C': 35.9381...,0.358597,0.314883,...,0.607994,0.605021,0.608268,0.609053,0.607951,0.607358,0.609150,0.606754,0.002079,16
21,1.808034,0.010343,0.297103,0.005152,35.938137,1.000000,1.002305,{'multioutputregressor__estimator__C': 35.9381...,0.359330,0.315691,...,0.608422,0.605436,0.608692,0.609480,0.608373,0.607782,0.609568,0.607178,0.002076,15
22,1.818689,0.035447,0.299144,0.005855,35.938137,1.000000,1.642266,{'multioutputregressor__estimator__C': 35.9381...,0.229263,0.176224,...,0.533115,0.531497,0.532542,0.533810,0.533951,0.532148,0.534805,0.532073,0.002180,30
23,1.688244,0.013764,0.294970,0.004103,21.544347,1.000000,1.642266,{'multioutputregressor__estimator__C': 21.5443...,0.147875,0.095072,...,0.364652,0.363889,0.364430,0.364713,0.366265,0.363943,0.366346,0.363949,0.002138,34
24,1.919642,0.031285,0.317969,0.028137,35.938137,1.000000,10.000000,{'multioutputregressor__estimator__C': 35.9381...,0.007780,-0.025805,...,0.412708,0.411335,0.411269,0.414274,0.413979,0.411734,0.412919,0.412219,0.001212,33
25,1.830504,0.010049,0.306856,0.006335,21.544347,1.000000,10.000000,{'multioutputregressor__estimator__C': 21.5443...,-0.024605,-0.057132,...,0.245898,0.245045,0.245098,0.247661,0.247229,0.245154,0.246369,0.245829,0.000977,37
26,1.358198,0.010230,0.282009,0.004973,2.782559,1.000000,1.002305,{'multioutputregressor__estimator__C': 2.78255...,-0.011092,-0.046189,...,0.013446,0.014601,0.014991,0.013988,0.015717,0.014077,0.015649,0.014565,0.000996,44
27,1.365764,0.010176,0.285925,0.004631,1.668101,0.464159,1.050859,{'multioutputregressor__estimator__C': 1.66810...,-0.040063,-0.072596,...,-0.030091,-0.029134,-0.028815,-0.029567,-0.028344,-0.029722,-0.028393,-0.029141,0.000797,46
28,1.967963,0.019841,0.300267,0.004167,35.938137,0.021544,1.023293,{'multioutputregressor__estimator__C': 35.9381...,0.352389,0.307858,...,0.603839,0.600952,0.604116,0.604973,0.603837,0.603251,0.605083,0.602632,0.002111,25
29,1.699486,0.013415,0.300363,0.001354,12.915497,0.004642,2.911782,{'multioutputregressor__estimator__C': 12.9154...,0.002099,-0.041704,...,0.157994,0.158445,0.158445,0.159007,0.160046,0.157382,0.158829,0.158134,0.001373,39
30,1.588657,0.012390,0.307656,0.004623,1.668101,0.001000,10.000000,{'multioutputregressor__estimator__C': 1.66810...,-0.078270,-0.107804,...,-0.065682,-0.064818,-0.064913,-0.064568,-0.064509,-0.065873,-0.064601,-0.064822,0.000568,48
31,1.928880,0.017891,0.305156,0.005310,35.938137,0.004642,2.911782,{'multioutputregressor__estimator__C': 35.9381...,0.120330,0.066329,...,0.469365,0.468683,0.469177,0.470776,0.471285,0.468423,0.471575,0.469033,0.001929,31
32,1.638889,0.016179,0.308901,0.005687,7.742637,0.004642,10.000000,{'multioutputregressor__estimator__C': 7.74263...,-0.069483,-0.100645,...,0.032980,0.033121,0.033172,0.034548,0.034309,0.032724,0.034091,0.033611,0.000622,43
33,2.734043,0.031520,0.300847,0.003645,100.000000,0.002154,1.112797,"{'multioutputregressor__estimator__C': 100.0, ...",0.482811,0.434661,...,0.841853,0.839319,0.841751,0.843393,0.841286,0.841187,0.840371,0.841196,0.001188,7
34,2.293050,0.011224,0.294214,0.002466,100.000000,1.000000,1.050859,"{'multioutputregressor__estimator__C': 100.0, ...",0.497434,0.451031,...,0.846413,0.843924,0.846194,0.848005,0.845820,0.845854,0.844802,0.845716,0.001227,4
35,2.518512,0.037100,0.300564,0.004662,100.000000,0.100000,1.050859,"{'multioutputregressor__estimator__C': 100.0, ...",0.498139,0.451402,...,0.846241,0.843750,0.846015,0.847859,0.845630,0.845677,0.844623,0.845540,0.001231,5
36,2.446492,0.010177,0.300533,0.003962,100.000000,0.100000,1.258925,"{'multioutputregressor__estimator__C': 100.0, ...",0.448301,0.397993,...,0.832234,0.829720,0.832195,0.833635,0.831786,0.831530,0.830990,0.831707,0.001086,8
37,2.435127,0.027127,0.301697,0.002725,100.000000,0.100000,1.642266,"{'multioutputregressor__estimator__C': 100.0, ...",0.372655,0.321329,...,0.812317,0.810370,0.812463,0.813558,0.812470,0.811101,0.811597,0.811963,0.000962,9
38,2.731892,0.051535,0.305681,0.004902,100.000000,0.004642,1.050859,"{'multioutputregressor__estimator__C': 100.0, ...",0.498201,0.451429,...,0.846206,0.843715,0.845980,0.847827,0.845593,0.845642,0.844588,0.845505,0.001232,6
39,2.570423,0.022031,0.302966,0.006700,100.000000,0.002154,2.911782,"{'multioutputregressor__estimator__C': 100.0, ...",0.232972,0.185408,...,0.781232,0.779843,0.781436,0.782100,0.781994,0.779545,0.781684,0.781074,0.000957,10
40,2.605867,0.062232,0.311099,0.003697,100.000000,0.004642,10.000000,"{'multioutputregressor__estimator__C': 100.0, ...",0.065055,0.038927,...,0.754572,0.752828,0.753908,0.755698,0.754580,0.752982,0.754973,0.754228,0.001053,11
41,2.698168,0.017117,0.297641,0.002437,100.000000,0.004642,1.023293,"{'multioutputregressor__estimator__C': 100.0, ...",0.505179,0.459079,...,0.848193,0.845704,0.847894,0.849837,0.847564,0.847646,0.846496,0.847463,0.001252,3
42,1.556256,0.065486,0.304086,0.011650,4.641589,0.100000,10.000000,{'multioutputregressor__estimator__C': 4.64158...,-0.074817,-0.105096,...,-0.016761,-0.016237,-0.016256,-0.015420,-0.015463,-0.016839,-0.015154,-0.015913,0.000587,45
43,1.561713,0.041273,0.305912,0.008107,2.782559,0.100000,10.000000,{'multioutputregressor__estimator__C': 2.78255...,-0.077378,-0.107199,...,-0.047310,-0.046661,-0.046737,-0.046135,-0.046109,-0.047538,-0.045935,-0.046508,0.000575,47
44,2.718340,0.043883,0.300369,0.003850,100.000000,0.004642,1.010745,"{'multioutputregressor__estimator__C': 100.0, ...",0.508374,0.462628,...,0.849096,0.846615,0.848774,0.850753,0.848462,0.848568,0.847366,0.848358,0.001262,2
45,2.705058,0.013359,0.299693,0.003554,100.000000,0.004642,1.002305,"{'multioutputregressor__estimator__C': 100.0, ...",0.510530,0.465024,...,0.849700,0.847224,0.849367,0.851366,0.849073,0.849193,0.847955,0.848960,0.001267,1
46,1.710759,0.030672,0.297250,0.002227,21.544347,1.000000,2.911782,{'multioutputregressor__estimator__C': 21.5443...,0.060652,0.010107,...,0.300722,0.300565,0.300780,0.301759,0.302776,0.300046,0.301961,0.300490,0.001796,35
47,2.015847,0.018785,0.294713,0.003687,59.948425,1.000000,1.112797,{'multioutputregressor__estimator__C': 59.9484...,0.415297,0.368735,...,0.733848,0.730526,0.733077,0.735218,0.733225,0.732221,0.733421,0.732565,0.001394,12
48,1.966883,0.015421,0.298202,0.003688,59.948425,1.000000,2.911782,{'multioutputregressor__estimator__C': 59.9484...,0.184246,0.131635,...,0.645645,0.644360,0.645755,0.646609,0.647033,0.644465,0.647810,0.645388,0.001594,14
49,2.273839,0.012068,0.307170,0.020240,59.948425,0.001000,1.642266,{'multioutputregressor__estimator__C': 59.9484...,0.308313,0.255644,...,0.691223,0.689008,0.691106,0.691992,0.691650,0.689742,0.691984,0.690329,0.001421,13

In [51]:
search.best_score_

np.float64(0.4754122308294789)

In [52]:
search.best_params_

OrderedDict([('multioutputregressor__estimator__C', 100.0),
             ('multioutputregressor__estimator__epsilon',
              0.004641588833612777),
             ('multioutputregressor__estimator__gamma', 1.0023052380778996)])

Looks like the best parameters for SVR (which by the looks of it is performing quite poorly) are:

    - C: 100
    - epsilon: 0.005
    - gamma: 1

In [57]:
# Test performance with Regressor Chaining, given the optimized hyperparamters.
from itertools import permutations

targets = ['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']
combinations = list(permutations(range(len(targets))))

# alkalinity = 0, electrical conductance = 1, dissolved reactive phosphorous = 2
combinations

[(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]

In [67]:
# Test with all possible chain combinations!

svr = SVR(C=100, epsilon=0.005, gamma=1)
scores = []

for combo in combinations:
    chain = RegressorChain(base_estimator=svr, order=combo)
    pipe = make_pipeline(StandardScaler(), chain)

    cv_scores = cross_validate(pipe, X_train_rfe, y_train, cv=5, return_train_score=True, n_jobs=-1)

    scores.append({
        'order': combo,
        'mean_train_score': np.mean(cv_scores['train_score']),
        'mean_test_score': np.mean(cv_scores['test_score']),
        "mean_fit_time": np.mean(cv_scores["fit_time"]),
        "mean_score_time": np.mean(cv_scores["score_time"])
    })

In [68]:
scores_df = pd.DataFrame(scores)
scores_df = scores_df.sort_values(by='mean_test_score', ascending=False)
scores_df

,order,mean_train_score,mean_test_score,mean_fit_time,mean_score_time
1,"(0, 2, 1)",0.686311,0.190337,3.436365,1.794748
0,"(0, 1, 2)",0.461263,0.177547,2.865268,1.673056
4,"(2, 0, 1)",0.694198,0.153516,4.049290,2.103889
5,"(2, 1, 0)",0.490149,0.141511,5.563361,2.744834
2,"(1, 0, 2)",0.332381,0.115743,3.075551,1.814276
3,"(1, 2, 0)",0.334365,0.115688,3.324587,1.825534

Looks like MultiOutputRegression worked much better than Regression Chaining, lets use that instead.

In [ ]:
## FINAL MODEL EVALUATION ON TEST SET TO SEE PERFORMANCE

svr_final = make_pipeline(StandardScaler(), MultiOutputRegressor(SVR(C=100, epsilon=0.005, gamma=1)))
svr_final.fit(X_train_rfe, y_train)
test_score = svr_final.score(X_test_rfe, y_test)
print(test_score)

0.49111691799167495

In [85]:
## Predict Output for Submission Set

submission_df = pd.read_csv('../data/validation_set.csv')
submission_df.head()

,Unnamed: 0,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,elevation,EVI,...,total_precipitation_sum,volumetric_soil_water,precipitation,cec_pH_interaction,phosphorous_pH_interaction,NDVI_LST_interaction,flow_acc_clay_interaction,flow_acc_phosphorous_interaction,evaporation_precipitation_ratio,cec_clay_ratio
0,0,-32.043333,27.822778,01-09-2014,NaN,NaN,NaN,161.90001,780.299056,1628.0,...,0.000007,0.136892,0.000000,1742.0,1742.0,4.542096e+07,351115.714286,338111.428571,-95.760822,0.962963
1,1,-33.329167,26.077500,16-09-2015,NaN,NaN,NaN,177.60000,279.351413,2933.0,...,0.000550,0.259777,27.521283,1495.0,1690.0,1.069767e+08,202225.000000,210314.000000,-3.653135,0.920000
2,2,-32.991639,27.640028,07-05-2015,NaN,NaN,NaN,158.40001,163.622679,4032.0,...,0.000174,0.232120,14.464016,1403.0,1525.0,1.034820e+08,121744.000000,126816.666667,-10.921542,0.958333
3,3,-34.096389,24.439167,07-02-2012,NaN,NaN,NaN,130.00000,44.046365,4701.0,...,NaN,NaN,42.085633,1121.0,1416.0,1.123978e+08,18889.531915,18889.531915,NaN,0.791667
4,4,-32.000556,28.581667,01-10-2014,NaN,NaN,NaN,152.50000,333.249422,1498.0,...,0.000618,0.336999,30.467072,1674.0,1674.0,6.468512e+07,410099.609756,381816.878049,-4.473473,0.931034

In [ ]:
imp_df = submission_df.drop(columns=['Longitude', 'Latitude', 
                                     'Unnamed: 0', 'Sample Date',
                                      'Total Alkalinity', 'Electrical Conductance',
                                      'Dissolved Reactive Phosphorus'])
sumbission_imp_df = mf.transform(imp_df)
imp_df.shape

In [79]:
submission_feats = ['flow_acc_phosphorous_interaction', 'flow_acc_clay_interaction', 'phosphorous_pH_interaction',
               'cec_pH_interaction', 'flow_accumulation', 'phosphorous', 'cec_clay_ratio', 'pet', 'elevation',
               'Land Surface Temperature', 'NDVI', 'volumetric_soil_water', 'total_evaporation_sum', 'MNDWI',
                'swir22', 'clay', 'cec', 'pH', 'EVI', 'soil_temperature', 'evaporation_precipitation_ratio', 
                'nir', 'green', 'NDMI', 'Latitude', 'Longitude', 'Sample Date']

submission_df = submission_df[submission_feats]
submission_df.columns

Index(['flow_acc_phosphorous_interaction', 'flow_acc_clay_interaction',
       'phosphorous_pH_interaction', 'cec_pH_interaction', 'flow_accumulation',
       'phosphorous', 'cec_clay_ratio', 'pet', 'elevation',
       'Land Surface Temperature', 'NDVI', 'volumetric_soil_water',
       'total_evaporation_sum', 'MNDWI', 'swir22', 'clay', 'cec', 'pH', 'EVI',
       'soil_temperature', 'evaporation_precipitation_ratio', 'nir', 'green',
       'NDMI', 'Latitude', 'Longitude', 'Sample Date'],
      dtype='object')

In [81]:
submission_data = submission_df.drop(columns=['Longitude', 'Latitude', 'Sample Date'])

In [82]:
submission_df.shape

(200, 27)

Edit: so this wont actually work because i trained MissForest on the missing target values now and so if i dont feed it target values it cant transform any data and since SVM cant natively handle Nan values there isnt really any way around this without restarting from the very beginning. Since the model performance is quite poor, I have decided to scrap it entirely.